package tuning.calibration.family;

public enum CalibrationFamilyId {
    MATMUL,
    ATTENTION_MATMUL,
    CONV2D_GEMM_DISPATCH,
    FUSED_DISPATCH,
    FUSED_CHEAP_CONTIGUOUS_WIDTH,
    FUSED_CHEAP_STRIDED_WIDTH,
    FUSED_NON_CHEAP_CONTIGUOUS_WIDTH,
    FUSED_NON_CHEAP_STRIDED_WIDTH,
    ELEMENTWISE_DISPATCH,
    REDUCTION,
    ATTENTION_THRESHOLDS,
    SCHEDULER,
    MATERIALIZATION,
    METAL_SELECTION
}
