// GENERATED by scripts/generate-cpu1-elementwise.js. Do not edit by hand.
package backend.cpu1.kernels.elementwise.logical;

import backend.cpu1.exec.Cpu1KernelArgs;
import backend.cpu1.exec.Cpu1TensorView;
import backend.cpu1.offset.Cpu1GenericOffsetPlan;
import jdk.incubator.vector.DoubleVector;
import jdk.incubator.vector.FloatVector;
import jdk.incubator.vector.VectorOperators;
import jdk.incubator.vector.VectorSpecies;
import tensor.dtype.TensorDTypeOps;
import utils.FastTranscendentals;
import utils.SpecialFunctions;

import java.lang.foreign.MemorySegment;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * Static logical_and/logical_or/logical_not loops selected by Cpu1ElementwiseKernelId at prepare time.
 */
public final class Cpu1LogicalLoops {
    private static final VectorSpecies<Float> F32 = FloatVector.SPECIES_PREFERRED;
    private static final VectorSpecies<Double> F64 = DoubleVector.SPECIES_PREFERRED;
    private static final ByteOrder ORDER = ByteOrder.nativeOrder();
    private static final int BROADCAST_CONTIGUOUS = 0;
    private static final int BROADCAST_SCALAR = 1;
    private static final int BROADCAST_INNER = 2;

    private Cpu1LogicalLoops() {
    }

    private static int broadcastVectorMode(Cpu1TensorView view) {
        if (isBroadcastScalar(view)) {
            return BROADCAST_SCALAR;
        }
        if (isBroadcastInner(view)) {
            return BROADCAST_INNER;
        }
        return BROADCAST_CONTIGUOUS;
    }

    private static int broadcastVectorInnerSize(Cpu1TensorView outputView) {
        int rank = outputView.rank();
        return rank == 0 ? 1 : outputView.shape(rank - 1);
    }

    private static boolean isBroadcastScalar(Cpu1TensorView view) {
        for (int dim = 0; dim < view.rank(); dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return true;
    }

    private static boolean isBroadcastInner(Cpu1TensorView view) {
        int rank = view.rank();
        if (rank == 0 || view.contiguous()) {
            return false;
        }
        for (int dim = 0; dim < rank - 1; dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return view.stride(rank - 1) == 1;
    }

    public static void logicalAndBoolArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output[outputOffset] = (byte) (left[leftOffset] != 0 && right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalAndBoolArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        byte[] left = args.input(0).boolArray();
        byte[] right = args.input(1).boolArray();
        byte[] output = args.output().boolArray();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output[outputOffset.offset(i)] = (byte) (left[leftOffset.offset(i)] != 0 && right[rightOffset.offset(i)] != 0 ? 1 : 0);
        }
    }

    public static void logicalAndBoolArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output[outputOffset] = (byte) (left[leftOffset] != 0 && right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalAndBoolArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output[outputOffset] = (byte) (left[leftOffset] != 0 && right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalAndBoolArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output[outputOffset] = (byte) (left[leftOffset] != 0 && right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalNotBoolArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        byte[] input = inputView.boolArray();
        byte[] output = outputView.boolArray();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            boolean value = input[inputOffset] != 0;
            output[outputOffset] = (byte) (!value ? 1 : 0);
        }
    }

    public static void logicalNotBoolArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        byte[] input = args.input(0).boolArray();
        byte[] output = args.output().boolArray();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            boolean value = input[inputOffset.offset(i)] != 0;
            output[outputOffset.offset(i)] = (byte) (!value ? 1 : 0);
        }
    }

    public static void logicalNotBoolArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        byte[] input = inputView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            boolean value = input[inputOffset] != 0;
            output[outputOffset] = (byte) (!value ? 1 : 0);
        }
    }

    public static void logicalNotBoolArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        byte[] input = inputView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            boolean value = input[inputOffset] != 0;
            output[outputOffset] = (byte) (!value ? 1 : 0);
        }
    }

    public static void logicalNotBoolArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        byte[] input = inputView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            boolean value = input[inputOffset] != 0;
            output[outputOffset] = (byte) (!value ? 1 : 0);
        }
    }

    public static void logicalOrBoolArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output[outputOffset] = (byte) (left[leftOffset] != 0 || right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalOrBoolArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        byte[] left = args.input(0).boolArray();
        byte[] right = args.input(1).boolArray();
        byte[] output = args.output().boolArray();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output[outputOffset.offset(i)] = (byte) (left[leftOffset.offset(i)] != 0 || right[rightOffset.offset(i)] != 0 ? 1 : 0);
        }
    }

    public static void logicalOrBoolArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output[outputOffset] = (byte) (left[leftOffset] != 0 || right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalOrBoolArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output[outputOffset] = (byte) (left[leftOffset] != 0 || right[rightOffset] != 0 ? 1 : 0);
        }
    }

    public static void logicalOrBoolArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        byte[] left = leftView.boolArray();
        byte[] right = rightView.boolArray();
        byte[] output = outputView.boolArray();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output[outputOffset] = (byte) (left[leftOffset] != 0 || right[rightOffset] != 0 ? 1 : 0);
        }
    }
}
