package io.github.pho001.synaptik.backend.cpu.internal.ir;

import io.github.pho001.synaptik.model.datatype.DataType;
import java.util.List;
import java.util.Objects;

/**
 * CPU-private generated-code identity for one cumulative sum or product scan.
 *
 * <p>The identity fixes the arithmetic kind, represented data type, normalized logical axis,
 * inclusive/exclusive and forward/reverse modes, structural input/output access forms, and the
 * sequential typed-rounding policy. Concrete extents, layout offsets and stride magnitudes,
 * carrier objects, assigned slots, worker ranges, and run identity remain cold geometry and do
 * not affect compatible generated bytes.</p>
 *
 * @param kind non-null cumulative addition or multiplication
 * @param dataType non-null FLOAT64, FLOAT32, BFLOAT16, INT32, or INT64 represented type
 * @param axis non-negative normalized logical scan axis
 * @param exclusive whether each output precedes incorporation of its input value
 * @param reverse whether traversal starts at the last coordinate of the selected axis
 * @param inputAccess non-null read-only structural input access plan
 * @param outputAccess non-null write-only structural output access plan
 * @param numericalPolicy {@link #SEQUENTIAL_TYPED_ROUNDING}; no other policy is supported
 */
public record CpuScanIr(Kind kind, DataType dataType, int axis, boolean exclusive,
        boolean reverse, CpuAccessPlan inputAccess, CpuAccessPlan outputAccess,
        int numericalPolicy) implements CpuPortableKernelIr {
    /** Supported cumulative arithmetic used by the generated and reference realizations. */
    public enum Kind {
        /** Cumulative addition with represented positive-zero identity. */ CUM_SUM,
        /** Cumulative multiplication with represented positive-one identity. */ CUM_PROD
    }
    /** Sequential same-type arithmetic, with BFLOAT16 rounded after every visited value. */
    public static final int SEQUENTIAL_TYPED_ROUNDING = 1;

    /**
     * Validates and retains one exact generated scan identity.
     *
     * @throws NullPointerException if a reference component is {@code null}
     * @throws IllegalArgumentException if the axis, type, access roles, or numerical policy is
     *     outside the supported scan identity
     */
    public CpuScanIr {
        Objects.requireNonNull(kind, "kind"); Objects.requireNonNull(dataType, "dataType");
        Objects.requireNonNull(inputAccess, "inputAccess");
        Objects.requireNonNull(outputAccess, "outputAccess");
        if (axis < 0 || dataType == DataType.BOOL
                || inputAccess.accessKind() != CpuAccessPlan.AccessKind.READ
                || outputAccess.accessKind() != CpuAccessPlan.AccessKind.WRITE
                || numericalPolicy != SEQUENTIAL_TYPED_ROUNDING) {
            throw new IllegalArgumentException("scan structural facts disagree");
        }
    }

    /**
     * Encodes this scan for the shared generator and compatibility boundary.
     *
     * @return a new canonical instruction-free form with one read input, one write output, and
     *     a deterministic family identity; never {@code null}
     */
    public CpuKernelIr encodedKernelIr() {
        var values = List.of(
                new CpuKernelIr.Value(0, dataType, CpuKernelIr.Value.Kind.INPUT, inputAccess),
                new CpuKernelIr.Value(1, dataType, CpuKernelIr.Value.Kind.OUTPUT, outputAccess));
        return new CpuKernelIr(values, List.of(), new CpuKernelIr.Loop("start", "end"),
                List.of(new CpuKernelIr.Store(1, 0)), "scan:" + kind + ":axis=" + axis
                        + ":exclusive=" + exclusive + ":reverse=" + reverse
                        + ":rounding=" + numericalPolicy);
    }

    /**
     * Returns the deterministic compatibility key for this structural scan identity.
     *
     * @return a non-null lowercase hexadecimal key excluding cold extents, layout magnitudes,
     *     carrier objects, slots, and execution ranges
     */
    @Override public String structuralKey() { return encodedKernelIr().structuralKey(); }
}
