package backend.cpu1.kernels.index;

/**
 * Concrete cpu1 index kernel variants.
 */
public enum Cpu1IndexKernelId {
    GATHER_F32_I32_DENSE_ARRAY,
    GATHER_F32_I64_DENSE_ARRAY,
    GATHER_F64_I32_DENSE_ARRAY,
    GATHER_F64_I64_DENSE_ARRAY,
    GATHER_BF16_I32_DENSE_ARRAY,
    GATHER_BF16_I64_DENSE_ARRAY,
    GATHER_I32_I32_DENSE_ARRAY,
    GATHER_I32_I64_DENSE_ARRAY,
    GATHER_I64_I32_DENSE_ARRAY,
    GATHER_I64_I64_DENSE_ARRAY,
    GATHER_BOOL_I32_DENSE_ARRAY,
    GATHER_BOOL_I64_DENSE_ARRAY
}
