package backend.metal;

/**
 * Stable Metal dtype support reason codes.
 */
public enum MetalDTypeReasonCode {
    SUPPORTED,
    SUPPORTED_STORAGE_ONLY,
    SUPPORTED_PREDICATE_INPUT_ONLY,
    UNSUPPORTED_EXTERNAL_INPUT_DTYPE,
    UNSUPPORTED_EXTERNAL_INPUT_ROLE,
    UNSUPPORTED_NATIVE_COMPUTE_DTYPE,
    UNSUPPORTED_NATIVE_OUTPUT_DTYPE,
    UNSUPPORTED_OPERATION_DTYPE,
    UNSUPPORTED_EXECUTION_ABI_DTYPE,
    FLOAT64_UNSUPPORTED
}
