package tuning.session;

public enum PlatformCalibrationFamily {
    MATMUL,
    ATTENTION_MATMUL,
    FUSED_THRESHOLDS,
    FUSED_CHEAP_CONTIGUOUS,
    FUSED_CHEAP_STRIDED,
    FUSED_NON_CHEAP_CONTIGUOUS,
    FUSED_NON_CHEAP_STRIDED,
    FUSED_ARITHMETIC,
    ELEMENTWISE_DISPATCH,
    REDUCTION,
    ATTENTION_THRESHOLDS,
    SCHEDULER,
    MATERIALIZATION,
    CONV2D,
    NUMERICS
}
