package tuning.session;

public enum PlatformCalibrationFamily {
    MATMUL,
    ATTENTION_MATMUL,
    FUSED_THRESHOLDS,
    FUSED_CHEAP_CONTIGUOUS,
    FUSED_CHEAP_STRIDED,
    FUSED_NON_CHEAP_CONTIGUOUS,
    FUSED_NON_CHEAP_STRIDED,
    FUSED_ARITHMETIC,
    ELEMENTWISE_DISPATCH,
    REDUCTION,
    ATTENTION_THRESHOLDS,
    SCHEDULER,
    MATERIALIZATION,
    CONV2D_GEMM_DISPATCH_F64,
    CONV2D_GEMM_DISPATCH_F32,
    CONV2D_GEMM_DISPATCH_BF16,
    NUMERICS
}
