package tuning.session;

public enum PlatformCalibrationProgressPhase {
    STARTED,
    FAMILY_STARTED,
    WORKLOAD_STARTED,
    CANDIDATE_VALIDATING,
    CANDIDATE_INVALID,
    CANDIDATE_MEASURING,
    CANDIDATE_MEASURED,
    CANDIDATE_FAILED,
    CANDIDATE_SCORED,
    FAMILY_COMPLETED,
    COMPLETED,
    FAILED
}
