// GENERATED by scripts/generate-cpu1-elementwise.js. Do not edit by hand.
package backend.cpu1.kernels.elementwise.unary.erf;

import backend.cpu1.exec.Cpu1KernelArgs;
import backend.cpu1.exec.Cpu1TensorView;
import backend.cpu1.offset.Cpu1GenericOffsetPlan;
import jdk.incubator.vector.DoubleVector;
import jdk.incubator.vector.FloatVector;
import jdk.incubator.vector.VectorOperators;
import jdk.incubator.vector.VectorSpecies;
import tensor.dtype.TensorDTypeOps;
import utils.FastTranscendentals;
import utils.SpecialFunctions;

import java.lang.foreign.MemorySegment;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * Static erf loops selected by Cpu1KernelId at prepare time.
 */
public final class Cpu1ErfLoops {
    private static final VectorSpecies<Float> F32 = FloatVector.SPECIES_PREFERRED;
    private static final VectorSpecies<Double> F64 = DoubleVector.SPECIES_PREFERRED;
    private static final ByteOrder ORDER = ByteOrder.nativeOrder();
    private static final int BROADCAST_CONTIGUOUS = 0;
    private static final int BROADCAST_SCALAR = 1;
    private static final int BROADCAST_INNER = 2;

    private Cpu1ErfLoops() {
    }

    private static int broadcastVectorMode(Cpu1TensorView view) {
        if (isBroadcastScalar(view)) {
            return BROADCAST_SCALAR;
        }
        if (isBroadcastInner(view)) {
            return BROADCAST_INNER;
        }
        return BROADCAST_CONTIGUOUS;
    }

    private static int broadcastVectorInnerSize(Cpu1TensorView outputView) {
        int rank = outputView.rank();
        return rank == 0 ? 1 : outputView.shape(rank - 1);
    }

    private static boolean isBroadcastScalar(Cpu1TensorView view) {
        for (int dim = 0; dim < view.rank(); dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return true;
    }

    private static boolean isBroadcastInner(Cpu1TensorView view) {
        int rank = view.rank();
        if (rank == 0 || view.contiguous()) {
            return false;
        }
        for (int dim = 0; dim < rank - 1; dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return view.stride(rank - 1) == 1;
    }

    public static void bf16ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value));
        }
    }

    public static void bf16ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        short[] input = args.input(0).bfloat16Array();
        short[] output = args.output().bfloat16Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset.offset(i)]);
            output[outputOffset.offset(i)] = TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value));
        }
    }

    public static void bf16ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value));
        }
    }

    public static void bf16ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value));
        }
    }

    public static void bf16ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value));
        }
    }

    public static void bf16SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value)));
        }
    }

    public static void bf16SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset.offset(i)) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset.offset(i)) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value)));
        }
    }

    public static void bf16SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value)));
        }
    }

    public static void bf16SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value)));
        }
    }

    public static void bf16SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(SpecialFunctions.erf(value)));
        }
    }

    public static void f32ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f32ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        float[] input = args.input(0).float32Array();
        float[] output = args.output().float32Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = SpecialFunctions.erf(value);
        }
    }

    public static void f32ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f32ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f32ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f32SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f32SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input.get(JAVA_FLOAT, (long) (inputOffset.offset(i)) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset.offset(i)) * Float.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f32SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f32SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f32SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f64ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f64ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        double[] input = args.input(0).float64Array();
        double[] output = args.output().float64Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = SpecialFunctions.erf(value);
        }
    }

    public static void f64ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f64ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f64ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input[inputOffset];
            output[outputOffset] = SpecialFunctions.erf(value);
        }
    }

    public static void f64SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f64SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset.offset(i)) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset.offset(i)) * Double.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f64SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f64SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, SpecialFunctions.erf(value));
        }
    }

    public static void f64SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, SpecialFunctions.erf(value));
        }
    }
}
