package utils;

/**
 * Internal helper class loader used to define generated bytecode classes.
 */
public class CustomClassLoader extends ClassLoader {
    /**
     * Defines a class from generated bytecode.
     *
     * @param name binary class name
     * @param bytes classfile bytes
     * @return defined class
     */
    public Class<?> define(String name, byte[] bytes) {
        return defineClass(name, bytes, 0, bytes.length);
    }
}
