package backend.accelerator.lowering;

/**
 * Stable reason codes for non-supported GPU lowering matrix rows.
 */
public enum GpuLoweringUnsupportedReason {
    SUPPORTED,
    UNSUPPORTED_OPERATION,
    UNSUPPORTED_DTYPE,
    UNSUPPORTED_LAYOUT,
    UNSUPPORTED_RANK_OR_SHAPE,
    UNSUPPORTED_INDEX_SEMANTICS,
    UNSUPPORTED_IGNORE_INDEX,
    UNSUPPORTED_DUPLICATE_INDEX,
    UNSUPPORTED_BOUNDS_CHECK,
    CAPABILITY_MISSING,
    NATIVE_ABI_MISMATCH,
    DEFERRED_FUSED_REGION,
    CPU_FUSED_OPERATION_UNSUPPORTED,
    COMPOUND_PATTERN_UNSUPPORTED,
    COMPOUND_REGION_SHORTENED,
    DAG_PRIMITIVE_UNSUPPORTED,
    DAG_REGION_BOUNDARY_MATERIALIZATION,
    DAG_CANDIDATE_SHORTENED,
    DAG_FUSED_SUBPATTERN_REJECTED
}
