#!/usr/bin/env python3
import hashlib
import json
import re
import sys
from pathlib import Path

EVIDENCE = Path(__file__).resolve().parent
MANIFEST = json.loads((EVIDENCE / "compiled-generated-msl-audit.json").read_text(encoding="utf-8"))


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_stripped(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> None:
    require(len(sys.argv) == 2, "usage: verify-compiled-generated-msl-audit.py WORK")
    work = Path(sys.argv[1]).resolve()
    require(MANIFEST["developerDir"] == "/Applications/Xcode.app/Contents/Developer", "unapproved developer directory")
    require(read_stripped(work / "sdk-path.txt") == MANIFEST["sdkPath"], "SDK path drift")
    require(read_stripped(work / "sdk-version.txt") == MANIFEST["sdkVersion"], "SDK version drift")
    require(read_stripped(work / "sdk-build.txt") == MANIFEST["sdkBuild"], "SDK build drift")
    require(read_stripped(work / "xcode-version.txt") == MANIFEST["xcode"], "Xcode version drift")
    require(read_stripped(work / "metal-version.txt") == MANIFEST["metal"], "Metal compiler version drift")
    require(read_stripped(work / "metallib-version.txt") == MANIFEST["metallib"], "metallib version drift")
    expected_runtime_reflection = {
        "pipelineOptions": ["MTLPipelineOptionBindingInfo", "MTLPipelineOptionBufferTypeInfo"],
        "input": {
            "name": "input",
            "index": 0,
            "bindingAccess": "readOnly",
            "pointerAccess": "readOnly",
            "elementType": "uint",
            "alignment": 4,
            "bytes": 4,
        },
        "output": {
            "name": "output",
            "index": 1,
            "bindingAccess": "readWrite",
            "pointerAccess": "readWrite",
            "elementType": "uint",
            "alignment": 4,
            "bytes": 4,
            "airAccess": "writeOnly",
        },
        "meta": {
            "name": "meta",
            "index": 2,
            "bindingAccess": "readOnly",
            "pointerAccess": "readOnly",
            "dataType": "struct",
            "alignment": 8,
            "bytes": 32,
            "members": [
                {"name": "elementCount", "type": "ulong", "offset": 0},
                {"name": "gridWidth", "type": "ulong", "offset": 8},
                {"name": "gridHeight", "type": "ulong", "offset": 16},
                {"name": "scalar", "type": "uint", "offset": 24},
                {"name": "reserved", "type": "uint", "offset": 28},
            ],
        },
    }
    require(
        MANIFEST["runtimeReflection"] == expected_runtime_reflection,
        "runtime reflection evidence drift",
    )

    for name, expected in MANIFEST["artifacts"].items():
        path = work / name
        require(path.is_file(), f"missing audit artifact: {name}")
        if expected.get("nondeterministicContainer"):
            require(expected == {"required": True, "nondeterministicContainer": True},
                    f"unapproved compiled-container policy: {name}")
            require(path.stat().st_size > 0, f"empty compiled container: {name}")
            continue
        require(path.stat().st_size == expected["bytes"], f"byte count drift: {name}")
        require(digest(path) == expected["sha256"], f"SHA-256 drift: {name}")

    metadata = json.loads((work / "fixtures.json").read_text(encoding="utf-8"))
    fixed_facts = MANIFEST["fixedCorpus"]
    require(metadata["fixedBytes"] == fixed_facts["bytes"], "fixed corpus byte count drift")
    require(metadata["fixedSha256"] == fixed_facts["sha256"], "fixed corpus metadata hash drift")
    require(metadata["components"] == fixed_facts["components"], "fixed component ledger drift")
    require(
        metadata["generatedBytes"] == 49 + sum(f["bytes"] for f in MANIFEST["fixtures"]),
        "generated byte formula drift",
    )
    require(
        metadata["totalBytes"] == metadata["fixedBytes"] + metadata["generatedBytes"],
        "total source byte formula drift",
    )
    expected_metadata = []
    for fixture in MANIFEST["fixtures"]:
        expected_metadata.append({
            "functionBytes": fixture["bytes"],
            "opcodes": [opcode.lower() for opcode in fixture["instructions"]],
            "siteKind": fixture["siteKind"],
            "step": fixture["step"],
        })
    require(metadata["fixtures"] == expected_metadata, "fixture instruction manifest drift")
    require(
        [fixture["instructions"] for fixture in MANIFEST["fixtures"][:4]]
        == [["FLOOR"], ["CEIL"], ["SIGN"], ["RELU"]],
        "singleton operation ledger drift",
    )
    require(
        [len(fixture["instructions"]) for fixture in MANIFEST["fixtures"][4:]]
        == list(range(2, 9)),
        "2..8 chain ledger drift",
    )

    source = (work / "generated-fixtures.metal").read_text(encoding="utf-8")
    fixed = source[:MANIFEST["fixedCorpus"]["bytes"]].encode("utf-8")
    require(hashlib.sha256(fixed).hexdigest() == MANIFEST["fixedCorpus"]["sha256"], "fixed corpus hash drift")
    require(source.count("kernel void synaptik_pw_g1_s") == len(MANIFEST["fixtures"]), "generated function count drift")
    require("#include <metal_stdlib>\nusing namespace metal;\n" in source, "generated source prefix absent")
    generated = source[MANIFEST["fixedCorpus"]["bytes"]:]
    require(
        hashlib.sha256(generated.encode("utf-8")).hexdigest()
        == metadata["generatedSha256"],
        "generated source hash drift",
    )
    require(
        hashlib.sha256(source.encode("utf-8")).hexdigest()
        == metadata["assembledSha256"],
        "assembled source hash drift",
    )
    for fixture in MANIFEST["fixtures"]:
        symbol = fixture["name"]
        function = re.search(
            rf"kernel void {re.escape(symbol)}\(.*?\n\}}",
            generated,
            flags=re.DOTALL,
        )
        require(function is not None, f"generated source site absent: {symbol}")
        body = function.group(0)
        helpers = re.findall(r"= (floor_bits|ceil_bits|sign_bits|relu_bits)\(", body)
        require(
            helpers == [opcode.lower() + "_bits" for opcode in fixture["instructions"]],
            f"generated source opcode ledger drift: {symbol}",
        )

    ir = (work / "generated-fixtures.air.ll.canonical").read_text(encoding="utf-8")
    nm = (work / "generated-fixtures.air.nm.canonical").read_text(encoding="utf-8")
    facts = MANIFEST["requiredAirFacts"]
    require(facts["pointMetaType"] in ir, "PointMeta AIR layout drift")
    for symbol in facts["generatedSymbols"]:
        nm_lines = [line for line in nm.splitlines() if line.endswith(" T " + symbol)]
        require(len(nm_lines) == 1, f"generated AIR symbol missing or duplicated: {symbol}")
        match = re.search(rf"^define void @{re.escape(symbol)}\((.*?)\n\}}", ir, flags=re.MULTILINE | re.DOTALL)
        require(match is not None, f"generated AIR body absent: {symbol}")
        body = match.group(0)
        signature = body.splitlines()[0]
        require(signature.count('"air-buffer-no-alias"') == facts["bufferCount"], f"buffer reflection count drift: {symbol}")
        require('i32 addrspace(1)* nocapture noundef readonly' in signature, f"input access drift: {symbol}")
        require('i32 addrspace(1)* nocapture noundef writeonly' in signature, f"output access drift: {symbol}")
        require(f'dereferenceable({facts["pointMetaBytes"]})' in signature and 'align 8' in signature, f"PointMeta binding drift: {symbol}")
        require(body.count("load i32, i32 addrspace(1)*") == 1, f"generated unit must load one boundary input: {symbol}")
        require(body.count("store i32") == 1, f"generated unit must store one boundary output: {symbol}")
        require(not re.search(r"\b(fast|contract|reassoc|afn)\b", body), f"fast-math flag present: {symbol}")
        require("call void @exact_" not in body, f"generated unit retained an unfused helper call: {symbol}")
        require(
            not re.search(
                r"\b(fadd|fsub|fmul|fdiv|frem|fcmp|sitofp|uitofp|fptosi|fptoui)\b",
                body,
            ),
            f"floating AIR operation present in raw helper site: {symbol}",
        )

    print("Task 0070 compiled generated-MSL audit passed")


if __name__ == "__main__":
    main()
