/**
 * Defines unsupported portable-route realization facts over common CPU lowering.
 *
 * <p>The route plan pairs route-independent canonical IR with the exact Class-File specialization
 * selected by common CPU analysis. The specialization contains exactly one scalar or
 * preferred-species vector body; parallel orchestration reuses that body and stays outside the
 * generated class. The plan may be consumed by artifact realization and finalization, but it does
 * not interpret graph semantics, own the scalar reference implementation, select a native
 * provider, schedule workers, or declare resource lifetime.
 * A functional-scatter specialization embeds its selected family, represented type, reduction,
 * carrier accesses, and output-domain contribution loop. It may additionally expose one direct
 * scratch-segment parameter when its already-lowered floating-product row requires the declared
 * per-range accumulator; the exact-product state machine is embedded in that generated entry.
 * Complete index and replacement-uniqueness validation remains outside generated work. Concrete
 * geometry, workspace identity, size, slice offset, and lifetime remain prepared invocation facts
 * rather than route or artifact-selection decisions.
 * A fold specialization remains a two-boundary workspace-free scalar artifact and embeds its
 * family, represented type, access form, mapping, and sequential addition body; parallel-scalar
 * orchestration reuses that same artifact over disjoint output-coordinate ranges.
 * An ordering specialization remains scalar and adds one direct scratch-segment parameter. SORT
 * and ARGSORT have two boundaries; TOP_K has three and writes both outputs from one artifact.
 * Its generated class embeds the typed stable merge, comparison, selected-pair ordering, and
 * represented value/index stores for the selected carrier and access form.
 * Concrete workspace identity, slice offset, axis, K, and slice ranges stay in the bound
 * invocation, while parallel-scalar orchestration assigns complete disjoint slices.
 * A random specialization remains scalar and workspace-free. It has one initializer output or
 * five ordered dropout boundaries; cold invocation geometry owns concrete layouts, while
 * explicit dropout state values remain direct input data.
 * A cumulative-scan specialization remains scalar, has exactly one input and one output, and
 * carries no scratch parameter. Parallel-scalar orchestration reuses the same artifact over
 * complete independent slices; concrete extents, layouts, carriers, and range count stay cold.
 * An ordinary aggregate specialization is likewise scalar and two-boundary. Floating numerical
 * rows add one exact scratch-segment parameter; integral numerical, extrema, and Boolean rows are
 * scratch-free. Its generated entry embeds the typed output-cell body; concrete layouts, parallel
 * output ranges, and assigned workspace identity stay cold, while numerical domain/state shape is
 * structural where it changes generated bytes or resource size.
 * An arg-extrema specialization is independently scalar and workspace-free, with one numeric
 * input and one INT64 output. Its generated body embeds kind, type, axis role, keep/remove form,
 * tie policy, carrier accesses, and structural ranks; resolved layout magnitudes stay in cold
 * invocation geometry.
 * A masked SUM/MEAN specialization is scalar and has typed data, canonical-BOOL mask, and output
 * boundaries followed by one exact-state scratch segment. Its generated body embeds the mask
 * topology, early false branch, selected-count work, and exact finalization; concrete layout
 * magnitudes, range count, carriers, scratch identity, and per-range slice offsets stay cold.
 * An advanced-reduction specialization has one floating input and matching output. LOG_SUM_EXP
 * and L2_NORM are workspace-free; L1_NORM and both statistical kinds add the existing exact-state
 * scratch parameter. The generated body fixes axes, correction, pass shape, and numerical owner,
 * while resolved layout magnitudes and complete-output-cell ranges remain cold.
 * A softmax specialization is scalar, workspace-free, and has one matching floating input/output
 * pair. Kind, type, axis role, algorithm/pass shape, access plans, and carrier pattern shape
 * generated bytes; compatible extents, stride magnitudes, ranges, workers, bases, and values stay
 * cold.
 * A batch-normalization training specialization is scalar, retains unique inputs followed by
 * five outputs, and adds one exact-state scratch parameter. Its generated entry fixes the
 * three-pass complete-channel algorithm and typed statistic transitions; concrete layouts,
 * selected range count, workspace identity, slice offsets, carriers, and values remain cold.
 *
 * <p>The plan is immutable cold-path state; route dispatch never occurs inside the generated loop.
 */
package io.github.pho001.synaptik.backend.cpu.internal.route.portable;
