#ifndef SYNAPTIK_TASK0063_ORDERING_KERNELS_H
#define SYNAPTIK_TASK0063_ORDERING_KERNELS_H

static NSString *const SynaptikTask0063OrderingKernelSource =
@"\n"
"struct OrderingMeta { uint elementCount; uint outputCount; uint axisLength; uint inner; uint k; uint valueType; uint width; uint direction; uint sorted; uint tieLast; };\n"
"inline ulong ordering_word(device const uchar *input,uint index,constant OrderingMeta &m){ulong word=0ul,offset=ulong(index)*ulong(m.width);for(uint byte=0u;byte<m.width;++byte)word|=ulong(input[offset+ulong(byte)])<<(byte*8u);return word;}\n"
"inline void ordering_store(device uchar *output,uint index,ulong word,constant OrderingMeta &m){ulong offset=ulong(index)*ulong(m.width);for(uint byte=0u;byte<m.width;++byte)output[offset+ulong(byte)]=uchar((word>>(byte*8u))&0xfful);}\n"
"inline bool ordering_nan(ulong word,uint type){if(type==1u)return (word&0x7f800000ul)==0x7f800000ul&&(word&0x007ffffful)!=0ul;if(type==4u)return (word&0x7ff0000000000000ul)==0x7ff0000000000000ul&&(word&0x000ffffffffffffful)!=0ul;if(type==5u)return (word&0x7f80ul)==0x7f80ul&&(word&0x007ful)!=0ul;return false;}\n"
"inline ulong ordering_key(ulong word,uint type){if(type==1u)return (word&0x80000000ul)!=0ul?(~word&0xfffffffful):(word^0x80000000ul);if(type==4u)return (word&0x8000000000000000ul)!=0ul?~word:(word^0x8000000000000000ul);if(type==5u)return (word&0x8000ul)!=0ul?(~word&0xfffful):(word^0x8000ul);if(type==2u)return (word^0x80000000ul)&0xfffffffful;if(type==6u)return word^0x8000000000000000ul;return word&1ul;}\n"
"inline bool ordering_before(ulong left,uint leftIndex,ulong right,uint rightIndex,bool descending,uint type){bool leftNan=ordering_nan(left,type),rightNan=ordering_nan(right,type);if(leftNan||rightNan){if(leftNan!=rightNan)return !leftNan;return leftIndex<rightIndex;}ulong leftKey=ordering_key(left,type),rightKey=ordering_key(right,type);if(leftKey!=rightKey)return descending?leftKey>rightKey:leftKey<rightKey;return leftIndex<rightIndex;}\n"
"inline uint ordering_rank(device const uchar *input,uint base,uint source,constant OrderingMeta &m,bool descending){ulong selected=ordering_word(input,base+source*m.inner,m);uint rank=0u;for(uint candidate=0u;candidate<m.axisLength;++candidate){ulong word=ordering_word(input,base+candidate*m.inner,m);if(ordering_before(word,candidate,selected,source,descending,m.valueType))++rank;}return rank;}\n"
"kernel void exact_sort_0063(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant OrderingMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){uint linear=gid.x;if(linear>=m.elementCount)return;uint source=(linear/m.inner)%m.axisLength,outer=linear/(m.axisLength*m.inner),inside=linear%m.inner,base=outer*m.axisLength*m.inner+inside,rank=ordering_rank(input,base,source,m,m.direction!=0u),destination=base+rank*m.inner;ordering_store(output,destination,ordering_word(input,linear,m),m);}\n"
"kernel void exact_argsort_0063(device const uchar *input [[buffer(0)]],device long *output [[buffer(1)]],constant OrderingMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){uint linear=gid.x;if(linear>=m.elementCount)return;uint source=(linear/m.inner)%m.axisLength,outer=linear/(m.axisLength*m.inner),inside=linear%m.inner,base=outer*m.axisLength*m.inner+inside,rank=ordering_rank(input,base,source,m,m.direction!=0u),destination=base+rank*m.inner;output[destination]=long(source);}\n"
"kernel void exact_top_k_0063(device const uchar *input [[buffer(0)]],device uchar *values [[buffer(1)]],device long *indices [[buffer(2)]],constant OrderingMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){uint linear=gid.x;if(linear>=m.elementCount)return;uint source=(linear/m.inner)%m.axisLength,outer=linear/(m.axisLength*m.inner),inside=linear%m.inner,base=outer*m.axisLength*m.inner+inside,rank=ordering_rank(input,base,source,m,m.direction!=0u);if(rank>=m.k)return;uint position=rank;if(m.sorted==0u){position=0u;for(uint candidate=0u;candidate<source;++candidate)if(ordering_rank(input,base,candidate,m,m.direction!=0u)<m.k)++position;}uint destination=outer*m.k*m.inner+position*m.inner+inside;ordering_store(values,destination,ordering_word(input,linear,m),m);indices[destination]=long(source);}\n"
"inline bool arg_better(ulong candidate,uint candidateIndex,ulong best,uint bestIndex,bool maximum,constant OrderingMeta &m){bool candidateNan=ordering_nan(candidate,m.valueType),bestNan=ordering_nan(best,m.valueType);if(candidateNan!=bestNan)return candidateNan;if(candidateNan)return m.tieLast!=0u?candidateIndex>bestIndex:candidateIndex<bestIndex;ulong candidateKey=ordering_key(candidate,m.valueType),bestKey=ordering_key(best,m.valueType);if(candidateKey!=bestKey)return maximum?candidateKey>bestKey:candidateKey<bestKey;return m.tieLast!=0u?candidateIndex>bestIndex:candidateIndex<bestIndex;}\n"
"inline void exact_arg_extreme_0063(device const uchar *input,device long *output,constant OrderingMeta &m,uint3 gid,bool maximum){uint linear=gid.x;if(linear>=m.outputCount)return;uint outer=linear/m.inner,inside=linear%m.inner,base=outer*m.axisLength*m.inner+inside,bestIndex=0u;ulong best=ordering_word(input,base,m);for(uint candidate=1u;candidate<m.axisLength;++candidate){ulong word=ordering_word(input,base+candidate*m.inner,m);if(arg_better(word,candidate,best,bestIndex,maximum,m)){best=word;bestIndex=candidate;}}output[linear]=long(bestIndex);}\n"
"kernel void exact_arg_max_0063(device const uchar *input [[buffer(0)]],device long *output [[buffer(1)]],constant OrderingMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){exact_arg_extreme_0063(input,output,m,gid,true);}\n"
"kernel void exact_arg_min_0063(device const uchar *input [[buffer(0)]],device long *output [[buffer(1)]],constant OrderingMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){exact_arg_extreme_0063(input,output,m,gid,false);}\n";

#endif
