#ifndef SYNAPTIK_TASK0071_ANCHOR_EPILOGUE_KERNELS_H
#define SYNAPTIK_TASK0071_ANCHOR_EPILOGUE_KERNELS_H

static NSString *const SynaptikTask0071AnchorEpilogueKernelSource =
@"\n"
"struct AnchorEpilogueMeta { DataMeta data; ulong addStrides[16]; ulong addOffset; uint scalarBits; uint lowerBits; uint upperBits; uint flags; uint addRank; uint reserved0; uint reserved1; uint reserved2; };\n"
"inline float anchor_mul_site_0071(float value, float scalar) { return value * scalar; }\n"
"inline float anchor_add_site_0071(float left, float right) { return left + right; }\n"
"inline float anchor_before_add_0071(float value, constant AnchorEpilogueMeta &m) { return (m.flags & 1u) != 0u ? anchor_mul_site_0071(value, as_type<float>(m.scalarBits)) : value; }\n"
"inline ulong anchor_add_offset_0071(ulong linear, constant AnchorEpilogueMeta &m) { ulong coords[16]; decode_coords(linear, m.data.outDims, m.data.outputRank, coords); ulong offset = m.addOffset; for (uint axis = 0u; axis < m.data.outputRank; ++axis) offset += coords[axis] * m.addStrides[axis]; return offset; }\n"
"inline float anchor_with_add_0071(float value, device const uchar *addend, ulong linear, constant AnchorEpilogueMeta &m) { float external = as_type<float>(uint(load_word(addend, anchor_add_offset_0071(linear, m), 4u))); return (m.flags & 16u) != 0u ? anchor_add_site_0071(external, value) : anchor_add_site_0071(value, external); }\n"
"inline uint anchor_terminal_0071(float value, constant AnchorEpilogueMeta &m) { uint word = as_type<uint>(value); if ((m.flags & 4u) != 0u) return relu_bits(word); if ((m.flags & 8u) != 0u) { uint lowered = exact_extreme(word, m.lowerBits, true); return exact_extreme(lowered, m.upperBits, false); } return word; }\n"
"inline float conv2d_value_0071(device const uchar *input, device const uchar *weight, device const uchar *bias, ulong linear, constant DataMeta &m) { ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); ulong groups = m.attrs[6]; ulong outputsPerGroup = m.outDims[1] / groups; ulong group = out[1] / outputsPerGroup; float accumulator = m.inputCount == 3u ? load_f32_0064(bias, out[1], m.reserved) : 0.0f; for (ulong ic = 0ul; ic < m.auxDims[1]; ++ic) for (ulong kh = 0ul; kh < m.auxDims[2]; ++kh) for (ulong kw = 0ul; kw < m.auxDims[3]; ++kw) { long ih = long(out[2] * m.attrs[0] + kh * m.attrs[4]) - long(m.attrs[2]); long iw = long(out[3] * m.attrs[1] + kw * m.attrs[5]) - long(m.attrs[3]); ulong wc[16] = {out[1], ic, kh, kw}; float w = load_f32_0064(weight, auxiliary_offset_0064(m, wc), m.indexType); float x = 0.0f; if (ih >= 0l && iw >= 0l && ulong(ih) < m.inDims[2] && ulong(iw) < m.inDims[3]) { ulong xc[16] = {out[0], group * m.auxDims[1] + ic, ulong(ih), ulong(iw)}; x = load_f32_0064(input, input_offset_0064(m, xc), m.sourceType); } accumulator = fma(x, w, accumulator); } return accumulator; }\n"
"kernel void matmul_f32_f32_f32_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant AnchorEpilogueMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, false, false), m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void matmul_f32_bf16_f32_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant AnchorEpilogueMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, false, true), m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void matmul_bf16_f32_f32_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant AnchorEpilogueMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, true, false), m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void matmul_f32_f32_f32_add_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device const uchar *addend [[buffer(2)]], device uchar *output [[buffer(3)]], constant AnchorEpilogueMeta &m [[buffer(4)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, false, false), m); value = anchor_with_add_0071(value, addend, linear, m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void matmul_f32_bf16_f32_add_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device const uchar *addend [[buffer(2)]], device uchar *output [[buffer(3)]], constant AnchorEpilogueMeta &m [[buffer(4)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, false, true), m); value = anchor_with_add_0071(value, addend, linear, m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void matmul_bf16_f32_f32_add_epilogue_0071(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device const uchar *addend [[buffer(2)]], device uchar *output [[buffer(3)]], constant AnchorEpilogueMeta &m [[buffer(4)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m.data); if (linear >= m.data.elementCount) return; float value = anchor_before_add_0071(matmul_f32_0061(left, right, linear, m.data, true, false), m); value = anchor_with_add_0071(value, addend, linear, m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void conv2d_epilogue_0071(device const uchar *input [[buffer(0)]], device const uchar *weight [[buffer(1)]], device const uchar *bias [[buffer(2)]], device uchar *output [[buffer(3)]], constant AnchorEpilogueMeta &m [[buffer(4)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.data.elementCount) return; float value = conv2d_value_0071(input, weight, bias, linear, m.data); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n"
"kernel void conv2d_add_epilogue_0071(device const uchar *input [[buffer(0)]], device const uchar *weight [[buffer(1)]], device const uchar *bias [[buffer(2)]], device const uchar *addend [[buffer(3)]], device uchar *output [[buffer(4)]], constant AnchorEpilogueMeta &m [[buffer(5)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.data.elementCount) return; float value = conv2d_value_0071(input, weight, bias, linear, m.data); value = anchor_with_add_0071(value, addend, linear, m); store_word(output, linear, 4u, ulong(anchor_terminal_0071(value, m))); }\n";

#endif
