#ifndef SYNAPTIK_TASK0059_DATA_KERNELS_H
#define SYNAPTIK_TASK0059_DATA_KERNELS_H

static NSString *const SynaptikTask0059DataKernelSource =
@"\n"
"struct DataMeta { ulong inDims[16]; ulong outDims[16]; ulong auxDims[16]; ulong inputStrides[16]; ulong outputStrides[16]; ulong auxiliaryStrides[16]; ulong inputOffset; ulong outputOffset; ulong auxiliaryOffset; ulong inputExtents[16]; ulong inputPrefixes[16]; ulong attrs[65]; ulong elementCount; ulong gridWidth; ulong gridHeight; uint operation; uint inputRank; uint outputRank; uint auxRank; uint width; uint sourceType; uint targetType; uint inputCount; uint attributeKind; uint attributeCount; uint indexType; uint reserved; ulong roleDims[16][16]; ulong roleStrides[16][16]; ulong roleOffsets[16]; uint roleRanks[16]; };\n"
"inline ulong data_linear_id(uint3 gid, constant DataMeta &m) { return ulong(gid.x) + m.gridWidth * (ulong(gid.y) + m.gridHeight * ulong(gid.z)); }\n"
"inline void decode_coords(ulong linear, constant ulong *dims, uint rank, thread ulong *coords) { for (int axis = int(rank) - 1; axis >= 0; --axis) { coords[axis] = linear % dims[axis]; linear /= dims[axis]; } }\n"
"inline ulong coords_linear(thread const ulong *coords, constant ulong *dims, uint rank) { ulong linear = 0ul; for (uint axis = 0u; axis < rank; ++axis) linear = linear * dims[axis] + coords[axis]; return linear; }\n"
"inline ulong coords_storage(thread const ulong *coords, constant ulong *strides, uint rank, ulong base) { ulong offset = base; for (uint axis = 0u; axis < rank; ++axis) offset += coords[axis] * strides[axis]; return offset; }\n"
"inline ulong logical_storage(ulong linear, constant ulong *dims, constant ulong *strides, uint rank, ulong base) { ulong coords[16]; decode_coords(linear, dims, rank, coords); return coords_storage(coords, strides, rank, base); }\n"
"inline ulong load_word(device const uchar *input, ulong offset, uint width) { ulong word = 0ul; for (uint byte = 0u; byte < width; ++byte) word |= ulong(input[offset * ulong(width) + byte]) << (byte * 8u); return word; }\n"
"inline void store_word(device uchar *output, ulong offset, uint width, ulong word) { for (uint byte = 0u; byte < width; ++byte) output[offset * ulong(width) + byte] = uchar(word >> (byte * 8u)); }\n"
"inline void copy_word(device const uchar *input, ulong inputOffset, device uchar *output, ulong outputOffset, uint width) { for (uint byte = 0u; byte < width; ++byte) output[outputOffset * ulong(width) + byte] = input[inputOffset * ulong(width) + byte]; }\n"
"inline bool source_nonzero(ulong word, uint type) { if (type == 1u) return (word & 0x7ffffffful) != 0ul; if (type == 4u) return (word & 0x7ffffffffffffffful) != 0ul; if (type == 5u) return (word & 0x7ffful) != 0ul; if (type == 2u) return uint(word) != 0u; if (type == 6u) return word != 0ul; return (word & 0xfful) != 0ul; }\n"
"inline ulong bool_target_word(bool value, uint target) { if (!value) return 0ul; if (target == 1u) return 0x3f800000ul; if (target == 4u) return 0x3ff0000000000000ul; if (target == 5u) return 0x3f80ul; return 1ul; }\n"
"kernel void exact_cast_0059(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; ulong word = load_word(input, linear, m.width); ulong converted; uint outWidth = m.targetType == 3u ? 1u : m.targetType == 5u ? 2u : (m.targetType == 1u || m.targetType == 2u) ? 4u : 8u; if (m.sourceType == m.targetType) converted = word; else if (m.sourceType == 3u) converted = bool_target_word((word & 0xfful) != 0ul, m.targetType); else if (m.targetType == 3u) converted = source_nonzero(word, m.sourceType) ? 1ul : 0ul; else if (m.sourceType == 2u && m.targetType == 6u) converted = ulong(long(int(uint(word)))); else if (m.sourceType == 6u && m.targetType == 2u) converted = ulong(uint(word)); else converted = ulong(uint(word & 0xfffful) << 16u); store_word(output, linear, outWidth, converted); }\n"
"inline ulong slice_source(ulong outputLinear, constant DataMeta &m) { ulong out[16]; ulong src[16]; decode_coords(outputLinear, m.outDims, m.outputRank, out); if (m.attributeKind == 15u) { uint rank = uint(m.attrs[0]); uint prefixOffset = 1u + rank; for (uint axis = 0u; axis < rank; ++axis) src[axis] = out[axis] + m.attrs[prefixOffset + 1u + axis]; } else { for (uint axis = 0u; axis < m.inputRank; ++axis) src[axis] = out[axis]; uint count = uint(m.attrs[0]); for (uint item = 0u; item < count; ++item) { uint axis = uint(m.attrs[1u + count * 2u + item]); src[axis] = m.attrs[1u + item] + out[axis] * m.attrs[1u + count * 3u + item]; } } return coords_storage(src, m.inputStrides, m.inputRank, m.inputOffset); }\n"
"inline bool pad_source(ulong outputLinear, constant DataMeta &m, thread ulong &source) { ulong out[16]; ulong src[16]; decode_coords(outputLinear, m.outDims, m.outputRank, out); uint rank = uint(m.attrs[0]); for (uint axis = 0u; axis < rank; ++axis) { ulong before = m.attrs[1u + axis]; if (out[axis] < before || out[axis] - before >= m.inDims[axis]) return false; src[axis] = out[axis] - before; } source = coords_linear(src, m.inDims, rank); return true; }\n"
"inline bool unfold2_source(ulong outputLinear, constant DataMeta &m, thread ulong &source) { ulong out[16]; decode_coords(outputLinear, m.outDims, 3u, out); ulong kH=m.attrs[0], kW=m.attrs[1], sH=m.attrs[2], sW=m.attrs[3], pH=m.attrs[4], pW=m.attrs[5], dH=m.attrs[6], dW=m.attrs[7]; ulong c = out[1] / (kH*kW); ulong rem = out[1] % (kH*kW); ulong kh=rem/kW, kw=rem%kW; ulong outW = m.outDims[2] == 0ul ? 0ul : ((m.inDims[3]+2ul*pW-(dW*(kW-1ul)+1ul))/sW + (((m.attrs[8]!=0ul)&&((m.inDims[3]+2ul*pW-(dW*(kW-1ul)+1ul))%sW!=0ul))?1ul:0ul) + 1ul); ulong oh=out[2]/outW, ow=out[2]%outW; long ih=long(oh*sH+kh*dH)-long(pH), iw=long(ow*sW+kw*dW)-long(pW); if (ih<0l || iw<0l || ulong(ih)>=m.inDims[2] || ulong(iw)>=m.inDims[3]) return false; source=((out[0]*m.inDims[1]+c)*m.inDims[2]+ulong(ih))*m.inDims[3]+ulong(iw); return true; }\n"
"inline bool unfold3_source(ulong outputLinear, constant DataMeta &m, thread ulong &source) { ulong out[16]; decode_coords(outputLinear, m.outDims, 3u, out); ulong kD=m.attrs[0], kH=m.attrs[1], kW=m.attrs[2], sD=m.attrs[3], sH=m.attrs[4], sW=m.attrs[5], pD=m.attrs[6], pH=m.attrs[7], pW=m.attrs[8], dD=m.attrs[9], dH=m.attrs[10], dW=m.attrs[11]; ulong volume=kD*kH*kW, c=out[1]/volume, rem=out[1]%volume, kd=rem/(kH*kW); rem%=kH*kW; ulong kh=rem/kW,kw=rem%kW; ulong nW=m.inDims[4]+2ul*pW-(dW*(kW-1ul)+1ul), oW=nW/sW+(((m.attrs[12]!=0ul)&&(nW%sW!=0ul))?1ul:0ul)+1ul; ulong nH=m.inDims[3]+2ul*pH-(dH*(kH-1ul)+1ul),oH=nH/sH+(((m.attrs[12]!=0ul)&&(nH%sH!=0ul))?1ul:0ul)+1ul; ulong od=out[2]/(oH*oW), pos=out[2]%(oH*oW),oh=pos/oW,ow=pos%oW; long id=long(od*sD+kd*dD)-long(pD), ih=long(oh*sH+kh*dH)-long(pH), iw=long(ow*sW+kw*dW)-long(pW); if(id<0l||ih<0l||iw<0l||ulong(id)>=m.inDims[2]||ulong(ih)>=m.inDims[3]||ulong(iw)>=m.inDims[4]) return false; source=(((out[0]*m.inDims[1]+c)*m.inDims[2]+ulong(id))*m.inDims[3]+ulong(ih))*m.inDims[4]+ulong(iw); return true; }\n"
"kernel void exact_move_unary_0059(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint3 gid [[thread_position_in_grid]]) { ulong linear=data_linear_id(gid,m); if(linear>=m.elementCount)return; ulong source=linear,destination=linear; bool copied=true; ulong fill=0ul; if(m.operation==73u){ ulong out[16],src[16]; decode_coords(linear,m.outDims,m.outputRank,out); uint axis=uint(m.attrs[0]); for(uint s=0u,t=0u;s<m.inputRank;++s)src[s]=s==axis?m.attrs[1]:out[t++]; source=coords_storage(src,m.inputStrides,m.inputRank,m.inputOffset); destination=coords_storage(out,m.outputStrides,m.outputRank,m.outputOffset); } else if(m.operation==74u){ copied=pad_source(linear,m,source); fill=m.attrs[2u+uint(m.attrs[0])*2u]; } else if(m.operation==75u){ source=slice_source(linear,m); destination=logical_storage(linear,m.outDims,m.outputStrides,m.outputRank,m.outputOffset); } else if(m.operation==79u){ ulong out[16],src[16]; decode_coords(linear,m.outDims,m.outputRank,out); for(uint a=0u;a<m.inputRank;++a)src[a]=out[a]%m.inDims[a]; source=coords_linear(src,m.inDims,m.inputRank); } else if(m.operation==81u){ copied=unfold2_source(linear,m,source); fill=m.attributeKind==20u?m.attrs[10]:0ul; } else if(m.operation==83u){ copied=unfold3_source(linear,m,source); fill=m.attributeKind==23u?m.attrs[14]:0ul; } if(copied)copy_word(input,source,output,destination,m.width); else store_word(output,destination,m.width,fill); }\n"
"inline long read_index(device const uchar *indices, ulong offset, uint type) { ulong word=load_word(indices,offset,type==2u?4u:8u); return type==2u?long(int(uint(word))):long(word); }\n"
"kernel void exact_move_binary_0059(device const uchar *data [[buffer(0)]], device const uchar *indices [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear=data_linear_id(gid,m); if(linear>=m.elementCount)return; ulong source=0ul; if(m.operation==69u){ ulong out[16];decode_coords(linear,m.outDims,m.outputRank,out);out[uint(m.attrs[0])]=ulong(read_index(indices,linear,m.indexType));source=coords_linear(out,m.inDims,m.inputRank); } else { ulong out[16],src[16];decode_coords(linear,m.outDims,m.outputRank,out);uint batch=uint(m.attrs[0]),q=m.auxRank,k=uint(m.auxDims[q-1u]);for(uint a=0u;a<batch;++a)src[a]=out[a];ulong prefix=0ul;for(uint a=0u;a<q-1u;++a)prefix=prefix*m.auxDims[a]+out[a];for(uint j=0u;j<k;++j)src[batch+j]=ulong(read_index(indices,prefix*ulong(k)+j,m.indexType));for(uint a=batch+k;a<m.inputRank;++a)src[a]=out[q-1u+a-(batch+k)];source=coords_linear(src,m.inDims,m.inputRank); } copy_word(data,source,output,linear,m.width); }\n"
"kernel void exact_compose_0059(device const uchar *i0 [[buffer(0)]],device const uchar *i1 [[buffer(1)]],device const uchar *i2 [[buffer(2)]],device const uchar *i3 [[buffer(3)]],device const uchar *i4 [[buffer(4)]],device const uchar *i5 [[buffer(5)]],device const uchar *i6 [[buffer(6)]],device const uchar *i7 [[buffer(7)]],device const uchar *i8 [[buffer(8)]],device const uchar *i9 [[buffer(9)]],device const uchar *i10 [[buffer(10)]],device const uchar *i11 [[buffer(11)]],device const uchar *i12 [[buffer(12)]],device const uchar *i13 [[buffer(13)]],device const uchar *i14 [[buffer(14)]],device const uchar *i15 [[buffer(15)]],device uchar *output [[buffer(16)]],constant DataMeta &m [[buffer(17)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],srcCoords[16];decode_coords(linear,m.outDims,m.outputRank,out);uint axis=uint(m.attrs[0]),which=0u;ulong source; if(m.operation==77u){ulong coordinate=out[axis];while(which+1u<m.inputCount&&coordinate>=m.inputPrefixes[which+1u])++which;for(uint a=0u;a<m.outputRank;++a)srcCoords[a]=out[a];srcCoords[axis]=coordinate-m.inputPrefixes[which];source=0ul;for(uint a=0u;a<m.outputRank;++a)source=source*(a==axis?m.inputExtents[which]:m.outDims[a])+srcCoords[a];}else{which=uint(out[axis]);for(uint a=0u,s=0u;a<m.outputRank;++a)if(a!=axis)srcCoords[s++]=out[a];source=coords_linear(srcCoords,m.inDims,m.inputRank);}device const uchar *input=i0;switch(which){case 1u:input=i1;break;case 2u:input=i2;break;case 3u:input=i3;break;case 4u:input=i4;break;case 5u:input=i5;break;case 6u:input=i6;break;case 7u:input=i7;break;case 8u:input=i8;break;case 9u:input=i9;break;case 10u:input=i10;break;case 11u:input=i11;break;case 12u:input=i12;break;case 13u:input=i13;break;case 14u:input=i14;break;case 15u:input=i15;break;default:break;}copy_word(input,source,output,linear,m.width);}\n";

#endif
