#ifndef SYNAPTIK_TASK0066_DTYPE_LAYOUT_KERNELS_H
#define SYNAPTIK_TASK0066_DTYPE_LAYOUT_KERNELS_H

static NSString *const SynaptikTask0066DtypeLayoutKernelSource =
@"\n"
"inline uint t66_width(uint type){return type==3u?1u:type==5u?2u:(type==1u||type==2u)?4u:8u;}\n"
"inline bool t66_float_type(uint type){return type==1u||type==4u||type==5u;}\n"
"inline uint t66_frac_bits(uint type){return type==4u?52u:type==1u?23u:7u;}\n"
"inline uint t66_exp_bits(uint type){return type==4u?11u:type==1u?8u:8u;}\n"
"inline int t66_bias(uint type){return type==4u?1023:type==1u?127:127;}\n"
"inline ulong t66_frac_mask(uint bits){return bits==64u?~0ul:((1ul<<bits)-1ul);}\n"
"inline int t66_high_bit(ulong value){int p=-1;while(value!=0ul){value>>=1u;++p;}return p;}\n"
"inline ulong t66_round_shift(ulong value,uint shift){if(shift==0u)return value;if(shift>64u)return 0ul;if(shift==64u){ulong midpoint=1ul<<63u;return value>midpoint||(value==midpoint&&0ul!=0ul)?1ul:0ul;}ulong q=value>>shift;ulong rem=value&((1ul<<shift)-1ul);ulong midpoint=1ul<<(shift-1u);return q+ulong(rem>midpoint||(rem==midpoint&&(q&1ul)!=0ul));}\n"
"inline ulong t66_pack_finite(bool sign,ulong mant,int exp2,uint target){uint tf=t66_frac_bits(target),te=t66_exp_bits(target);int bias=t66_bias(target),emin=1-bias,emax=bias;ulong signWord=sign?(1ul<<(tf+te)):0ul;if(mant==0ul)return signWord;int p=t66_high_bit(mant);int e=exp2+p;if(e>emax)return signWord|(((1ul<<te)-1ul)<<tf);ulong q=0ul;if(e>=emin){if(p>int(tf))q=t66_round_shift(mant,uint(p-int(tf)));else q=mant<<uint(int(tf)-p);if(q==(1ul<<(tf+1u))){q>>=1u;++e;if(e>emax)return signWord|(((1ul<<te)-1ul)<<tf);}return signWord|(ulong(e+bias)<<tf)|(q&((1ul<<tf)-1ul));}int quantum=emin-int(tf);int shift=quantum-exp2;if(shift>0)q=t66_round_shift(mant,uint(shift));else q=mant<<uint(-shift);if(q==0ul)return signWord;if(q>=(1ul<<tf))return signWord|(1ul<<tf);return signWord|q;}\n"
"inline ulong t66_float_cast(ulong word,uint source,uint target){uint sf=t66_frac_bits(source),se=t66_exp_bits(source),tf=t66_frac_bits(target),te=t66_exp_bits(target);ulong sfrac=word&((1ul<<sf)-1ul);ulong sexp=(word>>sf)&((1ul<<se)-1ul);bool sign=((word>>(sf+se))&1ul)!=0ul;ulong signWord=sign?(1ul<<(tf+te)):0ul;if(sexp==((1ul<<se)-1ul)){if(sfrac==0ul)return signWord|(((1ul<<te)-1ul)<<tf);if(tf>=sf)return signWord|(((1ul<<te)-1ul)<<tf)|(sfrac<<(tf-sf));return (((1ul<<te)-1ul)<<tf)|(1ul<<(tf-1u));}if(sexp==0ul&&sfrac==0ul)return signWord;ulong mant;int exp2;if(sexp==0ul){mant=sfrac;exp2=1-t66_bias(source)-int(sf);}else{mant=(1ul<<sf)|sfrac;exp2=int(sexp)-t66_bias(source)-int(sf);}return t66_pack_finite(sign,mant,exp2,target);}\n"
"inline ulong t66_int_to_float(ulong word,uint source,uint target){bool sign=false;ulong mag=word;if(source==2u){uint value=uint(word);sign=(value&0x80000000u)!=0u;mag=sign?ulong(~value+1u):ulong(value);}else{sign=(word&0x8000000000000000ul)!=0ul;mag=sign?(~word+1ul):word;}return t66_pack_finite(sign,mag,0,target);}\n"
"inline ulong t66_float_to_int(ulong word,uint source,uint target){uint sf=t66_frac_bits(source),se=t66_exp_bits(source);ulong frac=word&((1ul<<sf)-1ul);ulong exp=(word>>sf)&((1ul<<se)-1ul);bool sign=((word>>(sf+se))&1ul)!=0ul;uint bits=target==2u?32u:64u;ulong positive=bits==32u?0x7ffffffful:0x7ffffffffffffffful;ulong negative=bits==32u?0x80000000ul:0x8000000000000000ul;if(exp==((1ul<<se)-1ul)){if(frac!=0ul)return 0ul;return sign?negative:positive;}if(exp==0ul&&frac==0ul)return 0ul;ulong mant=exp==0ul?frac:((1ul<<sf)|frac);int exp2=exp==0ul?1-t66_bias(source)-int(sf):int(exp)-t66_bias(source)-int(sf);ulong limit=sign?negative:positive;ulong mag;if(exp2>=0){if(exp2>=64||mant>(limit>>uint(exp2)))mag=limit;else mag=mant<<uint(exp2);}else{uint shift=uint(-exp2);mag=shift>=64u?0ul:(mant>>shift);}if(mag>limit)mag=limit;if(!sign)return mag;if(mag>=negative)return negative;ulong result=~mag+1ul;return bits==32u?ulong(uint(result)):result;}\n"
"inline ulong t66_convert(ulong word,uint source,uint target){if(source==target)return word;if(source==3u)return bool_target_word((word&0xfful)!=0ul,target);if(target==3u)return source_nonzero(word,source)?1ul:0ul;if(t66_float_type(source)&&t66_float_type(target))return t66_float_cast(word,source,target);if((source==2u||source==6u)&&t66_float_type(target))return t66_int_to_float(word,source,target);if(t66_float_type(source)&&(target==2u||target==6u))return t66_float_to_int(word,source,target);if(source==2u&&target==6u)return ulong(long(int(uint(word))));if(source==6u&&target==2u)return ulong(uint(word));return 0ul;}\n"
"kernel void exact_cast_0066(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=logical_storage(linear,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);ulong word=load_word(input,source,t66_width(m.sourceType));store_word(output,linear,t66_width(m.targetType),t66_convert(word,m.sourceType,m.targetType));}\n"
"inline ulong t66_input_linear(thread const ulong *coords,constant DataMeta &m){return coords_storage(coords,m.inputStrides,m.inputRank,m.inputOffset);}\n"
"kernel void exact_move_unary_0066(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],src[16];decode_coords(linear,m.outDims,m.outputRank,out);ulong source=0ul;bool copied=true;ulong fill=0ul;if(m.operation==6u||m.operation==11u){source=logical_storage(linear,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);}else if(m.operation==7u){uint pad=m.outputRank-m.inputRank;for(uint a=0u;a<m.inputRank;++a)src[a]=m.inDims[a]==1ul?0ul:out[a+pad];source=t66_input_linear(src,m);}else if(m.operation==8u){for(uint a=0u;a<m.attributeCount;++a)src[uint(m.attrs[a])]=out[a];source=t66_input_linear(src,m);}else if(m.operation==9u){uint axis=uint(m.attrs[0]);for(uint s=0u,t=0u;s<m.inputRank;++s){if(t==axis)++t;src[s]=out[t++];}source=t66_input_linear(src,m);}else if(m.operation==10u){uint axis=uint(m.attrs[0]);for(uint s=0u,t=0u;s<m.inputRank;++s)src[s]=s==axis?0ul:out[t++];source=t66_input_linear(src,m);}else if(m.operation==19u){uint axis=uint(m.attrs[2]);for(uint a=0u;a<m.inputRank;++a)src[a]=out[a];src[axis]=out[axis]*m.attrs[1]+out[m.outputRank-1u];source=t66_input_linear(src,m);}else if(m.operation==73u){uint axis=uint(m.attrs[0]);for(uint s=0u,t=0u;s<m.inputRank;++s)src[s]=s==axis?m.attrs[1]:out[t++];source=t66_input_linear(src,m);}else if(m.operation==74u){ulong ordinal=0ul;copied=pad_source(linear,m,ordinal);if(copied)source=logical_storage(ordinal,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);fill=m.attrs[2u+uint(m.attrs[0])*2u];}else if(m.operation==75u){source=slice_source(linear,m);}else if(m.operation==79u){for(uint a=0u;a<m.inputRank;++a)src[a]=out[a]%m.inDims[a];source=t66_input_linear(src,m);}else if(m.operation==81u){ulong ordinal=0ul;copied=unfold2_source(linear,m,ordinal);if(copied)source=logical_storage(ordinal,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);fill=m.attributeKind==20u?m.attrs[10]:0ul;}else if(m.operation==83u){ulong ordinal=0ul;copied=unfold3_source(linear,m,ordinal);if(copied)source=logical_storage(ordinal,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);fill=m.attributeKind==23u?m.attrs[14]:0ul;}ulong destination=logical_storage(linear,m.outDims,m.outputStrides,m.outputRank,m.outputOffset);if(copied)copy_word(input,source,output,destination,m.width);else store_word(output,destination,m.width,fill);}\n"
"kernel void exact_gather_0066(device const uchar *data [[buffer(0)]],device const uchar *indices [[buffer(1)]],device uchar *output [[buffer(2)]],constant DataMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],src[16],idx[16];decode_coords(linear,m.outDims,m.outputRank,out);uint axis=uint(m.attrs[0]);for(uint a=0u;a<axis;++a)src[a]=out[a];for(uint a=0u;a<m.auxRank;++a)idx[a]=out[axis+a];long selected=read_index(indices,coords_storage(idx,m.auxiliaryStrides,m.auxRank,m.auxiliaryOffset),m.indexType);src[axis]=ulong(selected);for(uint a=axis+1u;a<m.inputRank;++a)src[a]=out[a-1u+m.auxRank];copy_word(data,t66_input_linear(src,m),output,linear,m.width);}\n"
"kernel void exact_one_hot_0066(device const uchar *indices [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],idx[16];decode_coords(linear,m.outDims,m.outputRank,out);for(uint a=0u;a<m.inputRank;++a)idx[a]=out[a];long value=read_index(indices,coords_storage(idx,m.inputStrides,m.inputRank,m.inputOffset),m.sourceType);output[linear]=uchar(value==long(out[m.outputRank-1u]));}\n"
"kernel void exact_gather_index_0066(device const uchar *data [[buffer(0)]],device const uchar *indices [[buffer(1)]],device uchar *output [[buffer(2)]],constant DataMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],src[16],idx[16];decode_coords(linear,m.outDims,m.outputRank,out);if(m.operation==69u){for(uint a=0u;a<m.outputRank;++a){src[a]=out[a];idx[a]=out[a];}src[uint(m.attrs[0])]=ulong(read_index(indices,coords_storage(idx,m.auxiliaryStrides,m.auxRank,m.auxiliaryOffset),m.indexType));}else{uint batch=uint(m.attrs[0]),q=m.auxRank,k=uint(m.auxDims[q-1u]);for(uint a=0u;a<batch;++a)src[a]=out[a];for(uint a=0u;a<q-1u;++a)idx[a]=out[a];for(uint j=0u;j<k;++j){idx[q-1u]=j;src[batch+j]=ulong(read_index(indices,coords_storage(idx,m.auxiliaryStrides,q,m.auxiliaryOffset),m.indexType));}for(uint a=batch+k;a<m.inputRank;++a)src[a]=out[q-1u+a-(batch+k)];}copy_word(data,t66_input_linear(src,m),output,linear,m.width);}\n"
"inline bool t66_class(ulong word,uint type,uint op){uint f=t66_frac_bits(type),e=t66_exp_bits(type);ulong exp=(word>>f)&((1ul<<e)-1ul),frac=word&((1ul<<f)-1ul);bool special=exp==((1ul<<e)-1ul);return op==40u?!special:op==41u?(special&&frac!=0ul):(special&&frac==0ul);}\n"
"kernel void exact_predicate_0066(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=logical_storage(linear,m.inDims,m.inputStrides,m.inputRank,m.inputOffset);ulong word=load_word(input,source,t66_width(m.sourceType));output[linear]=uchar(m.operation==45u?!bool(word&0xfful):t66_class(word,m.sourceType,m.operation));}\n"
"kernel void exact_logical_binary_0066(device const uchar *left [[buffer(0)]],device const uchar *right [[buffer(1)]],device uchar *output [[buffer(2)]],constant DataMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],lc[16],rc[16];decode_coords(linear,m.outDims,m.outputRank,out);uint lp=m.outputRank-m.inputRank,rp=m.outputRank-m.auxRank;for(uint a=0u;a<m.inputRank;++a)lc[a]=m.inDims[a]==1ul?0ul:out[a+lp];for(uint a=0u;a<m.auxRank;++a)rc[a]=m.auxDims[a]==1ul?0ul:out[a+rp];bool l=left[coords_storage(lc,m.inputStrides,m.inputRank,m.inputOffset)]!=0,r=right[coords_storage(rc,m.auxiliaryStrides,m.auxRank,m.auxiliaryOffset)]!=0;output[linear]=uchar(m.operation==43u?(l&&r):(l||r));}\n"
"kernel void exact_where_0066(device const uchar *condition [[buffer(0)]],device const uchar *whenTrue [[buffer(1)]],device const uchar *whenFalse [[buffer(2)]],device uchar *output [[buffer(3)]],constant DataMeta &m [[buffer(4)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],cc[16],tc[16],fc[16];decode_coords(linear,m.outDims,m.outputRank,out);uint cp=m.outputRank-m.inputRank,tp=m.outputRank-m.auxRank,fr=uint(m.inputExtents[0]),fp=m.outputRank-fr;for(uint a=0u;a<m.inputRank;++a)cc[a]=m.inDims[a]==1ul?0ul:out[a+cp];for(uint a=0u;a<m.auxRank;++a)tc[a]=m.auxDims[a]==1ul?0ul:out[a+tp];for(uint a=0u;a<fr;++a)fc[a]=m.inputExtents[1u+a]==1ul?0ul:out[a+fp];bool take=condition[coords_storage(cc,m.inputStrides,m.inputRank,m.inputOffset)]!=0;uint sourceType=take?m.sourceType:m.reserved;device const uchar *source=take?whenTrue:whenFalse;ulong offset=take?coords_storage(tc,m.auxiliaryStrides,m.auxRank,m.auxiliaryOffset):coords_storage(fc,m.outputStrides,fr,m.outputOffset);ulong word=load_word(source,offset,t66_width(sourceType));store_word(output,linear,t66_width(m.targetType),t66_convert(word,sourceType,m.targetType));}\n"
"inline ulong t66_role_logical(ulong ordinal,uint role,constant DataMeta &m){return logical_storage(ordinal,m.roleDims[role],m.roleStrides[role],m.roleRanks[role],m.roleOffsets[role]);}\n"
"kernel void exact_scatter_copy_0066(device const uchar *data [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear<m.elementCount)copy_word(data,t66_role_logical(linear,0u,m),output,linear,m.width);}\n"
"kernel void exact_scatter_elements_0066(device const uchar *data [[buffer(0)]],device const uchar *indices [[buffer(1)]],device const uchar *updates [[buffer(2)]],device uchar *output [[buffer(3)]],constant DataMeta &m [[buffer(4)]],uint3 gid [[thread_position_in_grid]]){(void)data;ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong coords[16];decode_coords(linear,m.roleDims[1],m.roleRanks[1],coords);long selected=read_index(indices,coords_storage(coords,m.roleStrides[1],m.roleRanks[1],m.roleOffsets[1]),m.indexType);coords[uint(m.attrs[0])]=ulong(selected);ulong destination=coords_linear(coords,m.outDims,m.outputRank);copy_word(updates,t66_role_logical(linear,2u,m),output,destination,m.width);}\n"
"kernel void exact_scatter_nd_0066(device const uchar *data [[buffer(0)]],device const uchar *indices [[buffer(1)]],device const uchar *updates [[buffer(2)]],device uchar *output [[buffer(3)]],constant DataMeta &m [[buffer(4)]],uint3 gid [[thread_position_in_grid]]){(void)data;ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong update[16],target[16],idx[16];decode_coords(linear,m.roleDims[2],m.roleRanks[2],update);uint batch=uint(m.attrs[0]),q=m.roleRanks[1],k=uint(m.roleDims[1][q-1u]);for(uint a=0u;a<batch;++a)target[a]=update[a];for(uint a=0u;a<q-1u;++a)idx[a]=update[a];for(uint j=0u;j<k;++j){idx[q-1u]=j;target[batch+j]=ulong(read_index(indices,coords_storage(idx,m.roleStrides[1],q,m.roleOffsets[1]),m.indexType));}for(uint a=batch+k;a<m.inputRank;++a)target[a]=update[q-1u+a-(batch+k)];ulong destination=coords_linear(target,m.outDims,m.outputRank);copy_word(updates,t66_role_logical(linear,2u,m),output,destination,m.width);}\n"
"kernel void exact_slice_update_0066(device const uchar *data [[buffer(0)]],device const uchar *updates [[buffer(1)]],device uchar *output [[buffer(2)]],constant DataMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=0ul;if(slice_update_source_0060(linear,m,source))copy_word(updates,source,output,linear,m.width);else copy_word(data,t66_role_logical(linear,0u,m),output,linear,m.width);}\n"
"kernel void exact_fold_0066(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=0ul;bool copied=m.operation==80u?fold_axis_source_0060(linear,m,source):fold_window_source_0060(linear,m,m.operation==82u?2u:3u,source);if(copied)copy_word(input,t66_role_logical(source,0u,m),output,linear,m.width);else store_word(output,linear,m.width,0ul);}\n"
"kernel void exact_compose_0066(device const uchar *i0 [[buffer(0)]],device const uchar *i1 [[buffer(1)]],device const uchar *i2 [[buffer(2)]],device const uchar *i3 [[buffer(3)]],device const uchar *i4 [[buffer(4)]],device const uchar *i5 [[buffer(5)]],device const uchar *i6 [[buffer(6)]],device const uchar *i7 [[buffer(7)]],device const uchar *i8 [[buffer(8)]],device const uchar *i9 [[buffer(9)]],device const uchar *i10 [[buffer(10)]],device const uchar *i11 [[buffer(11)]],device const uchar *i12 [[buffer(12)]],device const uchar *i13 [[buffer(13)]],device const uchar *i14 [[buffer(14)]],device const uchar *i15 [[buffer(15)]],device uchar *output [[buffer(16)]],constant DataMeta &m [[buffer(17)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong out[16],src[16];decode_coords(linear,m.outDims,m.outputRank,out);uint axis=uint(m.attrs[0]),which=0u;if(m.operation==77u){ulong coordinate=out[axis];while(which+1u<m.inputCount&&coordinate>=m.inputPrefixes[which+1u])++which;for(uint a=0u;a<m.outputRank;++a)src[a]=out[a];src[axis]=coordinate-m.inputPrefixes[which];}else{which=uint(out[axis]);for(uint a=0u,s=0u;a<m.outputRank;++a)if(a!=axis)src[s++]=out[a];}device const uchar *selected=i0;switch(which){case 1u:selected=i1;break;case 2u:selected=i2;break;case 3u:selected=i3;break;case 4u:selected=i4;break;case 5u:selected=i5;break;case 6u:selected=i6;break;case 7u:selected=i7;break;case 8u:selected=i8;break;case 9u:selected=i9;break;case 10u:selected=i10;break;case 11u:selected=i11;break;case 12u:selected=i12;break;case 13u:selected=i13;break;case 14u:selected=i14;break;case 15u:selected=i15;break;default:break;}ulong source=coords_storage(src,m.roleStrides[which],m.roleRanks[which],m.roleOffsets[which]);copy_word(selected,source,output,linear,m.width);}\n";

#endif
