#ifndef SYNAPTIK_TASK0064_CONVOLUTION_POOLING_KERNELS_H
#define SYNAPTIK_TASK0064_CONVOLUTION_POOLING_KERNELS_H

static NSString *const SynaptikTask0064ConvolutionPoolingKernelSource =
@"\n"
"inline uint width_0064(uint type) { return type == 4u ? 8u : (type == 5u ? 2u : 4u); }\n"
"inline float load_f32_0064(device const uchar *p, ulong offset, uint type) { uint raw = uint(load_word(p, offset, width_0064(type))); return as_type<float>(type == 5u ? raw << 16u : raw); }\n"
"inline ulong input_offset_0064(constant DataMeta &m, thread const ulong *coords) { ulong offset = m.inputOffset; for (uint axis = 0u; axis < m.inputRank; ++axis) offset += coords[axis] * m.inputStrides[axis]; return offset; }\n"
"inline ulong auxiliary_offset_0064(constant DataMeta &m, thread const ulong *coords) { ulong offset = m.auxiliaryOffset; for (uint axis = 0u; axis < m.auxRank; ++axis) offset += coords[axis] * m.auxiliaryStrides[axis]; return offset; }\n"
"inline bool pool_nan_0064(ulong raw, uint type) { if (type == 4u) return (raw & 0x7ff0000000000000ul) == 0x7ff0000000000000ul && (raw & 0x000ffffffffffffful) != 0ul; uint word = uint(raw); if (type == 5u) return (word & 0x7f80u) == 0x7f80u && (word & 0x007fu) != 0u; return (word & 0x7f800000u) == 0x7f800000u && (word & 0x007fffffu) != 0u; }\n"
"inline bool pool_greater_0064(ulong candidate, ulong best, uint type) { bool candidateNan = pool_nan_0064(candidate, type); bool bestNan = pool_nan_0064(best, type); if (bestNan) return false; if (candidateNan) return true; if (type == 4u) { ulong ck = (candidate & 0x8000000000000000ul) != 0ul ? ~candidate : candidate ^ 0x8000000000000000ul; ulong bk = (best & 0x8000000000000000ul) != 0ul ? ~best : best ^ 0x8000000000000000ul; return ck > bk; } uint c = uint(candidate); uint b = uint(best); uint sign = type == 5u ? 0x8000u : 0x80000000u; uint mask = type == 5u ? 0xffffu : 0xffffffffu; uint ck = (c & sign) != 0u ? (~c & mask) : (c ^ sign); uint bk = (b & sign) != 0u ? (~b & mask) : (b ^ sign); return ck > bk; }\n"
"inline ulong pool_negative_infinity_0064(uint type) { return type == 4u ? 0xfff0000000000000ul : (type == 5u ? 0xff80ul : 0xff800000ul); }\n"
"kernel void conv2d_0064(device const uchar *input [[buffer(0)]], device const uchar *weight [[buffer(1)]], device const uchar *bias [[buffer(2)]], device uchar *output [[buffer(3)]], constant DataMeta &m [[buffer(4)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); ulong groups = m.attrs[6]; ulong outputsPerGroup = m.outDims[1] / groups; ulong group = out[1] / outputsPerGroup; float accumulator = m.inputCount == 3u ? load_f32_0064(bias, out[1], m.reserved) : 0.0f; for (ulong ic = 0ul; ic < m.auxDims[1]; ++ic) for (ulong kh = 0ul; kh < m.auxDims[2]; ++kh) for (ulong kw = 0ul; kw < m.auxDims[3]; ++kw) { long ih = long(out[2] * m.attrs[0] + kh * m.attrs[4]) - long(m.attrs[2]); long iw = long(out[3] * m.attrs[1] + kw * m.attrs[5]) - long(m.attrs[3]); ulong wc[16] = {out[1], ic, kh, kw}; float w = load_f32_0064(weight, auxiliary_offset_0064(m, wc), m.indexType); float x = 0.0f; if (ih >= 0l && iw >= 0l && ulong(ih) < m.inDims[2] && ulong(iw) < m.inDims[3]) { ulong xc[16] = {out[0], group * m.auxDims[1] + ic, ulong(ih), ulong(iw)}; x = load_f32_0064(input, input_offset_0064(m, xc), m.sourceType); } accumulator = fma(x, w, accumulator); } store_word(output, linear, 4u, ulong(as_type<uint>(accumulator))); }\n"
"kernel void conv3d_0064(device const uchar *input [[buffer(0)]], device const uchar *weight [[buffer(1)]], device const uchar *bias [[buffer(2)]], device uchar *output [[buffer(3)]], constant DataMeta &m [[buffer(4)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); ulong groups = m.attrs[9]; ulong outputsPerGroup = m.outDims[1] / groups; ulong group = out[1] / outputsPerGroup; float accumulator = m.inputCount == 3u ? load_f32_0064(bias, out[1], m.reserved) : 0.0f; for (ulong ic = 0ul; ic < m.auxDims[1]; ++ic) for (ulong kd = 0ul; kd < m.auxDims[2]; ++kd) for (ulong kh = 0ul; kh < m.auxDims[3]; ++kh) for (ulong kw = 0ul; kw < m.auxDims[4]; ++kw) { long id = long(out[2] * m.attrs[0] + kd * m.attrs[6]) - long(m.attrs[3]); long ih = long(out[3] * m.attrs[1] + kh * m.attrs[7]) - long(m.attrs[4]); long iw = long(out[4] * m.attrs[2] + kw * m.attrs[8]) - long(m.attrs[5]); ulong wc[16] = {out[1], ic, kd, kh, kw}; float w = load_f32_0064(weight, auxiliary_offset_0064(m, wc), m.indexType); float x = 0.0f; if (id >= 0l && ih >= 0l && iw >= 0l && ulong(id) < m.inDims[2] && ulong(ih) < m.inDims[3] && ulong(iw) < m.inDims[4]) { ulong xc[16] = {out[0], group * m.auxDims[1] + ic, ulong(id), ulong(ih), ulong(iw)}; x = load_f32_0064(input, input_offset_0064(m, xc), m.sourceType); } accumulator = fma(x, w, accumulator); } store_word(output, linear, 4u, ulong(as_type<uint>(accumulator))); }\n"
"kernel void max_pool2d_0064(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); ulong best = pool_negative_infinity_0064(m.sourceType); bool found = false; for (ulong kh = 0ul; kh < m.attrs[0]; ++kh) for (ulong kw = 0ul; kw < m.attrs[1]; ++kw) { long ih = long(out[2] * m.attrs[2] + kh * m.attrs[6]) - long(m.attrs[4]); long iw = long(out[3] * m.attrs[3] + kw * m.attrs[7]) - long(m.attrs[5]); if (ih < 0l || iw < 0l || ulong(ih) >= m.inDims[2] || ulong(iw) >= m.inDims[3]) continue; ulong coords[16] = {out[0], out[1], ulong(ih), ulong(iw)}; ulong candidate = load_word(input, input_offset_0064(m, coords), width_0064(m.sourceType)); if (!found || pool_greater_0064(candidate, best, m.sourceType)) { best = candidate; found = true; } } store_word(output, linear, width_0064(m.sourceType), best); }\n"
"kernel void max_pool3d_0064(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); ulong best = pool_negative_infinity_0064(m.sourceType); bool found = false; for (ulong kd = 0ul; kd < m.attrs[0]; ++kd) for (ulong kh = 0ul; kh < m.attrs[1]; ++kh) for (ulong kw = 0ul; kw < m.attrs[2]; ++kw) { long id = long(out[2] * m.attrs[3] + kd * m.attrs[9]) - long(m.attrs[6]); long ih = long(out[3] * m.attrs[4] + kh * m.attrs[10]) - long(m.attrs[7]); long iw = long(out[4] * m.attrs[5] + kw * m.attrs[11]) - long(m.attrs[8]); if (id < 0l || ih < 0l || iw < 0l || ulong(id) >= m.inDims[2] || ulong(ih) >= m.inDims[3] || ulong(iw) >= m.inDims[4]) continue; ulong coords[16] = {out[0], out[1], ulong(id), ulong(ih), ulong(iw)}; ulong candidate = load_word(input, input_offset_0064(m, coords), width_0064(m.sourceType)); if (!found || pool_greater_0064(candidate, best, m.sourceType)) { best = candidate; found = true; } } store_word(output, linear, width_0064(m.sourceType), best); }\n"
"kernel void average_pool2d_0064(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); float sum = 0.0f; bool allNegativeZero = true; for (ulong kh = 0ul; kh < m.attrs[0]; ++kh) for (ulong kw = 0ul; kw < m.attrs[1]; ++kw) { long ih = long(out[2] * m.attrs[2] + kh * m.attrs[6]) - long(m.attrs[4]); long iw = long(out[3] * m.attrs[3] + kw * m.attrs[7]) - long(m.attrs[5]); float value = 0.0f; if (ih < 0l || iw < 0l || ulong(ih) >= m.inDims[2] || ulong(iw) >= m.inDims[3]) { allNegativeZero = false; } else { ulong coords[16] = {out[0], out[1], ulong(ih), ulong(iw)}; uint raw = uint(load_word(input, input_offset_0064(m, coords), 4u)); allNegativeZero = allNegativeZero && raw == 0x80000000u; value = as_type<float>(raw); } sum += value; } float result = sum / float(m.attrs[0] * m.attrs[1]); if (result == 0.0f) result = allNegativeZero ? as_type<float>(0x80000000u) : 0.0f; store_word(output, linear, 4u, ulong(as_type<uint>(result))); }\n"
"kernel void average_pool3d_0064(device const uchar *input [[buffer(0)]], device uchar *output [[buffer(1)]], constant DataMeta &m [[buffer(2)]], uint gid [[thread_position_in_grid]]) { ulong linear = ulong(gid); if (linear >= m.elementCount) return; ulong out[16]; decode_coords(linear, m.outDims, m.outputRank, out); float sum = 0.0f; bool allNegativeZero = true; for (ulong kd = 0ul; kd < m.attrs[0]; ++kd) for (ulong kh = 0ul; kh < m.attrs[1]; ++kh) for (ulong kw = 0ul; kw < m.attrs[2]; ++kw) { long id = long(out[2] * m.attrs[3] + kd * m.attrs[9]) - long(m.attrs[6]); long ih = long(out[3] * m.attrs[4] + kh * m.attrs[10]) - long(m.attrs[7]); long iw = long(out[4] * m.attrs[5] + kw * m.attrs[11]) - long(m.attrs[8]); float value = 0.0f; if (id < 0l || ih < 0l || iw < 0l || ulong(id) >= m.inDims[2] || ulong(ih) >= m.inDims[3] || ulong(iw) >= m.inDims[4]) { allNegativeZero = false; } else { ulong coords[16] = {out[0], out[1], ulong(id), ulong(ih), ulong(iw)}; uint raw = uint(load_word(input, input_offset_0064(m, coords), 4u)); allNegativeZero = allNegativeZero && raw == 0x80000000u; value = as_type<float>(raw); } sum += value; } float result = sum / float(m.attrs[0] * m.attrs[1] * m.attrs[2]); if (result == 0.0f) result = allNegativeZero ? as_type<float>(0x80000000u) : 0.0f; store_word(output, linear, 4u, ulong(as_type<uint>(result))); }\n"
;

#endif
