#ifndef SYNAPTIK_TASK0061_MATMUL_KERNELS_H
#define SYNAPTIK_TASK0061_MATMUL_KERNELS_H

static NSString *const SynaptikTask0061MatmulKernelSource =
@"\n"
"inline void matmul_offsets_0061(ulong linear, ulong contraction, constant DataMeta &m, thread ulong &leftOffset, thread ulong &rightOffset) { ulong out[16]; ulong left[16]; ulong right[16]; decode_coords(linear, m.outDims, m.outputRank, out); uint leftBatch = m.inputRank > 1u ? m.inputRank - 2u : 0u; uint rightBatch = m.auxRank > 1u ? m.auxRank - 2u : 0u; uint batchRank = max(leftBatch, rightBatch); uint leftPad = batchRank - leftBatch; uint rightPad = batchRank - rightBatch; for (uint axis = 0u; axis < leftBatch; ++axis) left[axis] = m.inDims[axis] == 1ul ? 0ul : out[leftPad + axis]; for (uint axis = 0u; axis < rightBatch; ++axis) right[axis] = m.auxDims[axis] == 1ul ? 0ul : out[rightPad + axis]; if (m.inputRank == 1u) left[0] = contraction; else { left[m.inputRank - 2u] = out[batchRank]; left[m.inputRank - 1u] = contraction; } if (m.auxRank == 1u) right[0] = contraction; else { right[m.auxRank - 2u] = contraction; right[m.auxRank - 1u] = out[batchRank + (m.inputRank > 1u ? 1u : 0u)]; } leftOffset = coords_storage(left, m.inputStrides, m.inputRank, m.inputOffset); rightOffset = coords_storage(right, m.auxiliaryStrides, m.auxRank, m.auxiliaryOffset); }\n"
"inline float matmul_fma_0061(float left, float right, float accumulator) { return fma(left, right, accumulator); }\n"
"inline float matmul_f32_0061(device const uchar *left, device const uchar *right, ulong linear, constant DataMeta &m, bool leftBfloat, bool rightBfloat) { float accumulator = 0.0f; ulong contractions = m.inputExtents[0]; for (ulong contraction = 0ul; contraction < contractions; ++contraction) { ulong leftOffset, rightOffset; matmul_offsets_0061(linear, contraction, m, leftOffset, rightOffset); uint leftWord = uint(load_word(left, leftOffset, leftBfloat ? 2u : 4u)); uint rightWord = uint(load_word(right, rightOffset, rightBfloat ? 2u : 4u)); float leftValue = as_type<float>(leftBfloat ? leftWord << 16u : leftWord); float rightValue = as_type<float>(rightBfloat ? rightWord << 16u : rightWord); accumulator = matmul_fma_0061(leftValue, rightValue, accumulator); } return accumulator; }\n"
"kernel void matmul_i32_i32_i32_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; uint accumulator = 0u; for (ulong contraction = 0ul; contraction < m.inputExtents[0]; ++contraction) { ulong leftOffset, rightOffset; matmul_offsets_0061(linear, contraction, m, leftOffset, rightOffset); accumulator += uint(load_word(left, leftOffset, 4u)) * uint(load_word(right, rightOffset, 4u)); } store_word(output, linear, 4u, ulong(accumulator)); }\n"
"kernel void matmul_i32_i64_i64_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; ulong accumulator = 0ul; for (ulong contraction = 0ul; contraction < m.inputExtents[0]; ++contraction) { ulong leftOffset, rightOffset; matmul_offsets_0061(linear, contraction, m, leftOffset, rightOffset); ulong leftValue = ulong(long(int(uint(load_word(left, leftOffset, 4u))))); accumulator += leftValue * load_word(right, rightOffset, 8u); } store_word(output, linear, 8u, accumulator); }\n"
"kernel void matmul_i64_i32_i64_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; ulong accumulator = 0ul; for (ulong contraction = 0ul; contraction < m.inputExtents[0]; ++contraction) { ulong leftOffset, rightOffset; matmul_offsets_0061(linear, contraction, m, leftOffset, rightOffset); ulong rightValue = ulong(long(int(uint(load_word(right, rightOffset, 4u))))); accumulator += load_word(left, leftOffset, 8u) * rightValue; } store_word(output, linear, 8u, accumulator); }\n"
"kernel void matmul_i64_i64_i64_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; ulong accumulator = 0ul; for (ulong contraction = 0ul; contraction < m.inputExtents[0]; ++contraction) { ulong leftOffset, rightOffset; matmul_offsets_0061(linear, contraction, m, leftOffset, rightOffset); accumulator += load_word(left, leftOffset, 8u) * load_word(right, rightOffset, 8u); } store_word(output, linear, 8u, accumulator); }\n"
"kernel void matmul_f32_f32_f32_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; store_word(output, linear, 4u, ulong(as_type<uint>(matmul_f32_0061(left, right, linear, m, false, false)))); }\n"
"kernel void matmul_bf16_f32_f32_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; store_word(output, linear, 4u, ulong(as_type<uint>(matmul_f32_0061(left, right, linear, m, true, false)))); }\n"
"kernel void matmul_f32_bf16_f32_0061(device const uchar *left [[buffer(0)]], device const uchar *right [[buffer(1)]], device uchar *output [[buffer(2)]], constant DataMeta &m [[buffer(3)]], uint3 gid [[thread_position_in_grid]]) { ulong linear = data_linear_id(gid, m); if (linear >= m.elementCount) return; store_word(output, linear, 4u, ulong(as_type<uint>(matmul_f32_0061(left, right, linear, m, false, true)))); }\n";

#endif
