#ifndef SYNAPTIK_TASK0060_REDUCTION_KERNELS_H
#define SYNAPTIK_TASK0060_REDUCTION_KERNELS_H

static NSString *const SynaptikTask0060ReductionKernelSource =
@"\n"
"inline bool fold_axis_source_0060(ulong linear, constant DataMeta &m, thread ulong &source) { ulong out[16], src[16]; decode_coords(linear,m.outDims,m.outputRank,out); uint axis=m.reserved; ulong size=m.attrs[0],step=m.attrs[1],position=out[axis]/step,offset=out[axis]%step; if(offset>=size||position>=m.inDims[axis])return false; for(uint a=0u;a<m.outputRank;++a)src[a]=out[a]; src[axis]=position; src[m.inputRank-1u]=offset; source=coords_linear(src,m.inDims,m.inputRank); return true; }\n"
"inline ulong window_extent_0060(ulong input,ulong kernelSize,ulong padding,ulong stride,ulong dilation,bool ceilMode){ulong effective=dilation*(kernelSize-1ul)+1ul,numerator=input+2ul*padding-effective;return numerator/stride+((ceilMode&&(numerator%stride!=0ul))?1ul:0ul)+1ul;}\n"
"inline bool fold_window_source_0060(ulong linear,constant DataMeta &m,uint dimensions,thread ulong &source){ulong out[16];decode_coords(linear,m.outDims,m.outputRank,out);uint targetRank=uint(m.attrs[0]),base=1u+targetRank;ulong kernelSize[3],stride[3],padding[3],dilation[3],position[3],element[3],positionExtent[3];ulong volume=1ul,positionLinear=0ul,kernelLinear=0ul;for(uint s=0u;s<dimensions;++s){kernelSize[s]=m.attrs[base+s];stride[s]=m.attrs[base+dimensions+s];padding[s]=m.attrs[base+2u*dimensions+s];dilation[s]=m.attrs[base+3u*dimensions+s];positionExtent[s]=window_extent_0060(m.outDims[s+2u],kernelSize[s],padding[s],stride[s],dilation[s],m.attrs[base+4u*dimensions]!=0ul);ulong shifted=out[s+2u]+padding[s];position[s]=shifted/stride[s];ulong remainder=shifted%stride[s];if(position[s]>=positionExtent[s]||remainder%dilation[s]!=0ul)return false;element[s]=remainder/dilation[s];if(element[s]>=kernelSize[s])return false;positionLinear=positionLinear*positionExtent[s]+position[s];kernelLinear=kernelLinear*kernelSize[s]+element[s];volume*=kernelSize[s];}ulong channel=out[1];source=((out[0]*m.outDims[1]+channel)*volume+kernelLinear)*m.inDims[2]+positionLinear;return true;}\n"
"kernel void exact_fold_0060(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=0ul;bool copied=m.operation==80u?fold_axis_source_0060(linear,m,source):fold_window_source_0060(linear,m,m.operation==82u?2u:3u,source);if(copied)copy_word(input,source,output,linear,m.width);else store_word(output,linear,m.width,0ul);}\n"
"inline bool slice_update_source_0060(ulong linear,constant DataMeta &m,thread ulong &source){ulong out[16],update[16];decode_coords(linear,m.outDims,m.outputRank,out);for(uint a=0u;a<m.outputRank;++a)update[a]=out[a];if(m.attributeKind==15u){uint rank=uint(m.attrs[0]),prefixOffset=1u+rank;for(uint a=0u;a<rank;++a){ulong length=m.attrs[1u+a],start=m.attrs[prefixOffset+1u+a];if(length==0ul||out[a]<start||out[a]-start>=length)return false;update[a]=out[a]-start;}}else{uint count=uint(m.attrs[0]);for(uint item=0u;item<count;++item){uint axis=uint(m.attrs[1u+count*2u+item]);long start=long(m.attrs[1u+item]),length=long(m.attrs[1u+count+item]),step=long(m.attrs[1u+count*3u+item]);if(length==0l)return false;long delta=long(out[axis])-start;if(delta%step!=0l)return false;long coordinate=delta/step;if(coordinate<0l||coordinate>=length)return false;update[axis]=ulong(coordinate);}}source=coords_storage(update,m.auxiliaryStrides,m.auxRank,m.auxiliaryOffset);return true;}\n"
"kernel void exact_slice_update_0060(device const uchar *data [[buffer(0)]],device const uchar *updates [[buffer(1)]],device uchar *output [[buffer(2)]],constant DataMeta &m [[buffer(3)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong source=0ul;if(slice_update_source_0060(linear,m,source))copy_word(updates,source,output,linear,m.width);else copy_word(data,linear,output,linear,m.width);}\n"
"kernel void exact_scatter_copy_0060(device const uchar *data [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong linear=data_linear_id(gid,m);if(linear<m.elementCount)copy_word(data,linear,output,linear,m.width);}\n"
"kernel void exact_scatter_nd_0060(device const uchar *data [[buffer(0)]],device const uchar *indices [[buffer(1)]],device const uchar *updates [[buffer(2)]],device uchar *output [[buffer(3)]],constant DataMeta &m [[buffer(4)]],uint3 gid [[thread_position_in_grid]]){(void)data;ulong linear=data_linear_id(gid,m);if(linear>=m.elementCount)return;ulong update[16],target[16];decode_coords(linear,m.inputExtents,m.reserved,update);uint batch=uint(m.attrs[0]),q=m.auxRank,k=uint(m.auxDims[q-1u]);for(uint a=0u;a<batch;++a)target[a]=update[a];ulong tuple=0ul;for(uint a=0u;a<q-1u;++a)tuple=tuple*m.auxDims[a]+update[a];for(uint j=0u;j<k;++j)target[batch+j]=ulong(read_index(indices,tuple*ulong(k)+j,m.indexType));for(uint a=batch+k;a<m.inputRank;++a)target[a]=update[q-1u+a-(batch+k)];ulong destination=coords_linear(target,m.outDims,m.outputRank);copy_word(updates,linear,output,destination,m.width);}\n"
"kernel void exact_reduce_0060(device const uchar *input [[buffer(0)]],device uchar *output [[buffer(1)]],constant DataMeta &m [[buffer(2)]],uint3 gid [[thread_position_in_grid]]){ulong outLinear=data_linear_id(gid,m);if(outLinear>=m.elementCount)return;uint axesMask=uint(m.attrs[0]);ulong product=1ul;bool logical=m.operation==107u;for(ulong source=0ul;source<m.inputExtents[0];++source){ulong remaining=source,projected=0ul,scale=1ul;for(int axis=int(m.inputRank)-1;axis>=0;--axis){ulong coordinate=remaining%m.inDims[axis];remaining/=m.inDims[axis];if((axesMask&(1u<<uint(axis)))==0u){projected+=coordinate*scale;scale*=m.inDims[axis];}}if(projected!=outLinear)continue;ulong word=load_word(input,source,m.width);if(m.operation==106u)product=m.width==4u?ulong(uint(product)*uint(word)):product*word;else if(m.operation==107u)logical=logical&&((word&0xfful)!=0ul);else logical=logical||((word&0xfful)!=0ul);}if(m.operation==106u)store_word(output,outLinear,m.width,product);else store_word(output,outLinear,1u,logical?1ul:0ul);}\n";

#endif
