package backend.cpu1.kernels.loss.crossentropy;

public enum Cpu1DenseCrossEntropyKernelId {
    CROSS_ENTROPY_DENSE_F32_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_DENSE_F64_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_DENSE_BF16_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_DENSE_F32_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_DENSE_F64_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_DENSE_BF16_SEGMENT_DENSE_SCALAR
}
