package backend.cpu1.kernels.loss.crossentropy;

public enum Cpu1CrossEntropyKernelId {
    CROSS_ENTROPY_INDICES_F32_I32_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F32_I64_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F64_I32_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F64_I64_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_BF16_I32_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_BF16_I64_ARRAY_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F32_I32_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F32_I64_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F64_I32_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_F64_I64_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_BF16_I32_SEGMENT_DENSE_SCALAR,
    CROSS_ENTROPY_INDICES_BF16_I64_SEGMENT_DENSE_SCALAR
}
