package backend.metal.exec;

/**
 * Stable reason codes explaining a Metal-internal route decision.
 */
public enum MetalRouteReasonCode {
    MPS_GRAPH_SELECTED,
    CUSTOM_KERNEL_SELECTED,
    CUSTOM_KERNEL_UNAVAILABLE,
    BRIDGE_UNAVAILABLE,
    BUFFER_ABI_UNAVAILABLE,
    TENSOR_ARRAY_FALLBACK,
    CPU_FALLBACK,
    UNAVAILABLE_REQUIRED,
    INSUFFICIENT_WORK,
    UNSUPPORTED_DTYPE,
    UNSUPPORTED_LAYOUT,
    UNSUPPORTED_OPERATION_FAMILY,
    NATIVE_COPY_COST_UNKNOWN
}
