package backend.cpu1.kernels.loss.nll;

public enum Cpu1NllLossKernelId {
    NLL_DENSE_F32_ARRAY_DENSE_SCALAR,
    NLL_DENSE_F64_ARRAY_DENSE_SCALAR,
    NLL_DENSE_BF16_ARRAY_DENSE_SCALAR,
    NLL_DENSE_F32_SEGMENT_DENSE_SCALAR,
    NLL_DENSE_F64_SEGMENT_DENSE_SCALAR,
    NLL_DENSE_BF16_SEGMENT_DENSE_SCALAR
}
