package backend.cpu.kernels;

import backend.cpu.kernels.elementwise.binary.*;
import backend.cpu.kernels.elementwise.compare.*;
import backend.cpu.kernels.elementwise.grad.*;
import backend.cpu.kernels.fused.CpuFusedKernel;
import backend.cpu.kernels.index.*;
import backend.cpu.kernels.layout.*;
import backend.cpu.kernels.linalg.*;
import backend.cpu.kernels.elementwise.logical.*;
import backend.cpu.kernels.nn.*;
import backend.cpu.kernels.reduction.*;
import backend.cpu.kernels.reduction.grad.*;
import backend.cpu.kernels.elementwise.unary.*;
import backend.cpu.kernels.elementwise.where.*;
import operations.Operation;

public final class CpuKernelRegistry {
    private static final CpuAddKernel ADD = new CpuAddKernel();
    private static final CpuSubKernel SUB = new CpuSubKernel();
    private static final CpuMulKernel MUL = new CpuMulKernel();
    private static final CpuDivKernel DIV = new CpuDivKernel();
    private static final CpuMinKernel MIN = new CpuMinKernel();
    private static final CpuMaxKernel MAX = new CpuMaxKernel();
    private static final CpuGreaterThanKernel GT = new CpuGreaterThanKernel();
    private static final CpuGreaterOrEqualKernel GE = new CpuGreaterOrEqualKernel();
    private static final CpuLessThanKernel LT = new CpuLessThanKernel();
    private static final CpuLessOrEqualKernel LE = new CpuLessOrEqualKernel();
    private static final CpuEqualToKernel EQ = new CpuEqualToKernel();
    private static final CpuNotEqualToKernel NE = new CpuNotEqualToKernel();
    private static final CpuLogicalAndKernel LOGICAL_AND = new CpuLogicalAndKernel();
    private static final CpuLogicalOrKernel LOGICAL_OR = new CpuLogicalOrKernel();
    private static final CpuLogicalNotKernel LOGICAL_NOT = new CpuLogicalNotKernel();
    private static final CpuGatherKernel GATHER = new CpuGatherKernel();
    private static final CpuGatherAxisKernel GATHER_AXIS = new CpuGatherAxisKernel();
    private static final CpuGatherNdKernel GATHER_ND = new CpuGatherNdKernel();
    private static final CpuTakeAlongAxisKernel TAKE_ALONG_AXIS = new CpuTakeAlongAxisKernel();
    private static final CpuScatterAddKernel SCATTER_ADD = new CpuScatterAddKernel();
    private static final CpuScatterAxisAddKernel SCATTER_AXIS_ADD = new CpuScatterAxisAddKernel();
    private static final CpuScatterElementsKernel SCATTER_ELEMENTS = new CpuScatterElementsKernel();
    private static final CpuScatterNdKernel SCATTER_ND = new CpuScatterNdKernel();
    private static final CpuScaledDotProductAttentionKernel SCALED_DOT_PRODUCT_ATTENTION = new CpuScaledDotProductAttentionKernel();
    private static final CpuScaledDotProductAttentionWeightsKernel SCALED_DOT_PRODUCT_ATTENTION_WEIGHTS = new CpuScaledDotProductAttentionWeightsKernel();
    private static final CpuLinearKernel LINEAR = new CpuLinearKernel();
    private static final CpuConv2dKernel CONV2D = new CpuConv2dKernel();
    private static final CpuConv2dGemmKernel CONV2D_GEMM = new CpuConv2dGemmKernel();
    private static final CpuConv2dBackwardInputKernel CONV2D_BACKWARD_INPUT = new CpuConv2dBackwardInputKernel();
    private static final CpuConv2dBackwardWeightKernel CONV2D_BACKWARD_WEIGHT = new CpuConv2dBackwardWeightKernel();
    private static final CpuConv2dBackwardInputGemmKernel CONV2D_BACKWARD_INPUT_GEMM = new CpuConv2dBackwardInputGemmKernel();
    private static final CpuConv2dBackwardWeightGemmKernel CONV2D_BACKWARD_WEIGHT_GEMM = new CpuConv2dBackwardWeightGemmKernel();
    private static final CpuMaxPool2dKernel MAX_POOL2D = new CpuMaxPool2dKernel();
    private static final CpuMaxPool2dBackwardInputKernel MAX_POOL2D_BACKWARD_INPUT = new CpuMaxPool2dBackwardInputKernel();
    private static final CpuAvgPool2dKernel AVG_POOL2D = new CpuAvgPool2dKernel();
    private static final CpuAvgPool2dBackwardInputKernel AVG_POOL2D_BACKWARD_INPUT = new CpuAvgPool2dBackwardInputKernel();
    private static final CpuLayerNormKernel LAYER_NORM = new CpuLayerNormKernel();
    private static final CpuRmsNormKernel RMS_NORM = new CpuRmsNormKernel();
    private static final CpuReduceMinKernel REDUCE_MIN = new CpuReduceMinKernel();
    private static final CpuReduceMaxKernel REDUCE_MAX = new CpuReduceMaxKernel();
    private static final CpuReduceProdKernel REDUCE_PROD = new CpuReduceProdKernel();
    private static final CpuCumSumKernel CUMSUM = new CpuCumSumKernel();
    private static final CpuArgMaxKernel ARGMAX = new CpuArgMaxKernel();
    private static final CpuReduceAllKernel REDUCE_ALL = new CpuReduceAllKernel();
    private static final CpuReduceAnyKernel REDUCE_ANY = new CpuReduceAnyKernel();
    private static final CpuSoftmaxKernel SOFTMAX = new CpuSoftmaxKernel();
    private static final CpuLogSoftmaxKernel LOG_SOFTMAX = new CpuLogSoftmaxKernel();
    private static final CpuNllLossKernel NLL_LOSS = new CpuNllLossKernel();
    private static final CpuCrossEntropyLossKernel CROSS_ENTROPY_LOSS = new CpuCrossEntropyLossKernel();
    private static final CpuCrossEntropyLossIndicesKernel CROSS_ENTROPY_LOSS_INDICES = new CpuCrossEntropyLossIndicesKernel();
    private static final CpuMatMulKernel MATMUL = new CpuMatMulKernel();
    private static final CpuNegKernel NEG = new CpuNegKernel();
    private static final CpuInvKernel INV = new CpuInvKernel();
    private static final CpuLogKernel LOG = new CpuLogKernel();
    private static final CpuExpKernel EXP = new CpuExpKernel();
    private static final CpuFastExpKernel FAST_EXP = new CpuFastExpKernel();
    private static final CpuErfKernel ERF = new CpuErfKernel();
    private static final CpuTanhKernel TANH = new CpuTanhKernel();
    private static final CpuFastTanhKernel FAST_TANH = new CpuFastTanhKernel();
    private static final CpuPowKernel POW = new CpuPowKernel();
    private static final CpuPowTensorKernel POW_TENSOR = new CpuPowTensorKernel();
    private static final CpuSqrtKernel SQRT = new CpuSqrtKernel();
    private static final CpuAbsKernel ABS = new CpuAbsKernel();
    private static final CpuFloorKernel FLOOR = new CpuFloorKernel();
    private static final CpuCeilKernel CEIL = new CpuCeilKernel();
    private static final CpuSignKernel SIGN = new CpuSignKernel();
    private static final CpuMulScalarKernel MUL_SCALAR = new CpuMulScalarKernel();
    private static final CpuSumKernel SUM = new CpuSumKernel();
    private static final CpuMeanKernel MEAN = new CpuMeanKernel();
    private static final CpuReluKernel RELU = new CpuReluKernel();
    private static final CpuClampMinKernel CLAMP_MIN = new CpuClampMinKernel();
    private static final CpuClampMaxKernel CLAMP_MAX = new CpuClampMaxKernel();
    private static final CpuSigmoidKernel SIGMOID = new CpuSigmoidKernel();
    private static final CpuWhereKernel WHERE = new CpuWhereKernel();
    private static final CpuContiguousKernel CONTIGUOUS = new CpuContiguousKernel();
    private static final CpuReshapeLikeKernel RESHAPE = new CpuReshapeLikeKernel();
    private static final CpuExpandKernel EXPAND = new CpuExpandKernel();
    private static final CpuAliasViewKernel ALIAS_VIEW = new CpuAliasViewKernel();
    private static final CpuSliceScatterAddKernel SLICE_SCATTER_ADD = new CpuSliceScatterAddKernel();
    private static final CpuConcatKernel CONCAT = new CpuConcatKernel();
    private static final CpuPadKernel PAD = new CpuPadKernel();
    private static final CpuTileKernel TILE = new CpuTileKernel();
    private static final CpuCastKernel CAST = new CpuCastKernel();
    private static final CpuPermuteKernel PERMUTE = new CpuPermuteKernel();
    private static final CpuNoopKernel NOOP = new CpuNoopKernel();
    private static final CpuFusedKernel FUSED = new CpuFusedKernel();

    private CpuKernelRegistry() {
    }

    public static CpuKernel resolve(Operation.OpType type) {
        return switch (type) {
            case ADD -> ADD;
            case SUB -> SUB;
            case MUL -> MUL;
            case DIV -> DIV;
            case MIN -> MIN;
            case MAX -> MAX;
            case GT -> GT;
            case GE -> GE;
            case LT -> LT;
            case LE -> LE;
            case EQ -> EQ;
            case NE -> NE;
            case LOGICAL_AND -> LOGICAL_AND;
            case LOGICAL_OR -> LOGICAL_OR;
            case LOGICAL_NOT -> LOGICAL_NOT;
            case GATHER -> GATHER;
            case GATHER_AXIS -> GATHER_AXIS;
            case GATHER_ND -> GATHER_ND;
            case TAKE_ALONG_AXIS -> TAKE_ALONG_AXIS;
            case SCATTER_ADD -> SCATTER_ADD;
            case SCATTER_AXIS_ADD -> SCATTER_AXIS_ADD;
            case SCATTER_ELEMENTS -> SCATTER_ELEMENTS;
            case SCATTER_ND -> SCATTER_ND;
            case SCALED_DOT_PRODUCT_ATTENTION -> SCALED_DOT_PRODUCT_ATTENTION;
            case SCALED_DOT_PRODUCT_ATTENTION_WEIGHTS -> SCALED_DOT_PRODUCT_ATTENTION_WEIGHTS;
            case LINEAR -> LINEAR;
            case CONV2D -> CONV2D;
            case CONV2D_GEMM -> CONV2D_GEMM;
            case CONV2D_BACKWARD_INPUT -> CONV2D_BACKWARD_INPUT;
            case CONV2D_BACKWARD_WEIGHT -> CONV2D_BACKWARD_WEIGHT;
            case CONV2D_BACKWARD_INPUT_GEMM -> CONV2D_BACKWARD_INPUT_GEMM;
            case CONV2D_BACKWARD_WEIGHT_GEMM -> CONV2D_BACKWARD_WEIGHT_GEMM;
            case MAX_POOL2D -> MAX_POOL2D;
            case MAX_POOL2D_BACKWARD_INPUT -> MAX_POOL2D_BACKWARD_INPUT;
            case AVG_POOL2D -> AVG_POOL2D;
            case AVG_POOL2D_BACKWARD_INPUT -> AVG_POOL2D_BACKWARD_INPUT;
            case LAYER_NORM -> LAYER_NORM;
            case RMS_NORM -> RMS_NORM;
            case REDUCE_MIN -> REDUCE_MIN;
            case REDUCE_MAX -> REDUCE_MAX;
            case REDUCE_PROD -> REDUCE_PROD;
            case CUMSUM -> CUMSUM;
            case ARGMAX -> ARGMAX;
            case REDUCE_ALL -> REDUCE_ALL;
            case REDUCE_ANY -> REDUCE_ANY;
            case SOFTMAX -> SOFTMAX;
            case LOG_SOFTMAX -> LOG_SOFTMAX;
            case NLL_LOSS -> NLL_LOSS;
            case CROSS_ENTROPY_LOSS -> CROSS_ENTROPY_LOSS;
            case CROSS_ENTROPY_LOSS_INDICES -> CROSS_ENTROPY_LOSS_INDICES;
            case MATMUL -> MATMUL;
            case NEG -> NEG;
            case INV -> INV;
            case LOG -> LOG;
            case EXP -> EXP;
            case FAST_EXP -> FAST_EXP;
            case ERF -> ERF;
            case TANH -> TANH;
            case FAST_TANH -> FAST_TANH;
            case POW -> POW;
            case POW_TENSOR -> POW_TENSOR;
            case SQRT -> SQRT;
            case ABS -> ABS;
            case FLOOR -> FLOOR;
            case CEIL -> CEIL;
            case SIGN -> SIGN;
            case MUL_SCALAR -> MUL_SCALAR;
            case SUM -> SUM;
            case MEAN -> MEAN;
            case RELU -> RELU;
            case CLAMP_MIN -> CLAMP_MIN;
            case CLAMP_MAX -> CLAMP_MAX;
            case SIGMOID -> SIGMOID;
            case WHERE -> WHERE;
            case CONTIGUOUS -> CONTIGUOUS;
            case RESHAPE -> RESHAPE;
            case EXPAND -> EXPAND;
            case SELECT, SLICE, EXPAND_DIMS, SQUEEZE -> ALIAS_VIEW;
            case SLICE_SCATTER_ADD -> SLICE_SCATTER_ADD;
            case CONCAT -> CONCAT;
            case PAD -> PAD;
            case TILE -> TILE;
            case CAST -> CAST;
            case PERMUTE -> PERMUTE;
            case MIN_GRAD, MAX_GRAD, REDUCE_MIN_GRAD, REDUCE_MAX_GRAD,
                    SOFTMAX_GRAD, LOG_SOFTMAX_GRAD,
                    GATHER_GRAD, GATHER_AXIS_GRAD, GATHER_ND_GRAD, TAKE_ALONG_AXIS_GRAD,
                    SLICE_GRAD, CROSS_ENTROPY_LOSS_INDICES_GRAD,
                    SCALED_DOT_PRODUCT_ATTENTION_BACKWARD ->
                    throw new IllegalStateException("CPU has no direct kernel for legacy backward op type " + type);
            case CONST_SCALAR -> throw new IllegalStateException("CONST_SCALAR is an internal fused-plan op and has no standalone CPU kernel");
            case NOOP -> NOOP;
            case FUSED -> FUSED;
            case UNKNOWN -> throw new IllegalStateException("Cannot resolve CPU kernel for UNKNOWN operation type");
        };
    }
}
