package io.github.pho001.synaptik.compiler;

import io.github.pho001.synaptik.model.datatype.DataType;
import io.github.pho001.synaptik.model.datatype.DataTypePromotion;
import io.github.pho001.synaptik.model.operation.Operation;
import io.github.pho001.synaptik.model.operation.attention.*;
import io.github.pho001.synaptik.model.operation.convolution.*;
import io.github.pho001.synaptik.model.operation.linalg.MatmulKind;
import io.github.pho001.synaptik.model.operation.loss.*;
import io.github.pho001.synaptik.model.operation.pooling.*;
import io.github.pho001.synaptik.model.operation.random.*;
import io.github.pho001.synaptik.model.shape.Dimension;
import io.github.pho001.synaptik.model.shape.DimensionExpressions;
import io.github.pho001.synaptik.model.shape.Shape;
import io.github.pho001.synaptik.model.shape.StaticDimension;
import io.github.pho001.synaptik.model.tensor.TensorDescriptor;
import java.util.ArrayList;
import java.util.List;

/**
 * Derives descriptors and constraints for structured numeric, loss, and explicit graph-state
 * operation families.
 */
final class StructuredOperationInference {
    private StructuredOperationInference() {}

    /**
     * Verifies one supported matrix, attention, convolution, pooling, loss, RNG, or dropout
     * occurrence.
     *
     * @param op non-null typed operation whose kind belongs to this family
     * @param in non-null ordered input descriptors supplied by the captured node
     * @param outputCount structurally validated stored output count, used only to select an
     *     accepted multi-output signature
     * @return immutable independently derived descriptors and ordered constraints; never
     *     {@code null}
     * @throws IllegalArgumentException if the kind is unsupported here or the occurrence violates
     *     its operand, Shape, state, output-role, or attribute contract
     */
    static CapturedGraphInference.InferenceResult infer(
            Operation op, List<TensorDescriptor> in, int outputCount) {
        if(op.kind() instanceof MatmulKind)return matmul(in);
        if(op.kind() instanceof ScaledDotProductAttentionKind)return attention((ScaledDotProductAttentionAttrs)op.attrs(),in,outputCount);
        if(op.kind() instanceof Conv2dKind)return conv((Conv2dAttrs)op.attrs(),in);
        if(op.kind() instanceof Pool2dKind k)return pool(k,op.attrs(),in);
        if(op.kind() instanceof LossKind k)return loss(k,op.attrs(),in);
        if(op.kind() instanceof GraphRngKind)return CapturedGraphInference.InferenceResult.of(ElementwiseInference.descriptor(DataType.INT64,Shape.of(2),false));
        if(op.kind() instanceof DropoutKind)return dropout(in);
        throw new IllegalArgumentException("unsupported structured kind");
    }
    private static CapturedGraphInference.InferenceResult matmul(List<TensorDescriptor>in){TensorDescriptor l=in.get(0),r=in.get(1);DataType t=DataTypePromotion.promoteNumeric(l.dataType(),r.dataType());Shape a=l.shape(),b=r.shape();if(a.rank()<1||b.rank()<1)throw new IllegalArgumentException("matmul rank must be at least one");List<CapturedGraphInference.ConstraintRequest>cs=new ArrayList<>();cs.add(new CapturedGraphInference.ConstraintRequest("matmul contraction",new DimensionEqual(a.dimension(a.rank()-1),b.dimension(b.rank()==1?0:b.rank()-2))));int ar=Math.max(0,a.rank()-2),br=Math.max(0,b.rank()-2),rr=Math.max(ar,br);List<Dimension>d=new ArrayList<>();for(int i=0;i<rr;i++){Dimension x=i<rr-ar?null:a.dimension(i-(rr-ar)),y=i<rr-br?null:b.dimension(i-(rr-br));d.add(batch(x,y,"matmul",i,cs));}if(a.rank()!=1)d.add(a.dimension(a.rank()-2));if(b.rank()!=1)d.add(b.dimension(b.rank()-1));return new CapturedGraphInference.InferenceResult(List.of(ElementwiseInference.descriptor(t,Shape.ofDimensions(d.toArray(Dimension[]::new)),l.requiresGrad()||r.requiresGrad())),cs);}
    private static CapturedGraphInference.InferenceResult attention(ScaledDotProductAttentionAttrs attrs,List<TensorDescriptor>in,int outputCount){TensorDescriptor q=in.get(0),k=in.get(1),v=in.get(2);ElementwiseInference.requireFloating(q,"query");ElementwiseInference.requireFloating(k,"key");ElementwiseInference.requireFloating(v,"value");if(q.shape().rank()<2||k.shape().rank()<2||v.shape().rank()<2)throw new IllegalArgumentException("attention rank must be at least two");DataType t=DataTypePromotion.promoteFloating(DataTypePromotion.promoteFloating(q.dataType(),k.dataType()),v.dataType());if(attrs.scale().isPresent()&&attrs.scale().orElseThrow().dataType()!=t)throw new IllegalArgumentException("scale data type mismatch");List<CapturedGraphInference.ConstraintRequest>cs=new ArrayList<>();Dimension qe=q.shape().dimension(q.shape().rank()-1),ke=k.shape().dimension(k.shape().rank()-1),ks=k.shape().dimension(k.shape().rank()-2),vs=v.shape().dimension(v.shape().rank()-2);cs.add(new CapturedGraphInference.ConstraintRequest("attention embedding",new DimensionEqual(qe,ke)));cs.add(new CapturedGraphInference.ConstraintRequest("attention embedding positive",new DimensionAtLeast(qe,1)));cs.add(new CapturedGraphInference.ConstraintRequest("attention key/value sequence",new DimensionEqual(ks,vs)));int qr=q.shape().rank()-2,kr=k.shape().rank()-2,vr=v.shape().rank()-2,rr=Math.max(qr,Math.max(kr,vr));List<Dimension>batch=new ArrayList<>();for(int i=0;i<rr;i++){Dimension a=aligned(q.shape(),qr,rr,i),b=aligned(k.shape(),kr,rr,i),c=aligned(v.shape(),vr,rr,i);Dimension selected=batch(a,b,"attention",i,cs);selected=batch(selected,c,"attention",i,cs);batch.add(selected);}List<Dimension>scores=new ArrayList<>(batch);scores.add(q.shape().dimension(q.shape().rank()-2));scores.add(ks);Shape score=Shape.ofDimensions(scores.toArray(Dimension[]::new));if(in.size()==4){TensorDescriptor mask=in.get(3);ElementwiseInference.requireBool(mask,"mask");if(mask.shape().rank()>score.rank())throw new IllegalArgumentException("mask rank exceeds score rank");int off=score.rank()-mask.shape().rank();for(int i=0;i<mask.shape().rank();i++)cs.add(new CapturedGraphInference.ConstraintRequest("attention mask axis "+i,new AnyOf(List.of(new DimensionEqual(mask.shape().dimension(i),new StaticDimension(1)),new DimensionEqual(mask.shape().dimension(i),score.dimension(off+i))))));}List<Dimension>out=new ArrayList<>(batch);out.add(q.shape().dimension(q.shape().rank()-2));out.add(v.shape().dimension(v.shape().rank()-1));TensorDescriptor output=ElementwiseInference.descriptor(t,Shape.ofDimensions(out.toArray(Dimension[]::new)),q.requiresGrad()||k.requiresGrad()||v.requiresGrad());List<TensorDescriptor>outs=new ArrayList<>();outs.add(output);if(outputCount==2)outs.add(ElementwiseInference.descriptor(t,score,q.requiresGrad()||k.requiresGrad()));return new CapturedGraphInference.InferenceResult(outs,cs);}
    private static CapturedGraphInference.InferenceResult conv(Conv2dAttrs a,List<TensorDescriptor>in){TensorDescriptor x=in.get(0),w=in.get(1),bias=in.size()==3?in.get(2):null;ElementwiseInference.requireFloating(x,"input");ElementwiseInference.requireFloating(w,"weight");if(x.shape().rank()!=4||w.shape().rank()!=4)throw new IllegalArgumentException("conv rank must be four");DataType t=DataTypePromotion.promoteFloating(x.dataType(),w.dataType());boolean grad=x.requiresGrad()||w.requiresGrad();if(bias!=null){ElementwiseInference.requireFloating(bias,"bias");if(bias.shape().rank()!=1)throw new IllegalArgumentException("bias rank must be one");t=DataTypePromotion.promoteFloating(t,bias.dataType());grad|=bias.requiresGrad();}if(!(w.shape().dimension(2)instanceof StaticDimension kh)||kh.size()==0||!(w.shape().dimension(3)instanceof StaticDimension kw)||kw.size()==0)throw new IllegalArgumentException("kernel dimensions must be positive static");List<CapturedGraphInference.ConstraintRequest>cs=new ArrayList<>();Dimension ic=x.shape().dimension(1),oc=w.shape().dimension(0),wc=w.shape().dimension(1);cs.add(new CapturedGraphInference.ConstraintRequest("input channels divisible by groups",new DimensionDivisible(ic,a.groups())));cs.add(new CapturedGraphInference.ConstraintRequest("output channels divisible by groups",new DimensionDivisible(oc,a.groups())));cs.add(new CapturedGraphInference.ConstraintRequest("weight channels",new DimensionEqual(DimensionExpressions.multiply(wc,a.groups()),ic)));if(bias!=null)cs.add(new CapturedGraphInference.ConstraintRequest("bias channels",new DimensionEqual(bias.shape().dimension(0),oc)));Dimension oh=spatial(x.shape().dimension(2),kh.size(),a.paddingHeight(),a.dilationHeight(),a.strideHeight(),false),ow=spatial(x.shape().dimension(3),kw.size(),a.paddingWidth(),a.dilationWidth(),a.strideWidth(),false);return new CapturedGraphInference.InferenceResult(List.of(ElementwiseInference.descriptor(t,Shape.ofDimensions(x.shape().dimension(0),oc,oh,ow),grad)),cs);}
    private static CapturedGraphInference.InferenceResult pool(Pool2dKind kind,Object raw,List<TensorDescriptor>in){TensorDescriptor x=in.get(0);ElementwiseInference.requireFloating(x,"input");if(x.shape().rank()!=4)throw new IllegalArgumentException("pool input rank must be four");long kh,kw,ph,pw,dh,dw,sh,sw;boolean ceil;if(kind==Pool2dKind.MAX_POOL2D){MaxPool2dAttrs a=(MaxPool2dAttrs)raw;kh=a.kernelHeight();kw=a.kernelWidth();ph=a.paddingHeight();pw=a.paddingWidth();dh=a.dilationHeight();dw=a.dilationWidth();sh=a.strideHeight();sw=a.strideWidth();ceil=a.ceilMode();}else{AveragePool2dAttrs a=(AveragePool2dAttrs)raw;kh=a.kernelHeight();kw=a.kernelWidth();ph=a.paddingHeight();pw=a.paddingWidth();dh=a.dilationHeight();dw=a.dilationWidth();sh=a.strideHeight();sw=a.strideWidth();ceil=a.ceilMode();}Shape s=Shape.ofDimensions(x.shape().dimension(0),x.shape().dimension(1),spatial(x.shape().dimension(2),kh,ph,dh,sh,ceil),spatial(x.shape().dimension(3),kw,pw,dw,sw,ceil));return CapturedGraphInference.InferenceResult.of(ElementwiseInference.descriptor(x.dataType(),s,x.requiresGrad()));}
    private static CapturedGraphInference.InferenceResult loss(LossKind kind,Object raw,List<TensorDescriptor>in){TensorDescriptor logits=in.get(0),target=in.get(1);ElementwiseInference.requireFloating(logits,"prediction/logits");List<CapturedGraphInference.ConstraintRequest>cs=new ArrayList<>();Shape result;DataType t;boolean grad;if(kind==LossKind.MEAN_SQUARED_ERROR){ElementwiseInference.requireFloating(target,"target");exactShape(logits.shape(),target.shape(),"MSE",cs);t=DataTypePromotion.promoteFloating(logits.dataType(),target.dataType());LossReduction r=((MeanSquaredErrorAttrs)raw).reduction();result=r==LossReduction.NONE?logits.shape():Shape.scalar();grad=logits.requiresGrad()||target.requiresGrad();}else if(kind==LossKind.DENSE_CATEGORICAL_CROSS_ENTROPY_WITH_LOGITS){ElementwiseInference.requireFloating(target,"target");DenseCategoricalCrossEntropyWithLogitsAttrs a=(DenseCategoricalCrossEntropyWithLogitsAttrs)raw;axis(logits.shape(),a.axis());exactShape(logits.shape(),target.shape(),"dense target",cs);t=DataTypePromotion.promoteFloating(logits.dataType(),target.dataType());result=a.reduction()==LossReduction.NONE?remove(logits.shape(),a.axis()):Shape.scalar();grad=logits.requiresGrad()||target.requiresGrad();cs.add(classConstraint(logits.shape(),a.axis()));}else{ElementwiseInference.requireIndex(target,"target");IndexCategoricalCrossEntropyWithLogitsAttrs a=(IndexCategoricalCrossEntropyWithLogitsAttrs)raw;axis(logits.shape(),a.axis());Shape expected=remove(logits.shape(),a.axis());exactShape(expected,target.shape(),"index target",cs);if(a.ignoreIndex().isPresent()&&a.ignoreIndex().orElseThrow().dataType()!=target.dataType())throw new IllegalArgumentException("ignore index type mismatch");if(a.ignoreIndex().isEmpty())cs.add(classConstraint(logits.shape(),a.axis()));t=logits.dataType();result=a.reduction()==LossReduction.NONE?target.shape():Shape.scalar();grad=logits.requiresGrad();}return new CapturedGraphInference.InferenceResult(List.of(ElementwiseInference.descriptor(t,result,grad)),cs);}
    private static CapturedGraphInference.ConstraintRequest classConstraint(Shape s,int axis){return new CapturedGraphInference.ConstraintRequest("categorical class extent",new AnyOf(List.of(new ShapeElementCountValue(remove(s,axis),0,ShapeElementCountValue.Comparison.EQUAL),new DimensionAtLeast(s.dimension(axis),1))));}
    private static CapturedGraphInference.InferenceResult dropout(List<TensorDescriptor>in){TensorDescriptor x=in.get(0),state=in.get(1);ElementwiseInference.requireFloating(x,"input");if(state.dataType()!=DataType.INT64||!state.shape().equals(Shape.of(2))||state.requiresGrad())throw new IllegalArgumentException("invalid RNG state descriptor");return new CapturedGraphInference.InferenceResult(List.of(ElementwiseInference.descriptor(x.dataType(),x.shape(),x.requiresGrad()),ElementwiseInference.descriptor(DataType.BOOL,x.shape(),false),ElementwiseInference.descriptor(DataType.INT64,Shape.of(2),false)),List.of());}
    private static Dimension batch(Dimension a,Dimension b,String name,int axis,List<CapturedGraphInference.ConstraintRequest>cs){if(a==null)return b;if(b==null)return a;if(a.equals(b))return a;if(a instanceof StaticDimension sa&&sa.size()==1)return b;if(b instanceof StaticDimension sb&&sb.size()==1)return a;if(a instanceof StaticDimension&&b instanceof StaticDimension)throw new IllegalArgumentException(name+" batch mismatch");Dimension selected=a instanceof StaticDimension?a:b instanceof StaticDimension?b:null;if(selected==null)throw new IllegalArgumentException(name+" cannot select batch dimension");Dimension other=selected==a?b:a;cs.add(new CapturedGraphInference.ConstraintRequest(name+" batch axis "+axis,new AnyOf(List.of(new DimensionEqual(other,new StaticDimension(1)),new DimensionEqual(other,selected)))));return selected;}
    private static Dimension aligned(Shape s,int br,int rr,int axis){int off=rr-br;return axis<off?null:s.dimension(axis-off);}
    private static Dimension spatial(Dimension in,long kernel,long pad,long dilation,long stride,boolean ceil){long eff=Math.addExact(Math.multiplyExact(dilation,kernel-1),1),offset=Math.subtractExact(Math.multiplyExact(2,pad),eff);if(in instanceof StaticDimension s){long n=Math.addExact(s.size(),offset);if(n<0)throw new IllegalArgumentException("effective kernel does not fit");return new StaticDimension(Math.addExact(n/stride+(ceil&&n%stride!=0?1:0),1));}Dimension n=DimensionExpressions.addConstant(in,offset);return DimensionExpressions.addConstant(ceil?DimensionExpressions.ceilingDivide(n,stride):DimensionExpressions.floorDivide(n,stride),1);}
    private static void exactShape(Shape a,Shape b,String role,List<CapturedGraphInference.ConstraintRequest>cs){if(a.rank()!=b.rank())throw new IllegalArgumentException(role+" rank mismatch");for(int i=0;i<a.rank();i++)cs.add(new CapturedGraphInference.ConstraintRequest(role+" axis "+i,new DimensionEqual(a.dimension(i),b.dimension(i))));}
    private static Shape remove(Shape s,int axis){List<Dimension>d=new ArrayList<>(s.dimensions());d.remove(axis);return Shape.ofDimensions(d.toArray(Dimension[]::new));}
    private static void axis(Shape s,int a){if(a<0||a>=s.rank())throw new IllegalArgumentException("axis out of range");}
}
