// GENERATED by scripts/generate-cpu1-elementwise.js. Do not edit by hand.
package backend.cpu1.kernels.elementwise.unary.tanh;

import backend.cpu1.exec.Cpu1KernelArgs;
import backend.cpu1.exec.Cpu1TensorView;
import backend.cpu1.offset.Cpu1GenericOffsetPlan;
import jdk.incubator.vector.DoubleVector;
import jdk.incubator.vector.FloatVector;
import jdk.incubator.vector.VectorOperators;
import jdk.incubator.vector.VectorSpecies;
import tensor.dtype.TensorDTypeOps;
import utils.FastTranscendentals;
import utils.SpecialFunctions;

import java.lang.foreign.MemorySegment;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * Static tanh/fast_tanh loops selected by Cpu1ElementwiseKernelId at prepare time.
 */
public final class Cpu1TanhLoops {
    private static final VectorSpecies<Float> F32 = FloatVector.SPECIES_PREFERRED;
    private static final VectorSpecies<Double> F64 = DoubleVector.SPECIES_PREFERRED;
    private static final ByteOrder ORDER = ByteOrder.nativeOrder();
    private static final int BROADCAST_CONTIGUOUS = 0;
    private static final int BROADCAST_SCALAR = 1;
    private static final int BROADCAST_INNER = 2;

    private Cpu1TanhLoops() {
    }

    private static int broadcastVectorMode(Cpu1TensorView view) {
        if (isBroadcastScalar(view)) {
            return BROADCAST_SCALAR;
        }
        if (isBroadcastInner(view)) {
            return BROADCAST_INNER;
        }
        return BROADCAST_CONTIGUOUS;
    }

    private static int broadcastVectorInnerSize(Cpu1TensorView outputView) {
        int rank = outputView.rank();
        return rank == 0 ? 1 : outputView.shape(rank - 1);
    }

    private static boolean isBroadcastScalar(Cpu1TensorView view) {
        for (int dim = 0; dim < view.rank(); dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return true;
    }

    private static boolean isBroadcastInner(Cpu1TensorView view) {
        int rank = view.rank();
        if (rank == 0 || view.contiguous()) {
            return false;
        }
        for (int dim = 0; dim < rank - 1; dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return view.stride(rank - 1) == 1;
    }

    public static void fastTanhBf16ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhBf16ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        short[] input = args.input(0).bfloat16Array();
        short[] output = args.output().bfloat16Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset.offset(i)]);
            output[outputOffset.offset(i)] = TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhBf16ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhBf16ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhBf16ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhBf16SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value)));
        }
    }

    public static void fastTanhBf16SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset.offset(i)) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset.offset(i)) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value)));
        }
    }

    public static void fastTanhBf16SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value)));
        }
    }

    public static void fastTanhBf16SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value)));
        }
    }

    public static void fastTanhBf16SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(FastTranscendentals.fastTanhF32(value)));
        }
    }

    public static void fastTanhF32ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF32(value);
        }
    }

    public static void fastTanhF32ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        float[] input = args.input(0).float32Array();
        float[] output = args.output().float32Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = FastTranscendentals.fastTanhF32(value);
        }
    }

    public static void fastTanhF32ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF32(value);
        }
    }

    public static void fastTanhF32ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF32(value);
        }
    }

    public static void fastTanhF32ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF32(value);
        }
    }

    public static void fastTanhF32SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhF32SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input.get(JAVA_FLOAT, (long) (inputOffset.offset(i)) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset.offset(i)) * Float.BYTES, FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhF32SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhF32SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhF32SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, FastTranscendentals.fastTanhF32(value));
        }
    }

    public static void fastTanhF64ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF64(value);
        }
    }

    public static void fastTanhF64ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        double[] input = args.input(0).float64Array();
        double[] output = args.output().float64Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = FastTranscendentals.fastTanhF64(value);
        }
    }

    public static void fastTanhF64ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF64(value);
        }
    }

    public static void fastTanhF64ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF64(value);
        }
    }

    public static void fastTanhF64ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input[inputOffset];
            output[outputOffset] = FastTranscendentals.fastTanhF64(value);
        }
    }

    public static void fastTanhF64SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, FastTranscendentals.fastTanhF64(value));
        }
    }

    public static void fastTanhF64SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset.offset(i)) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset.offset(i)) * Double.BYTES, FastTranscendentals.fastTanhF64(value));
        }
    }

    public static void fastTanhF64SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, FastTranscendentals.fastTanhF64(value));
        }
    }

    public static void fastTanhF64SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, FastTranscendentals.fastTanhF64(value));
        }
    }

    public static void fastTanhF64SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, FastTranscendentals.fastTanhF64(value));
        }
    }

    public static void bf16ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        float[] inputChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                for (int lane = 0; lane < F32.length(); lane++) {
                    inputChunk[lane] = TensorDTypeOps.fromBFloat16Bits(input[inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + vectorInner + lane : inputBase + i + lane)]);
                }
                FloatVector.fromArray(F32, inputChunk, 0).lanewise(VectorOperators.TANH)
                        .intoArray(outputChunk, 0);
                for (int lane = 0; lane < F32.length(); lane++) {
                    output[outputBase + i + lane] = TensorDTypeOps.toBFloat16Bits(outputChunk[lane]);
                }
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                float value = TensorDTypeOps.fromBFloat16Bits(input[inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + scalarInner : inputBase + i)]);
                output[outputBase + i] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
            }
        }
    }

    public static void bf16ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        float[] inputChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            for (int lane = 0; lane < F32.length(); lane++) {
                inputChunk[lane] = TensorDTypeOps.fromBFloat16Bits(input[inputBase + i + lane]);
            }
            FloatVector.fromArray(F32, inputChunk, 0).lanewise(VectorOperators.TANH)
                    .intoArray(outputChunk, 0);
            for (int lane = 0; lane < F32.length(); lane++) {
                output[outputBase + i + lane] = TensorDTypeOps.toBFloat16Bits(outputChunk[lane]);
            }
        }
        for (; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputBase + i]);
            output[outputBase + i] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        short[] input = args.input(0).bfloat16Array();
        short[] output = args.output().bfloat16Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset.offset(i)]);
            output[outputOffset.offset(i)] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        short[] input = inputView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input[inputOffset]);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value));
        }
    }

    public static void bf16SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        float[] inputChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                for (int lane = 0; lane < F32.length(); lane++) {
                    inputChunk[lane] = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + vectorInner + lane : inputBase + i + lane)) * Short.BYTES));
                }
                FloatVector.fromArray(F32, inputChunk, 0).lanewise(VectorOperators.TANH)
                        .intoArray(outputChunk, 0);
                for (int lane = 0; lane < F32.length(); lane++) {
                    output.set(JAVA_SHORT, (long) (outputBase + i + lane) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(outputChunk[lane]));
                }
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + scalarInner : inputBase + i)) * Short.BYTES));
                output.set(JAVA_SHORT, (long) (outputBase + i) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
            }
        }
    }

    public static void bf16SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void bf16SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        float[] inputChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            for (int lane = 0; lane < F32.length(); lane++) {
                inputChunk[lane] = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputBase + i + lane) * Short.BYTES));
            }
            FloatVector.fromArray(F32, inputChunk, 0).lanewise(VectorOperators.TANH)
                    .intoArray(outputChunk, 0);
            for (int lane = 0; lane < F32.length(); lane++) {
                output.set(JAVA_SHORT, (long) (outputBase + i + lane) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(outputChunk[lane]));
            }
        }
        for (; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputBase + i) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputBase + i) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void bf16SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset.offset(i)) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset.offset(i)) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void bf16SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void bf16SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void bf16SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = TensorDTypeOps.fromBFloat16Bits(input.get(JAVA_SHORT, (long) (inputOffset) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits((float) Math.tanh(value)));
        }
    }

    public static void f32ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                (inputMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, input[inputBase]) : (inputMode == BROADCAST_INNER ? FloatVector.fromArray(F32, input, inputBase + vectorInner) : FloatVector.fromArray(F32, input, inputBase + i))).lanewise(VectorOperators.TANH)
                        .intoArray(output, outputBase + i);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                float value = input[inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + scalarInner : inputBase + i)];
                output[outputBase + i] = (float) Math.tanh(value);
            }
        }
    }

    public static void f32ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input[inputOffset];
            output[outputOffset] = (float) Math.tanh(value);
        }
    }

    public static void f32ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            FloatVector.fromArray(F32, input, inputBase + i).lanewise(VectorOperators.TANH)
                    .intoArray(output, outputBase + i);
        }
        for (; i < endExclusive; i++) {
            float value = input[inputBase + i];
            output[outputBase + i] = (float) Math.tanh(value);
        }
    }

    public static void f32ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        float[] input = args.input(0).float32Array();
        float[] output = args.output().float32Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = (float) Math.tanh(value);
        }
    }

    public static void f32ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input[inputOffset];
            output[outputOffset] = (float) Math.tanh(value);
        }
    }

    public static void f32ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input[inputOffset];
            output[outputOffset] = (float) Math.tanh(value);
        }
    }

    public static void f32ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        float[] input = inputView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input[inputOffset];
            output[outputOffset] = (float) Math.tanh(value);
        }
    }

    public static void f32SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        long inputBase = (long) inputView.storageOffset() * Float.BYTES;
        long outputBase = (long) outputView.storageOffset() * Float.BYTES;
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Float.BYTES;
                (inputMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, input.get(JAVA_FLOAT, inputBase)) : (inputMode == BROADCAST_INNER ? FloatVector.fromMemorySegment(F32, input, inputBase + (long) vectorInner * Float.BYTES, ORDER) : FloatVector.fromMemorySegment(F32, input, inputBase + (long) i * Float.BYTES, ORDER))).lanewise(VectorOperators.TANH)
                        .intoMemorySegment(output, outputOffset, ORDER);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Float.BYTES;
                float value = (inputMode == BROADCAST_SCALAR ? input.get(JAVA_FLOAT, inputBase) : (inputMode == BROADCAST_INNER ? input.get(JAVA_FLOAT, inputBase + (long) scalarInner * Float.BYTES) : input.get(JAVA_FLOAT, inputBase + (long) i * Float.BYTES)));
                output.set(JAVA_FLOAT, outputOffset, (float) Math.tanh(value));
            }
        }
    }

    public static void f32SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, (float) Math.tanh(value));
        }
    }

    public static void f32SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        long inputBase = (long) inputView.storageOffset() * Float.BYTES;
        long outputBase = (long) outputView.storageOffset() * Float.BYTES;
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            long byteIndex = (long) i * Float.BYTES;
            FloatVector.fromMemorySegment(F32, input, inputBase + byteIndex, ORDER).lanewise(VectorOperators.TANH)
                    .intoMemorySegment(output, outputBase + byteIndex, ORDER);
        }
        for (; i < endExclusive; i++) {
            long inputOffset = inputBase + (long) i * Float.BYTES;
            long outputOffset = outputBase + (long) i * Float.BYTES;
            float value = input.get(JAVA_FLOAT, inputOffset);
            output.set(JAVA_FLOAT, outputOffset, (float) Math.tanh(value));
        }
    }

    public static void f32SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            float value = input.get(JAVA_FLOAT, (long) (inputOffset.offset(i)) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset.offset(i)) * Float.BYTES, (float) Math.tanh(value));
        }
    }

    public static void f32SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, (float) Math.tanh(value));
        }
    }

    public static void f32SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, (float) Math.tanh(value));
        }
    }

    public static void f32SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            float value = input.get(JAVA_FLOAT, (long) (inputOffset) * Float.BYTES);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, (float) Math.tanh(value));
        }
    }

    public static void f64ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F64.loopBound(rowEnd - i);
            for (; i < upper; i += F64.length()) {
                int vectorInner = i % innerSize;
                (inputMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, input[inputBase]) : (inputMode == BROADCAST_INNER ? DoubleVector.fromArray(F64, input, inputBase + vectorInner) : DoubleVector.fromArray(F64, input, inputBase + i))).lanewise(VectorOperators.TANH)
                        .intoArray(output, outputBase + i);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                double value = input[inputMode == BROADCAST_SCALAR ? inputBase : (inputMode == BROADCAST_INNER ? inputBase + scalarInner : inputBase + i)];
                output[outputBase + i] = Math.tanh(value);
            }
        }
    }

    public static void f64ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input[inputOffset];
            output[outputOffset] = Math.tanh(value);
        }
    }

    public static void f64ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        int upper = startInclusive + F64.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F64.length()) {
            DoubleVector.fromArray(F64, input, inputBase + i).lanewise(VectorOperators.TANH)
                    .intoArray(output, outputBase + i);
        }
        for (; i < endExclusive; i++) {
            double value = input[inputBase + i];
            output[outputBase + i] = Math.tanh(value);
        }
    }

    public static void f64ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        double[] input = args.input(0).float64Array();
        double[] output = args.output().float64Array();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input[inputOffset.offset(i)];
            output[outputOffset.offset(i)] = Math.tanh(value);
        }
    }

    public static void f64ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input[inputOffset];
            output[outputOffset] = Math.tanh(value);
        }
    }

    public static void f64ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input[inputOffset];
            output[outputOffset] = Math.tanh(value);
        }
    }

    public static void f64ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        double[] input = inputView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input[inputOffset];
            output[outputOffset] = Math.tanh(value);
        }
    }

    public static void f64SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        long inputBase = (long) inputView.storageOffset() * Double.BYTES;
        long outputBase = (long) outputView.storageOffset() * Double.BYTES;
        int inputMode = broadcastVectorMode(inputView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F64.loopBound(rowEnd - i);
            for (; i < upper; i += F64.length()) {
                int vectorInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Double.BYTES;
                (inputMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, input.get(JAVA_DOUBLE, inputBase)) : (inputMode == BROADCAST_INNER ? DoubleVector.fromMemorySegment(F64, input, inputBase + (long) vectorInner * Double.BYTES, ORDER) : DoubleVector.fromMemorySegment(F64, input, inputBase + (long) i * Double.BYTES, ORDER))).lanewise(VectorOperators.TANH)
                        .intoMemorySegment(output, outputOffset, ORDER);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Double.BYTES;
                double value = (inputMode == BROADCAST_SCALAR ? input.get(JAVA_DOUBLE, inputBase) : (inputMode == BROADCAST_INNER ? input.get(JAVA_DOUBLE, inputBase + (long) scalarInner * Double.BYTES) : input.get(JAVA_DOUBLE, inputBase + (long) i * Double.BYTES)));
                output.set(JAVA_DOUBLE, outputOffset, Math.tanh(value));
            }
        }
    }

    public static void f64SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int inputOffset = inputBase + i;
            int outputOffset = outputBase + i;
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, Math.tanh(value));
        }
    }

    public static void f64SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        long inputBase = (long) inputView.storageOffset() * Double.BYTES;
        long outputBase = (long) outputView.storageOffset() * Double.BYTES;
        int upper = startInclusive + F64.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F64.length()) {
            long byteIndex = (long) i * Double.BYTES;
            DoubleVector.fromMemorySegment(F64, input, inputBase + byteIndex, ORDER).lanewise(VectorOperators.TANH)
                    .intoMemorySegment(output, outputBase + byteIndex, ORDER);
        }
        for (; i < endExclusive; i++) {
            long inputOffset = inputBase + (long) i * Double.BYTES;
            long outputOffset = outputBase + (long) i * Double.BYTES;
            double value = input.get(JAVA_DOUBLE, inputOffset);
            output.set(JAVA_DOUBLE, outputOffset, Math.tanh(value));
        }
    }

    public static void f64SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment input = args.input(0).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan inputOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset.offset(i)) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset.offset(i)) * Double.BYTES, Math.tanh(value));
        }
    }

    public static void f64SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, Math.tanh(value));
        }
    }

    public static void f64SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, Math.tanh(value));
        }
    }

    public static void f64SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView inputView = args.input(0);
        Cpu1TensorView outputView = args.output();
        MemorySegment input = inputView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int inputBase = inputView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int inputOffset = inputBase + c0 * inputView.stride(0) + c1 * inputView.stride(1) + c2 * inputView.stride(2) + c3 * inputView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            double value = input.get(JAVA_DOUBLE, (long) (inputOffset) * Double.BYTES);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, Math.tanh(value));
        }
    }
}
