package tuning.candidate.graph;

public enum GraphAutotuneParameter {
    CURRENT_GRAPH_POLICY,
    BACKEND_DISCOVERY_POLICY,
    BACKEND_REQUIREMENT_POLICY,
    OWNERSHIP_PLANNER_POLICY,
    PLANNING_COST_PROFILE,
    PARTITION_OPTIMIZATION_POLICY,
    MEMORY_PLANNING_POLICY,
    CPU_PARTITION_POLICY,
    CPU_FUSION_POLICY,
    RESEARCH_CSE_POLICY,
    RESEARCH_PIECEWISE_LOWERING,
    RESEARCH_MEMORY_LIFETIME
}
