package tuning.candidate.graph;

public enum GraphAutotuneParameter {
    CURRENT_GRAPH_POLICY,
    OFFLOAD_POLICY,
    CPU_REGION_POLICY,
    CPU_FUSION_POLICY,
    ACCELERATOR_REGION_POLICY,
    RESEARCH_METAL_TRANSFER_MODEL,
    RESEARCH_CSE_POLICY,
    RESEARCH_PIECEWISE_LOWERING,
    RESEARCH_MEMORY_LIFETIME
}
