package backend.cpu1.kernels.linalg.attention.backward;

/**
 * Dense scaled-dot-product-attention backward kernels supported by cpu1.
 */
public enum Cpu1AttentionBackwardKernelId {
    SDPA_BACKWARD_DQ_F32_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DQ_F32_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DK_F32_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DK_F32_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DV_F32_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DV_F32_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DQ_F64_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DQ_F64_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DK_F64_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DK_F64_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DV_F64_ARRAY_DENSE_SCALAR,
    SDPA_BACKWARD_DV_F64_ARRAY_DENSE_VECTOR,
    SDPA_BACKWARD_DQ_F32_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DQ_F32_SEGMENT_DENSE_VECTOR,
    SDPA_BACKWARD_DK_F32_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DK_F32_SEGMENT_DENSE_VECTOR,
    SDPA_BACKWARD_DV_F32_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DV_F32_SEGMENT_DENSE_VECTOR,
    SDPA_BACKWARD_DQ_F64_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DQ_F64_SEGMENT_DENSE_VECTOR,
    SDPA_BACKWARD_DK_F64_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DK_F64_SEGMENT_DENSE_VECTOR,
    SDPA_BACKWARD_DV_F64_SEGMENT_DENSE_SCALAR,
    SDPA_BACKWARD_DV_F64_SEGMENT_DENSE_VECTOR
}
