package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.pho001.synaptik.backend.cpu.internal.cache.CpuKernelSpecialization.CarrierAccess;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuArgExtremaLoweringTest;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionAnalysisInputs;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparer;
import io.github.pho001.synaptik.model.datatype.DataType;
import io.github.pho001.synaptik.model.datatype.ScalarValue;
import io.github.pho001.synaptik.model.graph.GraphValue;
import io.github.pho001.synaptik.model.layout.LayoutDescriptor;
import io.github.pho001.synaptik.model.operation.reduction.AggregateReductionKind;
import io.github.pho001.synaptik.model.operation.reduction.ArgExtremaTiePolicy;
import io.github.pho001.synaptik.model.shape.Shape;
import io.github.pho001.synaptik.model.tensor.TensorDescriptor;
import io.github.pho001.synaptik.planning.memory.LogicalMemoryRequirement;
import io.github.pho001.synaptik.prepare.analysis.PrepareContext;
import java.lang.foreign.MemorySegment;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;

/** Executes every generated ARG_MIN and ARG_MAX inventory owner against a local scalar oracle. */
class CpuArgExtremaSemanticClosureTest {
    private static final List<DataType> INPUT_TYPES = List.of(DataType.FLOAT64, DataType.FLOAT32,
            DataType.BFLOAT16, DataType.INT64, DataType.INT32);
    private static final Shape INPUT = Shape.of(2, 3);
    private static final CpuPartitionAnalysisInputs.MaterializationPolicy MATERIALIZATION =
            new CpuPartitionAnalysisInputs.MaterializationPolicy(true, 0, 1, 20, 1, 3,
                    1_000_000, 1, 1);

    @Test void everyArgExtremaInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle()
            throws Throwable {
        Set<String> owners = new TreeSet<>();
        int min = 0;
        int max = 0;
        for (AggregateReductionKind kind : List.of(AggregateReductionKind.ARG_MIN,
                AggregateReductionKind.ARG_MAX)) for (DataType type : INPUT_TYPES)
            for (ArgExtremaTiePolicy tie : ArgExtremaTiePolicy.values())
                for (boolean keep : List.of(false, true)) for (int axis : List.of(0, 1))
                    for (Request request : Request.values()) {
                        Fixture fixture = new Fixture(kind, type, tie, keep, axis, request);
                        assertTrue(owners.add(fixture.owner()), "duplicate semantic witness " + fixture);
                        invokeAndCompare(fixture);
                        if (kind == AggregateReductionKind.ARG_MIN) min++; else max++;
                    }
        assertEquals(200, min, "ARG_MIN direct generated invocations");
        assertEquals(200, max, "ARG_MAX direct generated invocations");
        assertEquals(400, owners.size(), "one exact generated definition/invocation per arg-extrema owner");
        assertEquals(inventoryOwners(), owners, "complete non-projecting arg-extrema inventory-owner join");
    }

    private static void invokeAndCompare(Fixture fixture) throws Throwable {
        PrepareContext<CpuPartitionAnalysisInputs> context = configure(base(fixture), fixture.request());
        var plan = new CpuPartitionPreparer().analyze(context).plan();
        var route = plan.units().getFirst().portablePlan();
        assertEquals(0, plan.materializations().size(), fixture + " materialization remains unselected");
        assertEquals(DataType.INT64, route.specialization().boundaryDataTypes().getLast(),
                fixture + " logical index output width");
        var geometry = plan.argExtremaGeometry().orElseThrow();
        assertEquals(fixture.axis(), geometry.axis());
        assertEquals(fixture.keep(), geometry.keepDimensions());
        assertEquals(fixture.tie(), geometry.tiePolicy());
        var generator = new CpuClassFileKernelGenerator();
        byte[] first = generator.generateClassBytes(route.specialization(), route.kernelIr());
        assertArrayEquals(first, generator.generateClassBytes(route.specialization(), route.kernelIr()),
                fixture + " deterministic generated bytes");
        var artifact = generator.defineClassBytes(route.specialization(), first);

        Storage input = new Storage(fixture.type(), route.specialization().carrierPattern().getFirst(), 32);
        Storage output = new Storage(DataType.INT64, route.specialization().carrierPattern().getLast(), 32);
        fillInput(input, context.values().getFirst().descriptor());
        long[] beforeInput = input.rawBits();
        output.fill(-91);
        long[] expected = output.longSnapshot();
        long start = 1;
        long end = geometry.outputCount();
        oracle(fixture, context, input, expected, start, end);
        assertExpectedPolicy(fixture, context, expected, start, end);
        artifact.entryPoint().invokeWithArguments(input.argument(), output.argument(),
                geometry.pack(new long[] {0, 0}), start, end);
        assertArrayEquals(expected, output.longSnapshot(), fixture + " independent oracle / untouched range");
        assertArrayEquals(beforeInput, input.rawBits(), fixture + " input mutation");
        assertEquals(-91L, output.longSnapshot()[(int) offset(
                context.values().getLast().descriptor().layout().orElseThrow(),
                coordinates(0, context.values().getLast().descriptor().shape().toLongArray()))],
                fixture + " unselected output remains untouched");
    }

    private static PrepareContext<CpuPartitionAnalysisInputs> base(Fixture fixture) {
        return CpuArgExtremaLoweringTest.context(fixture.kind(), fixture.type(), INPUT,
                fixture.axis(), fixture.keep(), fixture.tie());
    }

    private static PrepareContext<CpuPartitionAnalysisInputs> configure(
            PrepareContext<CpuPartitionAnalysisInputs> base, Request request) {
        List<GraphValue> values = new ArrayList<>();
        List<LogicalMemoryRequirement> memory = new ArrayList<>();
        for (int i = 0; i < base.values().size(); i++) {
            TensorDescriptor descriptor = base.values().get(i).descriptor();
            if (request.general() && descriptor.shape().rank() != 0) {
                long[] strides = descriptor.layout().orElseThrow().strides();
                for (int axis = 0; axis < strides.length; axis++) strides[axis] *= 2;
                descriptor = new TensorDescriptor(descriptor.dataType(), descriptor.shape(),
                        Optional.of(LayoutDescriptor.of(descriptor.shape(), strides, 1, true)), false);
            }
            values.add(new GraphValue(base.values().get(i).id(), descriptor));
            var requirement = base.memoryRequirements().get(i);
            memory.add(new LogicalMemoryRequirement(requirement.valueId(), descriptor,
                    requirement.producerPartition(), requirement.consumerPartitions(), requirement.graphOutput()));
        }
        List<CarrierAccess> carriers = new ArrayList<>();
        for (int i = 0; i < values.size(); i++) carriers.add(request.segment()
                || request.mixed() && i % 2 == 1 ? CarrierAccess.MEMORY_SEGMENT
                : CpuGeneratedDirectEvidenceClosureTest.heapCarrier(values.get(i).descriptor().dataType()));
        return new PrepareContext<>(base.partition(), base.nodes(), values, memory, base.constants(),
                new CpuPartitionAnalysisInputs(false, carriers, request.execution(), request.materialization()
                        ? MATERIALIZATION : CpuPartitionAnalysisInputs.MaterializationPolicy.DISABLED));
    }

    /* Test-local clean Java oracle: it neither lowers nor calls a production reference kernel. */
    private static void oracle(Fixture fixture, PrepareContext<?> context, Storage input,
            long[] expected, long start, long end) {
        LayoutDescriptor in = context.values().getFirst().descriptor().layout().orElseThrow();
        LayoutDescriptor out = context.values().getLast().descriptor().layout().orElseThrow();
        long[] inputShape = INPUT.toLongArray();
        long[] outputShape = context.values().getLast().descriptor().shape().toLongArray();
        for (long cell = start; cell < end; cell++) {
            long[] outCoordinate = coordinates(cell, outputShape);
            long[] coordinate = new long[inputShape.length];
            for (int source = 0, target = 0; source < coordinate.length; source++) {
                if (source == fixture.axis()) {
                    if (fixture.keep()) target++;
                } else coordinate[source] = outCoordinate[target++];
            }
            int best = 0;
            coordinate[fixture.axis()] = 0;
            double bestValue = input.get(offset(in, coordinate));
            for (int candidate = 1; candidate < inputShape[fixture.axis()]; candidate++) {
                coordinate[fixture.axis()] = candidate;
                double value = input.get(offset(in, coordinate));
                if (select(fixture.kind(), fixture.tie(), value, bestValue)) {
                    best = candidate;
                    bestValue = value;
                }
            }
            expected[(int) offset(out, outCoordinate)] = best;
        }
    }

    private static boolean select(AggregateReductionKind kind, ArgExtremaTiePolicy tie,
            double candidate, double best) {
        if (Double.isNaN(candidate)) return tie == ArgExtremaTiePolicy.LAST_INDEX || !Double.isNaN(best);
        if (Double.isNaN(best)) return false;
        int comparison = Double.compare(candidate, best);
        return kind == AggregateReductionKind.ARG_MIN ? comparison < 0
                || comparison == 0 && tie == ArgExtremaTiePolicy.LAST_INDEX
                : comparison > 0 || comparison == 0 && tie == ArgExtremaTiePolicy.LAST_INDEX;
    }

    /* A compact, value-level policy check prevents the local address oracle from becoming tautological. */
    private static void assertExpectedPolicy(Fixture fixture, PrepareContext<?> context, long[] expected,
            long start, long end) {
        LayoutDescriptor out = context.values().getLast().descriptor().layout().orElseThrow();
        long[] shape = context.values().getLast().descriptor().shape().toLongArray();
        for (long cell = start; cell < end; cell++) {
            long actual = expected[(int) offset(out, coordinates(cell, shape))];
            assertEquals(expectedIndex(fixture, cell), actual,
                    fixture + " independent tie/NaN/signed-zero policy oracle");
        }
    }

    private static long expectedIndex(Fixture fixture, long outputCell) {
        if (fixture.type().isFloating()) {
            if (fixture.axis() == 1) return 1; // selected row contains a represented NaN at index one.
            if (outputCell == 1) return fixture.tie() == ArgExtremaTiePolicy.FIRST_INDEX ? 0 : 1;
            return fixture.kind() == AggregateReductionKind.ARG_MIN ? 0 : 1; // -0.0 versus +0.0
        }
        if (fixture.axis() == 1) {
            if (fixture.kind() == AggregateReductionKind.ARG_MIN) return 1;
            return fixture.tie() == ArgExtremaTiePolicy.FIRST_INDEX ? 0 : 2;
        }
        if (outputCell == 1) return fixture.tie() == ArgExtremaTiePolicy.FIRST_INDEX ? 0 : 1;
        return fixture.kind() == AggregateReductionKind.ARG_MIN ? 0 : 1;
    }

    private static void fillInput(Storage input, TensorDescriptor descriptor) {
        // The selected non-empty ranges jointly witness NaN priority, signed-zero ordering,
        // first/last equal-NaN ties, signed integral extrema, and ordinary equal-value ties.
        double[] values = input.type.isFloating()
                ? new double[] {1.0, Double.NaN, -0.0, 0.0, Double.NaN, 0.0}
                : new double[] {1.0, -7.0, input.type == DataType.INT32
                        ? Integer.MIN_VALUE : Long.MIN_VALUE, input.type == DataType.INT32
                                ? Integer.MAX_VALUE : Long.MAX_VALUE, -7.0,
                        input.type == DataType.INT32 ? Integer.MAX_VALUE : Long.MAX_VALUE};
        LayoutDescriptor layout = descriptor.layout().orElseThrow();
        for (int ordinal = 0; ordinal < values.length; ordinal++) input.set(offset(layout, INPUT,
                ordinal), values[ordinal]);
    }

    private static long offset(LayoutDescriptor layout, Shape shape, int ordinal) {
        return offset(layout, coordinates(ordinal, shape.toLongArray()));
    }
    private static long offset(LayoutDescriptor layout, long[] coordinate) {
        long address = layout.storageOffset(); long[] strides = layout.strides();
        for (int axis = 0; axis < coordinate.length; axis++) address += coordinate[axis] * strides[axis];
        return address;
    }
    private static long[] coordinates(long ordinal, long[] shape) {
        long[] result = new long[shape.length];
        for (int axis = shape.length - 1; axis >= 0; axis--) { result[axis] = ordinal % shape[axis]; ordinal /= shape[axis]; }
        return result;
    }

    private static Set<String> inventoryOwners() throws Exception {
        try (var stream = CpuArgExtremaSemanticClosureTest.class.getResourceAsStream(
                "/io/github/pho001/synaptik/backend/cpu/internal/codegen/emit/generated-coverage-inventory.tsv")) {
            assertTrue(stream != null, "inventory resource");
            Set<String> result = new TreeSet<>();
            for (String line : new String(stream.readAllBytes(), StandardCharsets.UTF_8).split("\\n", -1)) {
                String[] fields = line.split("\\t", -1);
                if (fields.length == 27 && fields[0].startsWith("specialized:")
                        && (fields[2].equals("ARG_MIN") || fields[2].equals("ARG_MAX")))
                    assertTrue(result.add(fields[0]), "duplicate inventory owner " + fields[0]);
            }
            assertEquals(200, result.stream().filter(value -> value.startsWith("specialized:arg/ARG_MIN/")).count());
            assertEquals(200, result.stream().filter(value -> value.startsWith("specialized:arg/ARG_MAX/")).count());
            return result;
        }
    }

    private enum Request {
        HEAP_CONTIGUOUS_SCALAR(false, false, false, false, CpuGeneratedDirectEvidenceClosureTest.scalar(1)),
        SEGMENT_CONTIGUOUS_VECTOR(true, false, false, false, CpuGeneratedDirectEvidenceClosureTest.vector(1)),
        MIXED_GENERAL_PARALLEL_VECTOR(false, true, true, false, CpuGeneratedDirectEvidenceClosureTest.vector(4)),
        HEAP_GENERAL_PARALLEL_SCALAR(false, false, true, false, CpuGeneratedDirectEvidenceClosureTest.scalar(4)),
        HEAP_GENERAL_MATERIALIZATION(false, false, true, true, CpuGeneratedDirectEvidenceClosureTest.scalar(1));
        private final boolean segment, mixed, general, materialization;
        private final CpuPartitionAnalysisInputs.PortableExecutionConfig execution;
        Request(boolean segment, boolean mixed, boolean general, boolean materialization,
                CpuPartitionAnalysisInputs.PortableExecutionConfig execution) {
            this.segment = segment; this.mixed = mixed; this.general = general;
            this.materialization = materialization; this.execution = execution;
        }
        boolean segment() { return segment; } boolean mixed() { return mixed; }
        boolean general() { return general; } boolean materialization() { return materialization; }
        CpuPartitionAnalysisInputs.PortableExecutionConfig execution() { return execution; }
    }

    private record Fixture(AggregateReductionKind kind, DataType type, ArgExtremaTiePolicy tie,
            boolean keep, int axis, Request request) {
        String owner() { return "specialized:arg/" + kind + '/' + type + '/' + tie + '/' + keep + '/'
                + axis + '/' + request; }
    }

    private static final class Storage {
        private final DataType type; private final CarrierAccess carrier; private final Object heap;
        private final MemorySegment segment;
        Storage(DataType type, CarrierAccess carrier, int capacity) {
            this.type = type; this.carrier = carrier;
            heap = switch (type) { case FLOAT64 -> new double[capacity]; case FLOAT32 -> new float[capacity];
                case BFLOAT16 -> new short[capacity]; case INT64 -> new long[capacity]; case INT32 -> new int[capacity];
                default -> throw new AssertionError(type); };
            segment = switch (type) { case FLOAT64 -> MemorySegment.ofArray((double[]) heap); case FLOAT32 -> MemorySegment.ofArray((float[]) heap);
                case BFLOAT16 -> MemorySegment.ofArray((short[]) heap); case INT64 -> MemorySegment.ofArray((long[]) heap);
                case INT32 -> MemorySegment.ofArray((int[]) heap); default -> throw new AssertionError(type); };
        }
        Object argument() { return carrier == CarrierAccess.MEMORY_SEGMENT ? segment : heap; }
        void fill(long value) { Arrays.fill((long[]) heap, value); }
        void set(long index, double value) { switch (type) { case FLOAT64 -> ((double[]) heap)[(int) index] = value;
            case FLOAT32 -> ((float[]) heap)[(int) index] = (float) value; case BFLOAT16 -> ((short[]) heap)[(int) index] = ScalarValue.bfloat16((float) value).bfloat16Bits();
            case INT64 -> ((long[]) heap)[(int) index] = (long) value; case INT32 -> ((int[]) heap)[(int) index] = (int) value; default -> throw new AssertionError(type); } }
        double get(long index) { return switch (type) { case FLOAT64 -> ((double[]) heap)[(int) index]; case FLOAT32 -> ((float[]) heap)[(int) index];
            case BFLOAT16 -> Float.intBitsToFloat((((short[]) heap)[(int) index] & 0xffff) << 16); case INT64 -> ((long[]) heap)[(int) index]; case INT32 -> ((int[]) heap)[(int) index]; default -> throw new AssertionError(type); }; }
        long[] longSnapshot() { return ((long[]) heap).clone(); }
        long[] rawBits() { long[] result = new long[java.lang.reflect.Array.getLength(heap)]; for (int i = 0; i < result.length; i++) result[i] = switch (type) { case FLOAT64 -> Double.doubleToRawLongBits(((double[]) heap)[i]); case FLOAT32 -> Float.floatToRawIntBits(((float[]) heap)[i]); case BFLOAT16 -> ((short[]) heap)[i] & 0xffffL; case INT64 -> ((long[]) heap)[i]; case INT32 -> ((int[]) heap)[i]; default -> throw new AssertionError(type); }; return result; }
    }
}
