package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import static org.junit.jupiter.api.Assertions.*;

import io.github.pho001.synaptik.backend.cpu.internal.cache.CpuKernelSpecialization.CarrierAccess;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuAttentionLowering;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionAnalysisInputs;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparer;
import io.github.pho001.synaptik.model.datatype.DataType;
import io.github.pho001.synaptik.model.datatype.ScalarValue;
import io.github.pho001.synaptik.model.graph.GraphValue;
import io.github.pho001.synaptik.model.layout.LayoutDescriptor;
import io.github.pho001.synaptik.model.tensor.TensorDescriptor;
import io.github.pho001.synaptik.planning.memory.LogicalMemoryRequirement;
import io.github.pho001.synaptik.prepare.analysis.PrepareContext;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.jupiter.api.Test;

/** Executes every exact generated attention inventory owner against a test-local stable oracle. */
class CpuAttentionSemanticClosureTest {
    private static final List<DataType> FLOATING = List.of(DataType.FLOAT64, DataType.FLOAT32, DataType.BFLOAT16);
    private static final CpuPartitionAnalysisInputs.MaterializationPolicy MATERIALIZATION =
            new CpuPartitionAnalysisInputs.MaterializationPolicy(true, 0, 1, 20, 1, 3, 1_000_000, 1, 1);

    @Test void everyAttentionInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle() throws Throwable {
        int raw = 0; Set<String> owners = new TreeSet<>();
        for (var q : FLOATING) for (var k : FLOATING) for (var v : FLOATING)
            for (boolean mask : List.of(false, true)) for (boolean causal : List.of(false, true))
                for (boolean weights : List.of(false, true)) for (boolean scale : List.of(false, true))
                    for (var roles : CpuSpecializedGeneratedMatrixTest.attentionRoles(mask, q, k, v)) for (var request : Request.values()) {
                        Fixture fixture = new Fixture(q, k, v, mask, causal, weights, scale, roles, request);
                        assertTrue(owners.add(fixture.owner()), "duplicate semantic witness " + fixture);
                        invokeAndCompare(fixture); raw++;
                    }
        assertEquals(4560, raw, "one definition and invocation per attention inventory row");
        assertEquals(inventoryOwners(), owners, "complete non-projecting attention inventory-owner join");
    }

    private static void invokeAndCompare(Fixture f) throws Throwable {
        var context = configure(CpuSpecializedGeneratedMatrixTest.attentionContext(f.q, f.k, f.v, f.mask,
                f.causal, f.weights, f.explicitScale, f.roles), f.request());
        var plan = new CpuPartitionPreparer().analyze(context).plan();
        var unit = plan.units().getFirst(); var route = unit.portablePlan();
        assertEquals(io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparationPlan.ExecutionStrategy.Compute.SCALAR,
                unit.executionStrategy().compute(), f + " attention never selects a vector body");
        assertEquals(f.request.parallel
                        ? io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparationPlan.ExecutionStrategy.Orchestration.PARALLEL
                        : io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparationPlan.ExecutionStrategy.Orchestration.SINGLE_THREAD,
                unit.executionStrategy().orchestration(), f + " requested execution selects its actual attention orchestration");
        assertEquals(0, plan.materializations().size(), f + " attention remains direct under every request");
        assertTrue(route.portableKernelIr() instanceof io.github.pho001.synaptik.backend.cpu.internal.ir.CpuAttentionIr, f.toString());
        var geometry = unit.attentionGeometry().orElseThrow();
        var generator = new CpuClassFileKernelGenerator();
        byte[] first = generator.generateClassBytes(route.specialization(), route.kernelIr());
        assertArrayEquals(first, generator.generateClassBytes(route.specialization(), route.kernelIr()),
                f + " deterministic generated bytes");
        var artifact = generator.defineClassBytes(route.specialization(), first);
        List<Storage> storage = new ArrayList<>();
        for (int i = 0; i < route.specialization().boundaryDataTypes().size(); i++) storage.add(new Storage(
                route.specialization().boundaryDataTypes().get(i), route.specialization().carrierPattern().get(i)));
        int inputs = geometry.uniqueInputCount();
        fillInputs(context, storage, inputs);
        for (int i = inputs; i < storage.size(); i++) storage.get(i).fill(-91.25d);
        List<double[]> before = storage.subList(0, inputs).stream().map(Storage::snapshot).toList();
        List<double[]> expected = storage.subList(inputs, storage.size()).stream().map(Storage::snapshot).toList();
        oracle(geometry, storage, expected, f.causal);
        Object[] boundaries = storage.stream().map(Storage::argument).toArray();
        long work = unit.elementCount();
        int ranges = Math.max(1, plan.selectedRangeCount());
        assertEquals(f.request.parallel, ranges > 1, f + " selected worker ranges");
        try (Arena arena = Arena.ofConfined()) {
            long start = 0;
            for (int range = 0; range < ranges; range++) {
                long end = (range + 1) * work / ranges;
                if (end > start) entry(artifact, boundaries, arena.allocate(Math.max(1, geometry.scratchSliceBytes()), 8),
                        geometry.pack(new long[storage.size()]), start, end);
                start = end;
            }
        }
        for (int i = 0; i < expected.size(); i++) assertStorage(expected.get(i), storage.get(inputs + i), f);
        for (int i = 0; i < inputs; i++) assertArrayEquals(before.get(i), storage.get(i).snapshot(), f + " input mutation " + i);
    }

    private static void entry(CpuGeneratedKernel artifact, Object[] boundaries, MemorySegment scratch,
            long[] geometry, long start, long end) throws Throwable {
        Object[] arguments = Arrays.copyOf(boundaries, boundaries.length + 4);
        arguments[boundaries.length] = scratch; arguments[boundaries.length + 1] = geometry;
        arguments[boundaries.length + 2] = start; arguments[boundaries.length + 3] = end;
        artifact.entryPoint().invokeWithArguments(arguments);
    }

    private static PrepareContext<CpuPartitionAnalysisInputs> configure(PrepareContext<CpuPartitionAnalysisInputs> base,
            Request request) {
        List<GraphValue> values = new ArrayList<>(); List<LogicalMemoryRequirement> memory = new ArrayList<>();
        for (int i = 0; i < base.values().size(); i++) {
            TensorDescriptor descriptor = base.values().get(i).descriptor();
            if (request.general && descriptor.shape().rank() != 0) {
                long[] strides = descriptor.layout().orElseThrow().strides();
                for (int axis = 0; axis < strides.length; axis++) strides[axis] *= 2;
                descriptor = new TensorDescriptor(descriptor.dataType(), descriptor.shape(),
                        Optional.of(LayoutDescriptor.of(descriptor.shape(), strides, 1, true)), false);
            }
            values.add(new GraphValue(base.values().get(i).id(), descriptor)); var r = base.memoryRequirements().get(i);
            memory.add(new LogicalMemoryRequirement(r.valueId(), descriptor, r.producerPartition(), r.consumerPartitions(), r.graphOutput()));
        }
        List<CarrierAccess> carriers = new ArrayList<>();
        for (int i = 0; i < values.size(); i++) carriers.add(request.segment || request.mixed && i % 2 == 1
                ? CarrierAccess.MEMORY_SEGMENT : CpuGeneratedDirectEvidenceClosureTest.heapCarrier(values.get(i).descriptor().dataType()));
        return new PrepareContext<>(base.partition(), base.nodes(), values, memory, base.constants(),
                new CpuPartitionAnalysisInputs(false, carriers, request.execution,
                        request.materialization ? MATERIALIZATION : CpuPartitionAnalysisInputs.MaterializationPolicy.DISABLED));
    }

    private static void fillInputs(PrepareContext<CpuPartitionAnalysisInputs> context, List<Storage> storage, int inputs) {
        for (int i = 0; i < inputs; i++) {
            var inputId = context.nodes().getFirst().inputs().stream().distinct().toList().get(i);
            TensorDescriptor d = context.values().stream().filter(v -> v.id().equals(inputId))
                    .findFirst().orElseThrow().descriptor();
            long count = elements(d.shape()); LayoutDescriptor l = d.layout().orElseThrow();
            for (long logical = 0; logical < count; logical++) storage.get(i).set(offset(l, d.shape(), logical),
                    d.dataType() == DataType.BOOL ? (logical % 3 == 0 ? 0 : 1) : .125 + i * .25 + logical * .0625);
        }
    }

    /* Independent stable scalar oracle: no lowering and no production/reference-kernel call. */
    private static void oracle(CpuAttentionLowering.Geometry g, List<Storage> s, List<double[]> expected, boolean causal) {
        int q = g.roleBoundaryPositions().get(0), k = g.roleBoundaryPositions().get(1), v = g.roleBoundaryPositions().get(2);
        int mask = g.mask().isPresent() ? g.roleBoundaryPositions().get(3) : -1;
        int out = g.uniqueInputCount(), weights = g.outputCount() == 2 ? out + 1 : -1;
        long[] batchExtents = g.batchExtents(); int rank = batchExtents.length + 2;
        for (long row = 0; row < g.rowCount(); row++) {
            long qi = row % g.queryLength(), batch = row / g.queryLength(); long[] coordinate = new long[batchExtents.length];
            for (int a = coordinate.length - 1; a >= 0; a--) { coordinate[a] = batch % batchExtents[a]; batch /= batchExtents[a]; }
            double[] score = new double[(int) g.keyLength()]; boolean[] eligible = new boolean[(int) g.keyLength()];
            boolean anyNan = false, allNeg = true; int positive = 0, count = 0;
            for (int j = 0; j < score.length; j++) {
                boolean ok = (!causal || j <= qi) && (mask < 0 || s.get(mask).get(address(g.mask().orElseThrow(), coordinate, qi, j)) != 0);
                eligible[j] = ok; if (!ok) continue; count++; double dot = 0;
                for (int e = 0; e < g.embedding(); e++) {
                    double left = narrow(g.resultType(), s.get(q).get(address(g.query().orElseThrow(), coordinate, qi, e)));
                    double right = narrow(g.resultType(), s.get(k).get(address(g.key().orElseThrow(), coordinate, j, e)));
                    dot = narrow(g.resultType(), dot + narrow(g.resultType(), left * right));
                }
                score[j] = narrow(g.resultType(), dot * narrow(g.resultType(), g.scale()));
                anyNan |= Double.isNaN(score[j]); allNeg &= score[j] == Double.NEGATIVE_INFINITY;
                if (score[j] == Double.POSITIVE_INFINITY) positive++;
            }
            double[] w = new double[score.length];
            if (count != 0 && !allNeg) {
                if (anyNan) {
                    for (int index = 0; index < w.length; index++) if (eligible[index]) w[index] = Double.NaN;
                } else if (positive != 0) {
                    for (int index = 0; index < w.length; index++) if (eligible[index] && score[index] == Double.POSITIVE_INFINITY) w[index] = narrow(g.resultType(), 1d / positive);
                } else {
                    double max = Double.NEGATIVE_INFINITY; for (int index = 0; index < w.length; index++) if (eligible[index]) max = Math.max(max, score[index]);
                    double sum = 0; for (int index = 0; index < w.length; index++) if (eligible[index]) { w[index] = narrow(g.resultType(), StrictMath.exp(score[index] - max)); sum = narrow(g.resultType(), sum + w[index]); }
                    for (int index = 0; index < w.length; index++) if (eligible[index]) w[index] = narrow(g.resultType(), w[index] / sum);
                }
            }
            for (int j = 0; j < w.length; j++) if (weights >= 0) expected.get(1)[(int) address(g.weights().orElseThrow(), coordinate, qi, j)] = quantize(g.resultType(), w[j]);
            for (int ev = 0; ev < g.valueEmbedding(); ev++) { double sum = 0;
                if (count != 0 && !allNeg) for (int j = 0; j < w.length; j++) if (eligible[j]) {
                    double value = narrow(g.resultType(), s.get(v).get(address(g.value().orElseThrow(), coordinate, j, ev)));
                    sum = narrow(g.resultType(), sum + narrow(g.resultType(), w[j] * value));
                }
                expected.get(0)[(int) address(g.output(), coordinate, qi, ev)] = quantize(g.resultType(), sum); }
        }
    }

    private static long address(CpuAttentionLowering.NormalizedLayout l, long[] batch, long a, long b) {
        long result = l.offset(); long[] strides = l.strides(); for (int i = 0; i < batch.length; i++) result += batch[i] * strides[i];
        return result + a * strides[strides.length - 2] + b * strides[strides.length - 1];
    }
    private static double narrow(DataType t, double x) { return t == DataType.FLOAT64 ? x : (float) x; }
    private static double quantize(DataType t, double x) { return t == DataType.BFLOAT16 ? Float.intBitsToFloat((ScalarValue.bfloat16((float) x).bfloat16Bits() & 0xffff) << 16) : narrow(t, x); }
    private static long offset(LayoutDescriptor l, io.github.pho001.synaptik.model.shape.Shape shape, long logical) { long r = l.storageOffset(); long[] d = shape.toLongArray(), st = l.strides(); for (int i = d.length - 1; i >= 0; i--) { r += (logical % d[i]) * st[i]; logical /= d[i]; } return r; }
    private static long elements(io.github.pho001.synaptik.model.shape.Shape shape) { long result = 1; for (long x : shape.toLongArray()) result *= x; return result; }
    private static void assertStorage(double[] expected, Storage actual, Fixture f) { for (int i = 0; i < expected.length; i++) assertEquals(expected[i], actual.get(i), actual.type == DataType.BFLOAT16 ? .02 : actual.type == DataType.FLOAT32 ? 2e-5 : 0, f + " physical " + i); }
    private static Set<String> inventoryOwners() throws Exception { try (var stream = CpuAttentionSemanticClosureTest.class.getResourceAsStream("/io/github/pho001/synaptik/backend/cpu/internal/codegen/emit/generated-coverage-inventory.tsv")) { assertNotNull(stream); Set<String> result = new TreeSet<>(); for (String line : new String(stream.readAllBytes(), StandardCharsets.UTF_8).split("\\n")) { String[] fields = line.split("\\t", -1); if (fields.length == 27 && fields[2].equals("SCALED_DOT_PRODUCT_ATTENTION")) assertTrue(result.add(fields[0]), "duplicate inventory owner " + fields[0]); } assertEquals(4560, result.size()); return result; } }

    private enum Request {
        HEAP_CONTIGUOUS_SCALAR(false, false, false, false, CpuGeneratedDirectEvidenceClosureTest.scalar(1)),
        SEGMENT_CONTIGUOUS_VECTOR(true, false, false, false, CpuGeneratedDirectEvidenceClosureTest.vector(1)),
        MIXED_GENERAL_PARALLEL_VECTOR(false, true, true, false, CpuGeneratedDirectEvidenceClosureTest.vector(4)),
        HEAP_GENERAL_PARALLEL_SCALAR(false, false, true, false, CpuGeneratedDirectEvidenceClosureTest.scalar(4)),
        HEAP_GENERAL_MATERIALIZATION(false, false, true, true, CpuGeneratedDirectEvidenceClosureTest.scalar(1));
        final boolean segment, mixed, general, materialization, parallel; final CpuPartitionAnalysisInputs.PortableExecutionConfig execution;
        Request(boolean segment, boolean mixed, boolean general, boolean materialization, CpuPartitionAnalysisInputs.PortableExecutionConfig execution) { this.segment = segment; this.mixed = mixed; this.general = general; this.materialization = materialization; this.execution = execution; this.parallel = execution.availableParallelism() > 1; }
    }
    private record Fixture(DataType q, DataType k, DataType v, boolean mask, boolean causal, boolean weights, boolean explicitScale, List<Integer> roles, Request request) {
        String owner() { return "specialized:attention/" + q + '/' + k + '/' + v + "/mask=" + mask + "/causal=" + causal + "/weights=" + weights + "/scale=" + explicitScale + "/roles=" + roles + '/' + request; }
    }
    private static final class Storage {
        final DataType type; final CarrierAccess carrier; final Object heap; final MemorySegment segment;
        Storage(DataType type, CarrierAccess carrier) { this.type = type; this.carrier = carrier; heap = switch (type) { case FLOAT64 -> new double[256]; case FLOAT32 -> new float[256]; case BFLOAT16 -> new short[256]; case BOOL -> new byte[256]; default -> throw new AssertionError(type); }; segment = switch (type) { case FLOAT64 -> MemorySegment.ofArray((double[]) heap); case FLOAT32 -> MemorySegment.ofArray((float[]) heap); case BFLOAT16 -> MemorySegment.ofArray((short[]) heap); case BOOL -> MemorySegment.ofArray((byte[]) heap); default -> throw new AssertionError(type); }; }
        Object argument() { return carrier == CarrierAccess.MEMORY_SEGMENT ? segment : heap; }
        void fill(double x) { for (int i = 0; i < 256; i++) set(i, x); }
        void set(long i, double x) { switch (type) { case FLOAT64 -> ((double[]) heap)[(int) i] = x; case FLOAT32 -> ((float[]) heap)[(int) i] = (float) x; case BFLOAT16 -> ((short[]) heap)[(int) i] = ScalarValue.bfloat16((float) x).bfloat16Bits(); case BOOL -> ((byte[]) heap)[(int) i] = (byte) x; default -> throw new AssertionError(type); } }
        double get(long i) { return switch (type) { case FLOAT64 -> ((double[]) heap)[(int) i]; case FLOAT32 -> ((float[]) heap)[(int) i]; case BFLOAT16 -> Float.intBitsToFloat((((short[]) heap)[(int) i] & 0xffff) << 16); case BOOL -> ((byte[]) heap)[(int) i]; default -> throw new AssertionError(type); }; }
        double[] snapshot() { double[] r = new double[256]; for (int i = 0; i < r.length; i++) r[i] = get(i); return r; }
    }
}
