package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;
import static org.junit.jupiter.api.Assertions.*;
import io.github.pho001.synaptik.backend.cpu.internal.cache.CpuKernelSpecialization.CarrierAccess;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuBatchNormTrainingLoweringTest;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.*;
import io.github.pho001.synaptik.prepare.analysis.PrepareContext;
import java.lang.classfile.ClassFile;
import java.lang.classfile.constantpool.MemberRefEntry;
import java.lang.foreign.Arena;
import java.util.*;
import org.junit.jupiter.api.Test;
class CpuBatchNormTrainingGeneratedKernelTest {
 @Test void emitsAndExecutesDirectFiveOutputFloatBody() throws Throwable {var base=CpuBatchNormTrainingLoweringTest.context(io.github.pho001.synaptik.model.shape.Shape.of(1,1,3),1);var inputs=new CpuPartitionAnalysisInputs(false,Collections.nCopies(10,CarrierAccess.FLOAT_ARRAY));var context=new PrepareContext<>(base.partition(),base.nodes(),base.values(),base.memoryRequirements(),base.constants(),inputs);var plan=new CpuPartitionPreparer().analyze(context).plan();var route=plan.units().getFirst().portablePlan();var generator=new CpuClassFileKernelGenerator();byte[] bytes=generator.generateClassBytes(route.specialization(),route.kernelIr());var model=ClassFile.of().parse(bytes);StringBuilder members=new StringBuilder();java.util.stream.StreamSupport.stream(model.constantPool().spliterator(),false).filter(MemberRefEntry.class::isInstance).map(MemberRefEntry.class::cast).forEach(m->members.append(m.owner().asInternalName()).append('.').append(m.name().stringValue()).append('\n'));assertAll(()->assertEquals(1,model.methods().size()),()->assertTrue(members.toString().contains("java/lang/Math.sqrt")),()->assertFalse(members.toString().contains("synaptik")));
  float[] input={1,2,3},scale={2},bias={.5f},oldMean={10},oldVar={4},output=new float[3],nextMean=new float[1],nextVar=new float[1],savedMean=new float[1],savedInv=new float[1];try(Arena arena=Arena.ofConfined()){var scratch=arena.allocate(plan.workspaceDeclaration().orElseThrow().byteSize(),8);long[] geometry=plan.batchNormTrainingGeometry().orElseThrow().pack(new long[10],0);var handle=generator.defineClassBytes(route.specialization(),bytes).entryPoint();handle.invokeExact(input,scale,bias,oldMean,oldVar,output,nextMean,nextVar,savedMean,savedInv,scratch,geometry,0L,1L);assertAll(()->assertEquals(Float.floatToRawIntBits(8f),Float.floatToRawIntBits(nextMean[0])),()->assertEquals(Float.floatToRawIntBits(3.25f),Float.floatToRawIntBits(nextVar[0])),()->assertEquals(Float.floatToRawIntBits(2f),Float.floatToRawIntBits(savedMean[0])),()->assertEquals(Float.floatToRawIntBits(.5f),Float.floatToRawIntBits(output[1])));
   input[1]=Float.POSITIVE_INFINITY;java.util.Arrays.fill(output,0);nextMean[0]=nextVar[0]=savedMean[0]=savedInv[0]=0;handle.invokeExact(input,scale,bias,oldMean,oldVar,output,nextMean,nextVar,savedMean,savedInv,scratch,geometry,0L,1L);int nan=0x7fc00000;for(float value:new float[]{output[0],output[1],output[2],nextMean[0],nextVar[0],savedMean[0],savedInv[0]})assertEquals(nan,Float.floatToRawIntBits(value));}}
 @Test void directOdometerIsRawBitEqualForFirstMiddleAndLastAxes() throws Throwable {
  executeAndCompare(new long[]{3,2},0);executeAndCompare(new long[]{2,3,2},1);executeAndCompare(new long[]{2,2,3},2);
 }
 private static void executeAndCompare(long[] extents,int axis)throws Throwable{
  var shape=io.github.pho001.synaptik.model.shape.Shape.of(extents);var base=CpuBatchNormTrainingLoweringTest.context(shape,axis);var inputs=new CpuPartitionAnalysisInputs(false,Collections.nCopies(10,CarrierAccess.FLOAT_ARRAY));var context=new PrepareContext<>(base.partition(),base.nodes(),base.values(),base.memoryRequirements(),base.constants(),inputs);var plan=new CpuPartitionPreparer().analyze(context).plan();var route=plan.units().getFirst().portablePlan();var generator=new CpuClassFileKernelGenerator();var handle=generator.defineClassBytes(route.specialization(),generator.generateClassBytes(route.specialization(),route.kernelIr())).entryPoint();int count=Math.toIntExact(java.util.Arrays.stream(extents).reduce(1,Math::multiplyExact)),channels=Math.toIntExact(extents[axis]);float[] input=new float[count],scale=new float[channels],bias=new float[channels],oldMean=new float[channels],oldVar=new float[channels],output=new float[count],nextMean=new float[channels],nextVar=new float[channels],savedMean=new float[channels],savedInv=new float[channels];for(int i=0;i<count;i++)input[i]=(i%7)-3;java.util.Arrays.fill(scale,2);java.util.Arrays.fill(bias,.5f);java.util.Arrays.fill(oldMean,10);java.util.Arrays.fill(oldVar,4);
  try(Arena arena=Arena.ofConfined()){var scratch=arena.allocate(plan.workspaceDeclaration().orElseThrow().byteSize(),8);long[] geometry=plan.batchNormTrainingGeometry().orElseThrow().pack(new long[10],0);handle.invokeExact(input,scale,bias,oldMean,oldVar,output,nextMean,nextVar,savedMean,savedInv,scratch,geometry,0L,(long)channels);}
  double[][] values={toDouble(input),toDouble(scale),toDouble(bias),toDouble(oldMean),toDouble(oldVar)};long[][] shapes={extents,new long[]{channels},new long[]{channels},new long[]{channels},new long[]{channels}};long[][] strides={denseStrides(extents),new long[]{1},new long[]{1},new long[]{1},new long[]{1}};var expected=io.github.pho001.synaptik.backend.cpu.internal.reference.CpuBatchNormTrainingReferenceKernel.evaluate(Collections.nCopies(5,io.github.pho001.synaptik.model.datatype.DataType.FLOAT32),io.github.pho001.synaptik.model.datatype.DataType.FLOAT32,.25f,1e-5f,values,shapes,new long[5],strides,axis);assertRaw(output,expected.output());assertRaw(nextMean,expected.nextRunningMean());assertRaw(nextVar,expected.nextRunningVariance());assertRaw(savedMean,expected.savedBatchMean());assertRaw(savedInv,expected.savedInverseStandardDeviation());
 }
 private static double[] toDouble(float[] values){double[] result=new double[values.length];for(int i=0;i<values.length;i++)result[i]=values[i];return result;}
 private static long[] denseStrides(long[] extents){long[] result=new long[extents.length];long stride=1;for(int i=extents.length-1;i>=0;i--){result[i]=stride;stride*=extents[i];}return result;}
 private static void assertRaw(float[] actual,double[] expected){assertEquals(expected.length,actual.length);for(int i=0;i<actual.length;i++)assertEquals(Float.floatToRawIntBits((float)expected[i]),Float.floatToRawIntBits(actual[i]),"coordinate "+i);}
}
