package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import io.github.pho001.synaptik.backend.cpu.internal.cache.CpuKernelSpecialization.CarrierAccess;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuConv3dLoweringTest;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionAnalysisInputs;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparationPlan.ExecutionUnitPlan;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparer;
import io.github.pho001.synaptik.model.datatype.DataType;
import io.github.pho001.synaptik.model.layout.LayoutDescriptor;
import io.github.pho001.synaptik.model.operation.convolution.Conv3dAttrs;
import io.github.pho001.synaptik.model.shape.Shape;
import io.github.pho001.synaptik.prepare.analysis.PrepareContext;
import java.lang.invoke.MethodHandle;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.ByteOrder;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Random;

/** Five-fork generated-versus-direct performance evidence harness for CPU 0008A Conv3d forms. */
public final class CpuConv3dPerformanceTest {
    private static final long MIN_BATCH_NANOS=25_000_000L;
    private static final Path EVIDENCE=Path.of("/private/tmp/synaptik-cpu-0008a-retained-evidence-20260826");
    private static final ValueLayout.OfFloat FLOAT = ValueLayout.JAVA_FLOAT_UNALIGNED
            .withOrder(ByteOrder.nativeOrder());
    private static final ValueLayout.OfShort SHORT = ValueLayout.JAVA_SHORT_UNALIGNED
            .withOrder(ByteOrder.nativeOrder());
    private static final ValueLayout.OfDouble DOUBLE = ValueLayout.JAVA_DOUBLE_UNALIGNED
            .withOrder(ByteOrder.nativeOrder());
    private static volatile long sink;
    @FunctionalInterface private interface Action{long run()throws Throwable;}
    private record Case(String name,Action generated,Action direct,Runnable verify){}
    private record Geometry(long[] x,long[] w,long[] y,Conv3dAttrs attrs){}
    private CpuConv3dPerformanceTest(){}

    /** Runs one accepted fork or aggregates the exact five retained forks. @param args fork/attempt or {@code aggregate} @throws Throwable on gate or evidence failure */
    public static void main(String[]args)throws Throwable{
        if(args.length>0&&args[0].equals("aggregate")){aggregate();return;}int fork=args.length==0?0:Integer.parseInt(args[0]),attempt=args.length<2?0:Integer.parseInt(args[1]);StringBuilder report=new StringBuilder();
        try(Arena arena=Arena.ofConfined()){environment(report);List<Case>cases=cases(arena);int[]repetitions=new int[cases.size()*2];for(int i=0;i<cases.size();i++){gate(cases.get(i));repetitions[2*i]=repetitions(cases.get(i).generated);repetitions[2*i+1]=repetitions(cases.get(i).direct);}long[][]generated=new long[cases.size()][9],direct=new long[cases.size()][9];Random random=new Random(0x0008_A0260826L^fork*0x9e3779b97f4a7c15L^attempt*0xd1b54a32d192ed03L);for(int round=-5;round<9;round++){List<Integer>order=new ArrayList<>();for(int i=0;i<cases.size();i++)order.add(i);Collections.shuffle(order,random);for(int i:order){long gt,dt;if(random.nextBoolean()){gt=time(cases.get(i).generated,repetitions[2*i]);dt=time(cases.get(i).direct,repetitions[2*i+1]);}else{dt=time(cases.get(i).direct,repetitions[2*i+1]);gt=time(cases.get(i).generated,repetitions[2*i]);}if(round>=0){generated[i][round]=gt/repetitions[2*i];direct[i][round]=dt/repetitions[2*i+1];gate(cases.get(i));}}}int failures=0;for(int i=0;i<cases.size();i++){long gm=median(generated[i]),dm=median(direct[i]);double ratio=(double)gm/dm;if(!(ratio<=1.15))failures++;report.append(String.format(Locale.ROOT,"RESULT,%s,%d,%d,%.9f,%s,%s%n",cases.get(i).name,gm,dm,ratio,Arrays.toString(generated[i]),Arrays.toString(direct[i])));}report.append("SINK,").append(sink).append('\n');if(failures!=0)throw new AssertionError("ratio failures "+failures);}catch(Throwable failure){report.append("REJECTED,").append(failure.getClass().getName()).append(',').append(clean(failure.getMessage())).append('\n');retain(false,fork,attempt,report.toString());System.out.print(report);throw failure;}retain(true,fork,attempt,report.toString());System.out.print(report);
    }

    private static List<Case>cases(Arena arena)throws Throwable{return List.of(f32("CONV3D-DENSE-F32",Shape.of(1,4,10,10,10),Shape.of(8,4,3,3,3),Shape.of(1,8,8,8,8),Conv3dAttrs.defaults(),false,1),f32("CONV3D-GROUPED-BIASED-F32",Shape.of(1,8,9,9,9),Shape.of(8,2,3,3,3),Shape.of(1,8,9,9,9),new Conv3dAttrs(1,1,1,1,1,1,1,1,1,4),true,1),f64(),bf16(),allSegment(arena),mixedGeneral(arena),f32("CONV3D-PARALLEL-F32",Shape.of(2,8,10,10,10),Shape.of(16,8,3,3,3),Shape.of(2,16,8,8,8),Conv3dAttrs.defaults(),false,4));}

    private static Case f32(String name,Shape xs,Shape ws,Shape ys,Conv3dAttrs attrs,boolean bias,int ranges)throws Throwable{List<DataType>types=Collections.nCopies(bias?3:2,DataType.FLOAT32);ExecutionUnitPlan unit=unit(types,xs,ws,ys,attrs,CarrierAccess.FLOAT_ARRAY,ranges);MethodHandle handle=handle(unit);int xc=count(xs),wc=count(ws),yc=count(ys),oc=(int)ws.toLongArray()[0];float[]x=new float[xc],w=new float[wc],b=bias?new float[oc]:null,g=new float[yc],d=new float[yc];fill(x);fill(w);if(b!=null)fill(b);long[]packed=unit.conv3dGeometry().orElseThrow().pack(new long[bias?4:3]);Geometry geometry=new Geometry(xs.toLongArray(),ws.toLongArray(),ys.toLongArray(),attrs);Action generated=()->{for(int r=0;r<ranges;r++){long start=(long)yc*r/ranges,end=(long)yc*(r+1)/ranges;if(bias)handle.invokeExact(x,w,b,g,packed,start,end);else handle.invokeExact(x,w,g,packed,start,end);}return checksum(g);};Action direct=()->{for(int r=0;r<ranges;r++)conv32(geometry,x,w,b,d,(long)yc*r/ranges,(long)yc*(r+1)/ranges);return checksum(d);};return new Case(name,generated,direct,()->{if(!Arrays.equals(g,d))throw new AssertionError(name);});}
    private static Case f64()throws Throwable{Shape xs=Shape.of(1,4,9,9,9),ws=Shape.of(6,2,3,3,3),ys=Shape.of(1,6,9,9,9);Conv3dAttrs attrs=new Conv3dAttrs(1,1,1,1,1,1,1,1,1,2);ExecutionUnitPlan unit=unit(Collections.nCopies(3,DataType.FLOAT64),xs,ws,ys,attrs,CarrierAccess.DOUBLE_ARRAY,1);MethodHandle handle=handle(unit);double[]x=new double[count(xs)],w=new double[count(ws)],b=new double[6],g=new double[count(ys)],d=new double[count(ys)];fill(x);fill(w);fill(b);long[]packed=unit.conv3dGeometry().orElseThrow().pack(new long[4]);Geometry geometry=new Geometry(xs.toLongArray(),ws.toLongArray(),ys.toLongArray(),attrs);Action generated=()->{handle.invokeExact(x,w,b,g,packed,0L,(long)g.length);return checksum(g);};Action direct=()->{conv64(geometry,x,w,b,d,0,d.length);return checksum(d);};return new Case("CONV3D-GROUPED-BIASED-F64",generated,direct,()->{if(!Arrays.equals(g,d))throw new AssertionError("f64");});}
    private static Case bf16()throws Throwable{Shape xs=Shape.of(1,8,8,8,8),ws=Shape.of(8,1,3,3,3),ys=Shape.of(1,8,8,8,8);Conv3dAttrs attrs=new Conv3dAttrs(1,1,1,1,1,1,1,1,1,8);ExecutionUnitPlan unit=unit(Collections.nCopies(2,DataType.BFLOAT16),xs,ws,ys,attrs,CarrierAccess.SHORT_ARRAY,1);MethodHandle handle=handle(unit);short[]x=new short[count(xs)],w=new short[count(ws)],g=new short[count(ys)],d=new short[count(ys)];fill(x);fill(w);long[]packed=unit.conv3dGeometry().orElseThrow().pack(new long[3]);Geometry geometry=new Geometry(xs.toLongArray(),ws.toLongArray(),ys.toLongArray(),attrs);Action generated=()->{handle.invokeExact(x,w,g,packed,0L,(long)g.length);return checksum(g);};Action direct=()->{conv16(geometry,x,w,d,0,d.length);return checksum(d);};return new Case("CONV3D-DEPTHWISE-BF16",generated,direct,()->{if(!Arrays.equals(g,d))throw new AssertionError("bf16");});}

    private static Case allSegment(Arena arena)throws Throwable{
        Shape xs=Shape.of(1,2,8,8,8),ws=Shape.of(3,2,3,3,3),ys=Shape.of(1,3,6,6,6);Conv3dAttrs attrs=Conv3dAttrs.defaults();
        var unit=unit(Collections.nCopies(2,DataType.FLOAT32),xs,ws,ys,attrs,null,List.of(CarrierAccess.MEMORY_SEGMENT,CarrierAccess.MEMORY_SEGMENT,CarrierAccess.MEMORY_SEGMENT),1);
        MethodHandle handle=handle(unit);MemorySegment x=arena.allocate((long)count(xs)*4,4),w=arena.allocate((long)count(ws)*4,4),g=arena.allocate((long)count(ys)*4,4),d=arena.allocate((long)count(ys)*4,4);fill32(x);fill32(w);long[]packed=unit.conv3dGeometry().orElseThrow().pack(new long[3]);Geometry geometry=new Geometry(xs.toLongArray(),ws.toLongArray(),ys.toLongArray(),attrs);
        Action generated=()->{handle.invokeExact(x,w,g,packed,0L,(long)count(ys));return checksum32(g);};Action direct=()->{conv32Segments(geometry,x,w,d,0,count(ys));return checksum32(d);};return new Case("CONV3D-ALL-SEGMENT-F32",generated,direct,()->{if(g.mismatch(d)!=-1)throw new AssertionError("all segment");});
    }

    private static Case mixedGeneral(Arena arena)throws Throwable{
        Shape xs=Shape.of(1,4,7,8,9),ws=Shape.of(6,2,2,2,2),ys=Shape.of(1,6,6,7,8);Conv3dAttrs attrs=new Conv3dAttrs(1,1,1,0,0,0,1,1,1,2);
        var layouts=List.of(LayoutDescriptor.of(xs,new long[]{2600,641,89,10,1},7,true),LayoutDescriptor.of(ws,new long[]{41,19,9,4,2},3,true),LayoutDescriptor.of(ys,new long[]{3600,587,83,9,1},5,true));
        var unit=unit(List.of(DataType.BFLOAT16,DataType.FLOAT64),xs,ws,ys,attrs,layouts,List.of(CarrierAccess.MEMORY_SEGMENT,CarrierAccess.DOUBLE_ARRAY,CarrierAccess.MEMORY_SEGMENT),1);var boundaries=unit.conv3dGeometry().orElseThrow().boundaries();MethodHandle handle=handle(unit);MemorySegment x=arena.allocate(span(boundaries.get(0))*2,2),g=arena.allocate(span(boundaries.get(2))*8,8),d=arena.allocate(span(boundaries.get(2))*8,8);double[]w=new double[Math.toIntExact(span(boundaries.get(1)))];fill16(x);fill(w);long[]packed=unit.conv3dGeometry().orElseThrow().pack(new long[3]);
        Action generated=()->{handle.invokeExact(x,w,g,packed,0L,(long)count(ys));return checksum64(g);};Action direct=()->{convMixed(boundaries,attrs,x,w,d,0,count(ys));return checksum64(d);};return new Case("CONV3D-GENERAL-MIXED",generated,direct,()->{if(g.mismatch(d)!=-1)throw new AssertionError("mixed general");});
    }

    private static ExecutionUnitPlan unit(List<DataType>types,Shape x,Shape w,Shape y,Conv3dAttrs attrs,CarrierAccess carrier,int ranges){PrepareContext<CpuPartitionAnalysisInputs>base=CpuConv3dLoweringTest.context(types,x,w,y,attrs,null);var config=new CpuPartitionAnalysisInputs.PortableExecutionConfig(CpuPartitionAnalysisInputs.PortableExecutionConfig.ComputePreference.SCALAR,ranges,ranges,1);var context=new PrepareContext<>(base.partition(),base.nodes(),base.values(),base.memoryRequirements(),base.constants(),new CpuPartitionAnalysisInputs(false,Collections.nCopies(types.size()+1,carrier),config));return new CpuPartitionPreparer().analyze(context).plan().units().getFirst();}
    private static ExecutionUnitPlan unit(List<DataType>types,Shape x,Shape w,Shape y,Conv3dAttrs attrs,List<LayoutDescriptor> layouts,List<CarrierAccess> carriers,int ranges){PrepareContext<CpuPartitionAnalysisInputs>base=CpuConv3dLoweringTest.context(types,x,w,y,attrs,layouts);var config=new CpuPartitionAnalysisInputs.PortableExecutionConfig(CpuPartitionAnalysisInputs.PortableExecutionConfig.ComputePreference.SCALAR,ranges,ranges,1);var context=new PrepareContext<>(base.partition(),base.nodes(),base.values(),base.memoryRequirements(),base.constants(),new CpuPartitionAnalysisInputs(false,carriers,config));return new CpuPartitionPreparer().analyze(context).plan().units().getFirst();}
    private static MethodHandle handle(ExecutionUnitPlan unit){var generator=new CpuClassFileKernelGenerator();byte[]bytes=generator.generateClassBytes(unit.portablePlan().specialization(),unit.portablePlan().kernelIr());return generator.defineClassBytes(unit.portablePlan().specialization(),bytes).entryPoint();}

    private static void conv32(Geometry g,float[]x,float[]w,float[]b,float[]out,long start,long end){long[]xe=g.x,we=g.w,ye=g.y;long opg=ye[1]/g.attrs.groups();for(long cell=start;cell<end;cell++){long q=cell,ow=q%ye[4];q/=ye[4];long oh=q%ye[3];q/=ye[3];long od=q%ye[2];q/=ye[2];long oc=q%ye[1],n=q/ye[1];float sum=b==null?0:b[(int)oc];long cb=oc/opg*we[1];for(long ic=0;ic<we[1];ic++)for(long kd=0;kd<we[2];kd++)for(long kh=0;kh<we[3];kh++)for(long kw=0;kw<we[4];kw++){long id=od*g.attrs.strideDepth()-g.attrs.paddingDepth()+kd*g.attrs.dilationDepth(),ih=oh*g.attrs.strideHeight()-g.attrs.paddingHeight()+kh*g.attrs.dilationHeight(),iw=ow*g.attrs.strideWidth()-g.attrs.paddingWidth()+kw*g.attrs.dilationWidth();float xv=id<0||id>=xe[2]||ih<0||ih>=xe[3]||iw<0||iw>=xe[4]?0:x[(int)((((n*xe[1]+cb+ic)*xe[2]+id)*xe[3]+ih)*xe[4]+iw)];float wv=w[(int)((((oc*we[1]+ic)*we[2]+kd)*we[3]+kh)*we[4]+kw)];sum=(float)(sum+xv*wv);}out[(int)cell]=sum;}}
    private static void conv64(Geometry g,double[]x,double[]w,double[]b,double[]out,long start,long end){long[]xe=g.x,we=g.w,ye=g.y;long opg=ye[1]/g.attrs.groups();for(long cell=start;cell<end;cell++){long q=cell,ow=q%ye[4];q/=ye[4];long oh=q%ye[3];q/=ye[3];long od=q%ye[2];q/=ye[2];long oc=q%ye[1],n=q/ye[1];double sum=b==null?0:b[(int)oc];long cb=oc/opg*we[1];for(long ic=0;ic<we[1];ic++)for(long kd=0;kd<we[2];kd++)for(long kh=0;kh<we[3];kh++)for(long kw=0;kw<we[4];kw++){long id=od*g.attrs.strideDepth()-g.attrs.paddingDepth()+kd*g.attrs.dilationDepth(),ih=oh*g.attrs.strideHeight()-g.attrs.paddingHeight()+kh*g.attrs.dilationHeight(),iw=ow*g.attrs.strideWidth()-g.attrs.paddingWidth()+kw*g.attrs.dilationWidth();double xv=id<0||id>=xe[2]||ih<0||ih>=xe[3]||iw<0||iw>=xe[4]?0:x[(int)((((n*xe[1]+cb+ic)*xe[2]+id)*xe[3]+ih)*xe[4]+iw)];sum+=xv*w[(int)((((oc*we[1]+ic)*we[2]+kd)*we[3]+kh)*we[4]+kw)];}out[(int)cell]=sum;}}
    private static void conv16(Geometry g,short[]x,short[]w,short[]out,long start,long end){long[]xe=g.x,we=g.w,ye=g.y;long opg=ye[1]/g.attrs.groups();for(long cell=start;cell<end;cell++){long q=cell,ow=q%ye[4];q/=ye[4];long oh=q%ye[3];q/=ye[3];long od=q%ye[2];q/=ye[2];long oc=q%ye[1],n=q/ye[1];float sum=0;long cb=oc/opg*we[1];for(long ic=0;ic<we[1];ic++)for(long kd=0;kd<we[2];kd++)for(long kh=0;kh<we[3];kh++)for(long kw=0;kw<we[4];kw++){long id=od*g.attrs.strideDepth()-g.attrs.paddingDepth()+kd*g.attrs.dilationDepth(),ih=oh*g.attrs.strideHeight()-g.attrs.paddingHeight()+kh*g.attrs.dilationHeight(),iw=ow*g.attrs.strideWidth()-g.attrs.paddingWidth()+kw*g.attrs.dilationWidth();float xv=id<0||id>=xe[2]||ih<0||ih>=xe[3]||iw<0||iw>=xe[4]?0:decode(x[(int)((((n*xe[1]+cb+ic)*xe[2]+id)*xe[3]+ih)*xe[4]+iw)]);float wv=decode(w[(int)((((oc*we[1]+ic)*we[2]+kd)*we[3]+kh)*we[4]+kw)]);sum=(float)(sum+xv*wv);}out[(int)cell]=bf(sum);}}

    private static void conv32Segments(Geometry g,MemorySegment x,MemorySegment w,MemorySegment out,long start,long end){long[]xe=g.x,we=g.w,ye=g.y;long opg=ye[1]/g.attrs.groups();for(long cell=start;cell<end;cell++){long q=cell,ow=q%ye[4];q/=ye[4];long oh=q%ye[3];q/=ye[3];long od=q%ye[2];q/=ye[2];long oc=q%ye[1],n=q/ye[1];float sum=0;long cb=oc/opg*we[1];for(long ic=0;ic<we[1];ic++)for(long kd=0;kd<we[2];kd++)for(long kh=0;kh<we[3];kh++)for(long kw=0;kw<we[4];kw++){long id=od*g.attrs.strideDepth()-g.attrs.paddingDepth()+kd*g.attrs.dilationDepth(),ih=oh*g.attrs.strideHeight()-g.attrs.paddingHeight()+kh*g.attrs.dilationHeight(),iw=ow*g.attrs.strideWidth()-g.attrs.paddingWidth()+kw*g.attrs.dilationWidth();float xv=id<0||id>=xe[2]||ih<0||ih>=xe[3]||iw<0||iw>=xe[4]?0:x.get(FLOAT,4*((((n*xe[1]+cb+ic)*xe[2]+id)*xe[3]+ih)*xe[4]+iw));float wv=w.get(FLOAT,4*((((oc*we[1]+ic)*we[2]+kd)*we[3]+kh)*we[4]+kw));sum=(float)(sum+xv*wv);}out.set(FLOAT,4*cell,sum);}}

    private static void convMixed(List<io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuConv3dLowering.Layout> b,Conv3dAttrs attrs,MemorySegment x,double[]w,MemorySegment out,long start,long end){var xl=b.get(0);var wl=b.get(1);var yl=b.get(2);long[]xe=xl.extents(),we=wl.extents(),ye=yl.extents(),xs=xl.strides(),ws=wl.strides(),ys=yl.strides();long opg=ye[1]/attrs.groups();for(long cell=start;cell<end;cell++){long q=cell,ow=q%ye[4];q/=ye[4];long oh=q%ye[3];q/=ye[3];long od=q%ye[2];q/=ye[2];long oc=q%ye[1],n=q/ye[1],oa=yl.offset()+n*ys[0]+oc*ys[1]+od*ys[2]+oh*ys[3]+ow*ys[4];double sum=0;long cb=oc/opg*we[1];for(long ic=0;ic<we[1];ic++)for(long kd=0;kd<we[2];kd++)for(long kh=0;kh<we[3];kh++)for(long kw=0;kw<we[4];kw++){long id=od*attrs.strideDepth()-attrs.paddingDepth()+kd*attrs.dilationDepth(),ih=oh*attrs.strideHeight()-attrs.paddingHeight()+kh*attrs.dilationHeight(),iw=ow*attrs.strideWidth()-attrs.paddingWidth()+kw*attrs.dilationWidth();double xv=id<0||id>=xe[2]||ih<0||ih>=xe[3]||iw<0||iw>=xe[4]?0:decode(x.get(SHORT,2*(xl.offset()+n*xs[0]+(cb+ic)*xs[1]+id*xs[2]+ih*xs[3]+iw*xs[4])));sum+=xv*w[(int)(wl.offset()+oc*ws[0]+ic*ws[1]+kd*ws[2]+kh*ws[3]+kw*ws[4])];}out.set(DOUBLE,oa*8,sum);}}

    private static int count(Shape s){return Math.toIntExact(Arrays.stream(s.toLongArray()).reduce(1,Math::multiplyExact));}private static long span(io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuConv3dLowering.Layout l){long m=l.offset();for(int i=0;i<l.extents().length;i++)m+=Math.max(0,l.extents()[i]-1)*l.strides()[i];return m+1;}private static void fill(float[]x){for(int i=0;i<x.length;i++)x[i]=(i%31-15)*.03125f;}private static void fill(double[]x){for(int i=0;i<x.length;i++)x[i]=(i%31-15)*.03125;}private static void fill(short[]x){for(int i=0;i<x.length;i++)x[i]=bf((i%31-15)*.03125f);}private static void fill32(MemorySegment x){for(long i=0;i<x.byteSize()/4;i++)x.set(FLOAT,i*4,(i%31-15)*.03125f);}private static void fill16(MemorySegment x){for(long i=0;i<x.byteSize()/2;i++)x.set(SHORT,i*2,bf((i%31-15)*.03125f));}private static short bf(float v){int b=Float.floatToRawIntBits(v);if((b&0x7fffffff)>0x7f800000)return(short)0x7fc0;return(short)((b+0x7fff+(b>>>16&1))>>>16);}private static float decode(short v){return Float.intBitsToFloat(Short.toUnsignedInt(v)<<16);}private static long checksum(float[]x){long h=0;for(float v:x)h=Long.rotateLeft(h,1)^Integer.toUnsignedLong(Float.floatToRawIntBits(v));return h;}private static long checksum(double[]x){long h=0;for(double v:x)h=Long.rotateLeft(h,1)^Double.doubleToRawLongBits(v);return h;}private static long checksum(short[]x){long h=0;for(short v:x)h=Long.rotateLeft(h,1)^Short.toUnsignedLong(v);return h;}private static long checksum32(MemorySegment x){long h=0;for(long p=0;p<x.byteSize();p+=4)h=Long.rotateLeft(h,1)^Integer.toUnsignedLong(Float.floatToRawIntBits(x.get(FLOAT,p)));return h;}private static long checksum64(MemorySegment x){long h=0;for(long p=0;p<x.byteSize();p+=8)h=Long.rotateLeft(h,1)^Double.doubleToRawLongBits(x.get(DOUBLE,p));return h;}private static void gate(Case c)throws Throwable{long g=c.generated.run(),d=c.direct.run();if(g!=d)throw new AssertionError(c.name+" checksum "+g+"/"+d);c.verify.run();}private static long time(Action a,int n)throws Throwable{long s=System.nanoTime(),v=0;for(int i=0;i<n;i++)v^=a.run();sink^=v;return System.nanoTime()-s;}private static int repetitions(Action a)throws Throwable{int n=1;while(time(a,n)<MIN_BATCH_NANOS)n=Math.multiplyExact(n,2);return n;}private static long median(long[]a){long[]c=a.clone();Arrays.sort(c);return c[4];}
    private static void environment(StringBuilder out){long total=Runtime.getRuntime().totalMemory(),max=Runtime.getRuntime().maxMemory();String java=System.getProperty("java.version");out.append("ENV,java=").append(java).append(",vm=").append(System.getProperty("java.vm.name")).append(",processors=").append(Runtime.getRuntime().availableProcessors()).append(",totalMemory=").append(total).append(",maxMemory=").append(max).append(",byteOrder=").append(ByteOrder.nativeOrder()).append('\n');long low=900L<<20,high=1100L<<20;if(!java.startsWith("26")||total<low||max<low||max>high)throw new AssertionError("requires Java 26 -Xms1g -Xmx1g");}
    private static void retain(boolean accepted,int fork,int attempt,String value)throws Exception{Path dir=EVIDENCE.resolve(accepted?"forks":"rejected-samples");Files.createDirectories(dir);String name=accepted?"fork-"+fork+".csv":"fork-"+fork+"-attempt-"+attempt+"-"+Instant.now().toEpochMilli()+".csv";Files.writeString(dir.resolve(name),value);}private static String clean(String s){return s==null?"":s.replace('\n',' ').replace('\r',' ').replace(',',';');}
    private static void aggregate()throws Exception{List<String>names=null;double[][]ratios=new double[5][7];for(int f=0;f<5;f++){List<String>ns=new ArrayList<>();int i=0;for(String line:Files.readAllLines(EVIDENCE.resolve("forks/fork-"+f+".csv")))if(line.startsWith("RESULT,")){String[]x=line.split(",",6);ns.add(x[1]);ratios[f][i++]=Double.parseDouble(x[4]);}if(i!=7)throw new AssertionError("fork "+f+" count "+i);if(names==null)names=List.copyOf(ns);else if(!names.equals(ns))throw new AssertionError("inventory");}StringBuilder report=new StringBuilder();int failures=0;for(int i=0;i<7;i++){double[]v=new double[5];for(int f=0;f<5;f++)v[f]=ratios[f][i];Arrays.sort(v);if(v[2]>1.15)failures++;report.append(String.format(Locale.ROOT,"AGGREGATE,%s,%.9f,%s%n",names.get(i),v[2],Arrays.toString(v)));}long rejected=Files.exists(EVIDENCE.resolve("rejected-samples"))?Files.list(EVIDENCE.resolve("rejected-samples")).count():0;report.append("COUNTS,accepted=5,rejected=").append(rejected).append('\n');Files.writeString(EVIDENCE.resolve("summary.csv"),report);System.out.print(report);if(failures!=0)throw new AssertionError("aggregate failures "+failures);}
}
