package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import static org.junit.jupiter.api.Assertions.*;

import io.github.pho001.synaptik.backend.cpu.CpuGeneratedCoverageUnsupportedBoundaryTest;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparer;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.Set;
import org.junit.jupiter.api.Test;

/**
 * Verifies the canonical generated-combination inventory.
 *
 * <p>Every row is the complete fact set emitted by one actual provider-to-preparer-to-generator
 * fixture execution. The owner and evidence key are foreign keys to that execution; operation
 * form is an inspectable attribute, never a join key. Oracle and performance are resolved by
 * canonical predicates over those facts; a partial disposition is an explicit gap, not a pass.</p>
 */
class CpuGeneratedCoverageCheckpointTest {
    private static final String BASE = "/io/github/pho001/synaptik/backend/cpu/internal/codegen/emit/";
    private static final String POST_TERMINAL_PRE_FROZEN_LAYOUT_INVENTORY_SHA256 =
            "2e9f07e30b47429387c8c1043207ee6e8feae327f09ac24a7a8f8c51821918fb";
    private static final String FROZEN_LAYOUT_INVENTORY_SHA256 =
            "527f36de41b64c228dd215c6f3182138b4c70db24c915117c4d7f82743ac41cc";
    private static final String HEADER = "owner-id\tevidence-key\toperation-form\tlowered-ir-family"
            + "\tdescriptor-alias-roles\tordered-boundary-values\tvirtual-values\tunit-count"
            + "\taffine-address-pairs\tordered-carriers\tlayout-access\trequested-strategy"
            + "\tselected-strategy\tmaterialization-candidate\tmaterializations-selected"
            + "\tprovider-supported\tpreparer-admitted\tprepared-ir-structural-key"
            + "\tgenerated-entry-descriptor\tclass-sha256\tnormalized-body-key\toutcome\treason"
            + "\tordinary-production-selection\tfallback-disposition\toracle-disposition\tperformance-disposition\n";

    @Test void exactCombinationInventoryReproducesEveryCanonicalFixtureExecution() throws Exception {
        Map<String, CpuGeneratedCoverageEvidenceRegistry.Record> observed = executeCanonicalFixtures();
        String actual = serialize(observed);
        dumpIfRequested(actual);
        String expected = resource("generated-coverage-inventory.tsv");
        assertEquals(expected, actual, "inventory must be regenerated byte-for-byte from its fixture executions");

        Map<String, String[]> rows = parse(expected);
        assertEquals(observed.size(), rows.size(), "missing, duplicate, or extra inventory rows");
        for (var entry : observed.entrySet()) {
            String[] row = rows.get(entry.getKey());
            assertNotNull(row, "missing owner: " + entry.getKey());
            assertEquals(entry.getValue().evidenceKey(), row[1], "repointed or relabeled owner: " + entry.getKey());
            assertSame(entry.getValue(), CpuGeneratedCoverageEvidenceRegistry.requireExact(row[0], row[1]));
            if (entry.getValue().outcome().equals("GENERATED")) {
                assertFalse(row[25].equals("PENDING"), entry.getKey());
                assertFalse(row[26].equals("PENDING"), entry.getKey());
            } else {
                assertEquals("N/A_NO_GENERATED_CODE", row[25], entry.getKey());
                assertEquals("N/A_NO_GENERATED_CODE", row[26], entry.getKey());
            }
        }
        assertEquals(17_463L, observed.values().stream().filter(record -> record.outcome().equals("GENERATED")).count());
        assertEquals(173L, observed.values().stream().filter(record -> !record.outcome().equals("GENERATED")).count());
        assertEquals(845L, observed.keySet().stream().filter(id -> id.startsWith("pointwise-matrix:")).count());
        assertEquals(256L, observed.keySet().stream().filter(id -> id.startsWith("scalar-immediate:")).count());
        assertTrue(observed.keySet().stream().anyMatch(id -> id.startsWith("ordinary:")));
        assertTrue(observed.keySet().stream().anyMatch(id -> id.startsWith("specialized:")));
        assertTrue(observed.keySet().stream().anyMatch(id -> id.startsWith("composition:conv1d/")));
        assertTrue(observed.keySet().stream().anyMatch(id -> id.startsWith("composition:pool1d/")));
        assertEquals(17_463L, rows.values().stream().filter(row -> row[21].equals("GENERATED"))
                .filter(row -> !row[25].equals("PENDING") && !row[26].equals("PENDING")).count());
        assertLiveDispositionResolution(observed);
    }

    @Test void postTerminalPreFrozenLayoutInventoryTransitionChangesOnlyThe24RecordedCompositionIdentities()
            throws Exception {
        String inventory = resource("generated-coverage-inventory.tsv");
        assertEquals(FROZEN_LAYOUT_INVENTORY_SHA256,
                hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))));
        Map<String, String[]> inventoryRows = parse(inventory);
        String transition = resource("cpu-0009c1-post-terminal-frozen-layout-transition.tsv");
        assertTrue(transition.endsWith("\n") && !transition.contains("\r"));
        String[] lines = transition.split("\n", -1);
        assertEquals(HEADER.stripTrailing(), lines[0]);
        Map<String, String[]> rows = new LinkedHashMap<>();
        for (int line = 1; line < lines.length - 1; line++) {
            String[] row = lines[line].split("\t", -1);
            assertEquals(27, row.length, "transition line " + (line + 1));
            for (String field : row) assertFalse(field.isBlank(), "transition field line " + (line + 1));
            assertNull(rows.put(row[0], row), "duplicate transition owner: " + row[0]);
        }
        assertEquals(24, rows.size(), "only the recorded post-terminal to frozen-layout identities change");
        assertEquals(Map.of("CONCAT", 12L, "STACK", 12L), rows.keySet().stream()
                .collect(java.util.stream.Collectors.groupingBy(owner -> inventoryRows.get(owner)[2], TreeMap::new,
                        java.util.stream.Collectors.counting())));
        assertEquals(Set.of("BFLOAT16", "BOOL", "FLOAT32", "FLOAT64", "INT32", "INT64"), rows.keySet().stream()
                .map(owner -> owner.split("/")[1]).collect(java.util.stream.Collectors.toUnmodifiableSet()));
        for (String[] previous : rows.values()) {
            String owner = previous[0];
            String[] current = inventoryRows.get(owner);
            assertNotNull(current, "current inventory owner: " + owner);
            assertTrue(owner.contains("/mixed-general-parallel-vector")
                    || owner.contains("/segment-contiguous-vector"), owner);
            assertNotEquals(previous[1], current[1], owner + " evidence identity changes");
            assertNotEquals(previous[19], current[19], owner + " generated class identity changes");
            for (int column = 0; column < current.length; column++) {
                if (column != 1 && column != 19) assertEquals(previous[column], current[column],
                        owner + " preserves non-identity column " + column);
            }
        }
        assertFalse(rows.values().stream().anyMatch(row -> row[2].equals("PAD") || row[2].equals("TILE")));
        assertNotEquals(POST_TERMINAL_PRE_FROZEN_LAYOUT_INVENTORY_SHA256,
                hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))),
                "the aggregate layout correction intentionally advances the frozen inventory");
    }

    @Test void directPoolProjectionInvokesEveryOneOfIts120ExactInventoryOwners() throws Throwable {
        new CpuPool2d3dSemanticClosureTest()
                .everyExactGeneratedPoolOwnerDefinesAndInvokesItsSpecializedEntry();
        Map<String, String[]> rows = parse(resource("generated-coverage-inventory.tsv"));
        for (String form : Set.of("AVERAGE_POOL2D", "MAX_POOL2D", "AVERAGE_POOL3D", "MAX_POOL3D")) {
            long count = rows.entrySet().stream()
                    .filter(entry -> entry.getKey().startsWith("specialized:"))
                    .filter(entry -> entry.getValue()[2].equals(form))
                    .filter(entry -> entry.getValue()[21].equals("GENERATED"))
                    .count();
            assertEquals(30L, count, form + " exact generated inventory projection");
        }
    }

    /**
     * Runs the semantic half of the closure as one fail-closed gate.
     *
     * <p>The inventory itself is intentionally not a semantic witness: it records the exact
     * provider/preparer/generator facts for an owner.  Each invoked closure below independently
     * reconstructs its finite owner basis, defines the corresponding generated class, invokes
     * its static entry, and compares its result with that family's independent oracle.  Those
     * tests also join their reconstructed identities to this SHA-bound inventory.  Keeping the
     * calls here makes the checkpoint fail if a partition is no longer executed by its direct
     * witness, even when its generation-only matrix remains current.</p>
     */
    @Test void everyGeneratedOwnerHasExactlyOneDirectGeneratedEntrySemanticWitness() throws Throwable {
        Map<String, String[]> rows = parse(resource("generated-coverage-inventory.tsv"));
        assertGeneratedOwnerPartitions(rows);

        new CpuAffineGeneratedCoverageFixtureTest()
                .everyAffineInventoryRowDefinesInvokesAndMatchesCoordinateOracle();
        new CpuPointwiseSemanticClosureManifestTest()
                .everyManifestOwnerExecutesItsIndependentGeneratedEntryOracle();
        new CpuScalarImmediateClampCleanJavaStructuralEquivalenceTest()
                .everyFormExecutesItsCompiledCleanCounterpartAgainstTheGeneratedOutput();

        new CpuOrdinaryMovementFoldSemanticClosureTest()
                .everyExactOrdinaryMovementAndFoldOwnerExecutesAgainstIndependentOracle();
        new CpuAggregateScanSemanticClosureTest()
                .everyAggregateAndScanMatrixCandidateDefinesAndExecutesItsOwnArtifact();
        new CpuIndexingOrderingSemanticClosureTest()
                .everyOrdinaryGatherAndOrderingRowExecutesAgainstAnIndependentOracle();
        new CpuScatterSemanticClosureTest()
                .everyOrdinaryScatterInventoryCandidateExecutesAgainstTheIndependentOracle();
        new CpuRandomOneHotSemanticClosureTest()
                .everyOrdinaryRandomAndOneHotOwnerDefinesAndExecutesItsActualEntry();

        new CpuArgExtremaSemanticClosureTest()
                .everyArgExtremaInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        new CpuMaskedAdvancedReductionSemanticClosureTest()
                .everyMaskedAndAdvancedInventoryOwnerDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        new CpuNormalizationSemanticClosureTest()
                .everyNormalizationInventoryOwnerDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        var batchNorm = new CpuBatchNormSemanticClosureTest();
        batchNorm.everyBatchNormInferenceInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        batchNorm.everyBatchNormTrainingInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        new CpuMatmulSemanticClosureTest()
                .everyMatmulInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        var convolution = new CpuConvolutionSemanticClosureTest();
        convolution.everyConv1dCompositionInventoryRowDefinesAndInvokesItsActualLoweredEntry();
        convolution.everyConv2dInventoryRowDefinesAndInvokesItsActualGeneratedEntry();
        convolution.everyConv3dInventoryRowDefinesAndInvokesItsActualGeneratedEntry();
        new CpuPool2d3dSemanticClosureTest()
                .everyExactGeneratedPoolOwnerDefinesAndInvokesItsSpecializedEntry();
        new CpuPool1dCompositionSemanticClosureTest()
                .everyExactGeneratedPool1dCompositionOwnerDefinesAndInvokesItsSpecializedEntry();
        new CpuAttentionSemanticClosureTest()
                .everyAttentionInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
        new CpuLossSemanticClosureTest()
                .everyLossInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle();
    }

    private static void assertGeneratedOwnerPartitions(Map<String, String[]> rows) {
        Map<String, Long> expected = Map.of(
                "specialized", 12_850L,
                "affine-matrix", 1_536L,
                "ordinary", 1_400L,
                "pointwise-matrix", 845L,
                "composition", 576L,
                "scalar-immediate", 256L);
        Map<String, Long> actual = new TreeMap<>();
        for (var entry : rows.entrySet()) {
            if (!entry.getValue()[21].equals("GENERATED")) continue;
            String owner = entry.getKey();
            String partition = owner.substring(0, owner.indexOf(':'));
            actual.merge(partition, 1L, Long::sum);
        }
        assertEquals(expected, actual, "generated owner partitions must be complete and disjoint");
        assertEquals(17_463L, actual.values().stream().mapToLong(Long::longValue).sum());
        assertEquals(173L, rows.size() - actual.values().stream().mapToLong(Long::longValue).sum(),
                "provider/preparer rejects remain outside generated semantic closure");
    }

    /** Runs each finite owner matrix once; clearing makes this independent of JUnit order. */
    private static Map<String, CpuGeneratedCoverageEvidenceRegistry.Record> executeCanonicalFixtures()
            throws Exception {
        CpuGeneratedCoverageEvidenceRegistry.clear();
        new CpuGeneratedDirectEvidenceClosureTest().pointwiseCandidateUniverseClosesRequestedCarrierLayoutAndStrategyAxes();
        for (var form : CpuScalarImmediateClampMatrixOracle.forms()) CpuScalarImmediateClampMatrixOracle.formArtifact(form);
        for (int index = 0; index < CpuAffineGeneratedCoverageFixtureTest.coverageFixtureContexts().size(); index++) {
            var context = CpuAffineGeneratedCoverageFixtureTest.coverageFixtureContexts().get(index);
            CpuGeneratedCoverageEvidenceRegistry.generated("affine-matrix:" + index, context,
                    new CpuPartitionPreparer().analyze(context).plan());
        }
        var ordinary = new CpuOrdinaryNonPointwiseGeneratedMatrixTest();
        ordinary.everyModelValidOrdinaryBaseRoleTypeAndRuntimeRequestUsesProductionBoundaries();
        var specialized = new CpuSpecializedGeneratedMatrixTest();
        specialized.everyAdmittedArgMaskedAdvancedAndSoftmaxFormGeneratesAcrossRequests();
        specialized.everyAdmittedTrailingAndBatchNormRoleCombinationGeneratesAcrossRequests();
        specialized.everyCurrentDirectMatmulFormGeneratesAcrossRequests();
        specialized.everyCurrentDirectConvolutionAndPoolingFormGeneratesAcrossRequests();
        specialized.everyCurrentDirectAttentionAndLossRoleFormGeneratesAcrossRequests();
        var composition = new CpuOneDimensionalCompositionGeneratedMatrixTest();
        composition.everyModelValidConv1dCompositionRoleAndGeometryGeneratesAcrossRequests();
        composition.everyModelValidPool1dCompositionTypeAndGeometryGeneratesAcrossRequests();
        for (var candidate : CpuGeneratedDirectEvidenceClosureTest.rejectedPointwiseCandidates()) {
            var fixture = candidate.coverageFixture();
            CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("rejected:pointwise:" + fixture.id(),
                    fixture.operationForm(), fixture.operation(), fixture.inputs(), fixture.outputs(), fixture.reason());
        }
        for (var fixture : CpuOrdinaryNonPointwiseGeneratedMatrixTest.rejectedProviderFixtures()) {
            CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("rejected:ordinary:" + fixture.id(),
                    fixture.operationForm(), fixture.operation(), fixture.inputs(), fixture.outputs(), fixture.reason());
        }
        for (var fixture : CpuSpecializedGeneratedMatrixTest.rejectedProviderFixtures()) {
            CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("rejected:specialized:" + fixture.id(),
                    fixture.operationForm(), fixture.operation(), fixture.inputs(), fixture.outputs(), fixture.reason());
        }
        for (var fixture : CpuGeneratedCoverageUnsupportedBoundaryTest.rejectedFixtures()) {
            CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("rejected:unsupported:" + fixture.id(),
                    fixture.operation().kind().name(), fixture.operation(), fixture.inputs(), fixture.outputs(), fixture.reason());
        }
        for (var fixture : CpuOneDimensionalCompositionGeneratedMatrixTest.rejectedPoolFixtures()) {
            CpuGeneratedCoverageEvidenceRegistry.rejectedByPreparer("rejected:composition:" + fixture.id(),
                    fixture.operationForm(), fixture.context(), fixture.reason());
        }
        return new TreeMap<>(CpuGeneratedCoverageEvidenceRegistry.snapshot());
    }

    @Test void exactOwnerRejectsEveryJoinDimensionAndStaticRegistryState() {
        var first = CpuGeneratedDirectEvidenceClosureTest.coverageFixtureContexts().getFirst();
        var second = CpuGeneratedDirectEvidenceClosureTest.coverageFixtureContexts().get(1);
        CpuGeneratedCoverageEvidenceRegistry.clear();
        var record = CpuGeneratedCoverageEvidenceRegistry.generated("exact-owner", first,
                new CpuPartitionPreparer().analyze(first).plan());
        for (String fact : List.of("form", "type-or-alias-roles", "carrier-order", "layout",
                "requested-strategy", "selected-strategy", "materialization", "ir-family", "hash-or-body",
                "ordinary-selection", "fallback-disposition", "oracle-or-performance-disposition")) {
            assertNotEquals(record.evidenceKey(), record.mutate(fact).evidenceKey(), fact);
            assertThrows(AssertionError.class, () -> CpuGeneratedCoverageEvidenceRegistry.requireExact(
                    "exact-owner", record.mutate(fact).evidenceKey()), fact);
        }
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageEvidenceRegistry.requireExact(
                "repointed-owner", record.evidenceKey()));
        CpuGeneratedCoverageEvidenceRegistry.clear();
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageEvidenceRegistry.require("exact-owner"));
        CpuGeneratedCoverageEvidenceRegistry.generated("exact-owner", second,
                new CpuPartitionPreparer().analyze(second).plan());

        CpuGeneratedCoverageEvidenceRegistry.clear();
        var rejected = CpuGeneratedDirectEvidenceClosureTest.rejectedPointwiseCandidates().getFirst().coverageFixture();
        var rejection = CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("rejected-owner", rejected.operationForm(),
                rejected.operation(), rejected.inputs(), rejected.outputs(), rejected.reason());
        assertNotEquals(rejection.evidenceKey(), rejection.mutate("rejection-boundary-or-reason").evidenceKey());
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageEvidenceRegistry.requireExact(
                "rejected-owner", rejection.mutate("rejection-boundary-or-reason").evidenceKey()));
    }

    @Test void canonicalDispositionRegistryRejectsOrphansDuplicatesAndInapplicableEvidence() {
        var context = CpuGeneratedDirectEvidenceClosureTest.coverageFixtureContexts().getFirst();
        CpuGeneratedCoverageEvidenceRegistry.clear();
        var record = CpuGeneratedCoverageEvidenceRegistry.generated("disposition-owner", context,
                new CpuPartitionPreparer().analyze(context).plan());
        assertThrows(AssertionError.class,
                () -> CpuGeneratedCoverageDispositionRegistry.verifyCanonicalRegistry(Map.of("disposition-owner", record)),
                "the complete registry rejects an orphaned scoped selector");
        assertEquals("oracle-exact-fixture-classfile-v1", CpuGeneratedCoverageDispositionRegistry.resolve(
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, record).evidenceId());
        assertEquals("performance-exact-fixture-unmeasured-v1", CpuGeneratedCoverageDispositionRegistry.resolve(
                CpuGeneratedCoverageDispositionRegistry.Kind.PERFORMANCE, record).evidenceId());
        var rejected = CpuGeneratedDirectEvidenceClosureTest.rejectedPointwiseCandidates().getFirst().coverageFixture();
        var noCode = CpuGeneratedCoverageEvidenceRegistry.rejectedByProvider("disposition-rejected",
                rejected.operationForm(), rejected.operation(), rejected.inputs(), rejected.outputs(), rejected.reason());
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.resolve(
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, noCode));

        var entries = CpuGeneratedCoverageDispositionRegistry.entries();
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.resolve(
                List.of(new CpuGeneratedCoverageDispositionRegistry.Entry("unsafe-rejection",
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, "ORACLE_PROVED",
                        "owner-prefix=disposition-rejected", "CpuGeneratedCoverageCheckpointTest#exactCombinationInventoryReproducesEveryCanonicalFixtureExecution")),
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, noCode), "rejected owner never inherits promotion");
        var reversed = new java.util.ArrayList<>(entries);
        java.util.Collections.reverse(reversed);
        assertEquals(CpuGeneratedCoverageDispositionRegistry.resolve(entries,
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, record).id(),
                CpuGeneratedCoverageDispositionRegistry.resolve(reversed,
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, record).id(),
                "selector precedence is TSV-order independent");
        var overlap = new java.util.ArrayList<>(entries);
        overlap.add(new CpuGeneratedCoverageDispositionRegistry.Entry("ambiguous-fallback",
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, "ORACLE_PROVED",
                "outcome=GENERATED;evidence-key=present",
                "CpuGeneratedCoverageCheckpointTest#exactCombinationInventoryReproducesEveryCanonicalFixtureExecution"));
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.resolve(overlap,
                CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, record), "equal-specificity overlap fails closed");
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.verify(List.of(
                new CpuGeneratedCoverageDispositionRegistry.Entry("bad-reference",
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, "ORACLE_PROVED", "outcome=GENERATED",
                        "Missing#evidence")), Map.of("disposition-owner", record)), "missing evidence reference");
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.verify(List.of(
                new CpuGeneratedCoverageDispositionRegistry.Entry("orphan", CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE,
                        "ORACLE_PROVED", "owner-prefix=no-such-owner:",
                        "CpuGeneratedCoverageCheckpointTest#exactCombinationInventoryReproducesEveryCanonicalFixtureExecution")),
                Map.of("disposition-owner", record)), "orphan selector");
        var duplicate = new CpuGeneratedCoverageDispositionRegistry.Entry("duplicate", CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE,
                "ORACLE_PROVED", "outcome=GENERATED",
                "CpuGeneratedCoverageCheckpointTest#exactCombinationInventoryReproducesEveryCanonicalFixtureExecution");
        assertThrows(AssertionError.class, () -> CpuGeneratedCoverageDispositionRegistry.verify(List.of(duplicate, duplicate),
                Map.of("disposition-owner", record)), "duplicate evidence id");
    }

    /**
     * Seals the finite scatter projection used by the direct generated-entry closure.
     *
     * <p>The projection is deliberately by exact owner identity, rather than by a family witness:
     * every one of the 416 inventory records remains individually accountable.  The inventory
     * digest catches stale or hand-edited projections before a semantic closure can claim them.</p>
     */
    @Test void scatterProjectionIsExactCompleteAndBoundToTheCurrentInventoryBytes() throws Exception {
        String inventory = resource("generated-coverage-inventory.tsv");
        assertEquals("527f36de41b64c228dd215c6f3182138b4c70db24c915117c4d7f82743ac41cc",
                hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))));
        Map<String, String[]> rows = parse(inventory);
        var scatter = rows.entrySet().stream().filter(entry -> entry.getKey().startsWith("ordinary:"))
                .filter(entry -> entry.getValue()[2].equals("SCATTER_ELEMENTS")
                        || entry.getValue()[2].equals("SCATTER_ND")).toList();
        assertEquals(416, scatter.size());
        assertEquals(208, scatter.stream().filter(entry -> entry.getValue()[2].equals("SCATTER_ELEMENTS")).count());
        assertEquals(208, scatter.stream().filter(entry -> entry.getValue()[2].equals("SCATTER_ND")).count());
        assertEquals(416, scatter.stream().map(Map.Entry::getKey).distinct().count(), "duplicate projection owner");
        for (var entry : scatter) {
            String[] row = entry.getValue();
            assertEquals("GENERATED", row[21], entry.getKey());
            assertTrue(row[0].contains("/heap-contiguous-scalar") || row[0].contains("/segment-contiguous-vector")
                    || row[0].contains("/mixed-general-parallel-vector")
                    || row[0].contains("/heap-general-materialization-candidate"), entry.getKey());
            assertFalse(row[1].isBlank() || row[18].startsWith("N/A_") || row[19].startsWith("N/A_"), entry.getKey());
        }
        String mutated = inventory.replaceFirst("ordinary:scatter-elements-ADD", "ordinary:scatter-elements-MUTATED");
        assertNotEquals(inventory, mutated);
        assertNotEquals(hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))),
                hex(MessageDigest.getInstance("SHA-256").digest(mutated.getBytes(StandardCharsets.UTF_8))));
        String duplicate = inventory + scatter.getFirst().getKey() + "\t" + String.join("\t", scatter.getFirst().getValue()) + "\n";
        assertThrows(AssertionError.class, () -> parse(duplicate));
    }

    /**
     * Seals the direct-execution ownership join for all ordinary aggregate and scan candidates.
     *
     * <p>The semantic closure defines and invokes each of these 460 contexts.  This projection
     * makes a changed inventory, duplicate identity, stale omission, or orphaned executable
     * context fail before that execution can be mistaken for coverage of a different row.</p>
     */
    @Test void aggregateAndScanProjectionHasExactlyThe460ExecutableOwners() throws Exception {
        String inventory = resource("generated-coverage-inventory.tsv");
        assertEquals("527f36de41b64c228dd215c6f3182138b4c70db24c915117c4d7f82743ac41cc",
                hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))));
        Map<String, String[]> rows = parse(inventory);
        Set<String> forms = Set.of("SUM", "MEAN", "PROD", "AGGREGATE_MIN", "AGGREGATE_MAX",
                "ALL", "ANY", "CUM_SUM", "CUM_PROD");
        Set<String> projected = rows.entrySet().stream().filter(entry -> entry.getKey().startsWith("ordinary:"))
                .filter(entry -> forms.contains(entry.getValue()[2])).map(Map.Entry::getKey)
                .collect(java.util.stream.Collectors.toUnmodifiableSet());
        Set<String> executable = CpuOrdinaryNonPointwiseGeneratedMatrixTest.aggregateOrScanCandidates().stream()
                .map(candidate -> "ordinary:" + candidate.ownerId())
                .collect(java.util.stream.Collectors.toUnmodifiableSet());
        assertEquals(460, projected.size(), "exact inventory projection");
        assertEquals(460, executable.size(), "exact direct-execution owner set");
        assertEquals(executable, projected, "orphan, stale, or relabeled aggregate/scan owner");
        for (String owner : projected) {
            String[] row = rows.get(owner);
            assertEquals("GENERATED", row[21], owner);
            assertFalse(row[18].startsWith("N/A_") || row[19].startsWith("N/A_"), owner);
        }
        String stale = inventory.replaceFirst("ordinary:CUM_PROD/BFLOAT16", "ordinary:CUM_PROD/STALE");
        assertNotEquals(inventory, stale);
        assertNotEquals(hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8))),
                hex(MessageDigest.getInstance("SHA-256").digest(stale.getBytes(StandardCharsets.UTF_8))));
        String duplicate = inventory + projected.iterator().next() + "\t"
                + String.join("\t", rows.get(projected.iterator().next())) + "\n";
        assertThrows(AssertionError.class, () -> parse(duplicate));
        assertEquals(459, projected.stream().filter(owner -> !owner.equals(projected.iterator().next())).count(),
                "removing one owner is an observable stale projection");
    }

    /**
     * Seals the direct-execution join for the finite gather and stable-ordering closure.
     *
     * <p>The source inventory remains authoritative for the 336 identities.  Comparing its exact
     * SHA-bound projection with independently reconstructed contexts makes duplicate, orphan,
     * stale, or manually relabelled owners fail closed.</p>
     */
    @Test void indexingAndOrderingProjectionHasExactlyThe336ExecutableOwners() throws Exception {
        String inventory = resource("generated-coverage-inventory.tsv");
        String digest = hex(MessageDigest.getInstance("SHA-256").digest(inventory.getBytes(StandardCharsets.UTF_8)));
        assertEquals("527f36de41b64c228dd215c6f3182138b4c70db24c915117c4d7f82743ac41cc", digest);
        Map<String, String[]> rows = parse(inventory);
        Set<String> forms = Set.of("GATHER", "GATHER_ELEMENTS", "GATHER_ND", "SORT", "ARGSORT", "TOP_K");
        Set<String> projected = rows.entrySet().stream().filter(entry -> entry.getKey().startsWith("ordinary:"))
                .filter(entry -> forms.contains(entry.getValue()[2])).map(Map.Entry::getKey)
                .collect(java.util.stream.Collectors.toUnmodifiableSet());
        Set<String> executable = CpuOrdinaryNonPointwiseGeneratedMatrixTest.indexingOrOrderingCandidates().stream()
                .map(candidate -> "ordinary:" + candidate.ownerId())
                .collect(java.util.stream.Collectors.toUnmodifiableSet());
        assertEquals(336, projected.size(), "exact inventory projection");
        assertEquals(336, executable.size(), "exact reconstructed owner set");
        assertEquals(executable, projected, "duplicate, orphan, stale, or relabelled owner");
        assertEquals(48, projected.stream().filter(id -> rows.get(id)[2].equals("GATHER")).count());
        assertEquals(48, projected.stream().filter(id -> rows.get(id)[2].equals("GATHER_ELEMENTS")).count());
        assertEquals(48, projected.stream().filter(id -> rows.get(id)[2].equals("GATHER_ND")).count());
        assertEquals(48, projected.stream().filter(id -> rows.get(id)[2].equals("SORT")).count());
        assertEquals(48, projected.stream().filter(id -> rows.get(id)[2].equals("ARGSORT")).count());
        assertEquals(96, projected.stream().filter(id -> rows.get(id)[2].equals("TOP_K")).count());
        for (String owner : projected) {
            String[] row = rows.get(owner);
            assertEquals("GENERATED", row[21], owner);
            assertFalse(row[18].startsWith("N/A_") || row[19].startsWith("N/A_"), owner);
        }
        String stale = inventory.replaceFirst("ordinary:gather/BFLOAT16/INT32", "ordinary:gather/STALE");
        assertNotEquals(digest, hex(MessageDigest.getInstance("SHA-256").digest(stale.getBytes(StandardCharsets.UTF_8))));
        String duplicate = inventory + projected.iterator().next() + "\t"
                + String.join("\t", rows.get(projected.iterator().next())) + "\n";
        assertThrows(AssertionError.class, () -> parse(duplicate));
        Set<String> orphaned = new java.util.HashSet<>(projected);
        orphaned.remove(projected.iterator().next());
        assertNotEquals(executable, orphaned, "one stale omission must fail the owner join");
    }

    private static String serialize(Map<String, CpuGeneratedCoverageEvidenceRegistry.Record> records) {
        StringBuilder text = new StringBuilder(HEADER);
        records.forEach((owner, record) -> text.append(String.join("\t", owner, record.evidenceKey(),
                record.operationForm(), record.loweredForm(), record.descriptorRoles(), record.boundaryIds(),
                record.virtualValues(), Integer.toString(record.unitCount()), Integer.toString(record.affineAddressPairCount()),
                record.orderedCarrierTypes(), record.layoutAccessRegime(), record.requestedStrategy(),
                record.selectedStrategy(), Boolean.toString(record.materializationCandidate()),
                Integer.toString(record.materializationsSelected()), Boolean.toString(record.providerSupported()),
                Boolean.toString(record.preparerAdmitted()), record.preparedIrStructuralKey(),
                record.generatedEntryDescriptor(), record.classHash(), record.normalizedBodyKey(), record.outcome(),
                record.reason(), record.ordinarySelection(), record.fallbackDisposition(), canonicalInventoryDisposition(record,
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE), canonicalInventoryDisposition(record,
                        CpuGeneratedCoverageDispositionRegistry.Kind.PERFORMANCE))).append('\n'));
        return text.toString();
    }

    /** Keeps the SHA-frozen inventory as an execution baseline; live promotion belongs to the registry. */
    private static String canonicalInventoryDisposition(CpuGeneratedCoverageEvidenceRegistry.Record record,
            CpuGeneratedCoverageDispositionRegistry.Kind kind) {
        return record.outcome().equals("GENERATED")
                ? kind == CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE
                ? "PARTIAL_CLASSFILE_NO_CLEAN_JAVA_ORACLE" : "PARTIAL_NO_REPRESENTATIVE_BENCHMARK"
                : "N/A_NO_GENERATED_CODE";
    }

    /** Reconciles the mutable evidence disposition ledger with the immutable execution inventory. */
    private static void assertLiveDispositionResolution(
            Map<String, CpuGeneratedCoverageEvidenceRegistry.Record> observed) {
        CpuGeneratedCoverageDispositionRegistry.verifyCanonicalRegistry(observed);
        long proved = 0, partial = 0, performancePartial = 0;
        for (var record : observed.values()) {
            if (!record.outcome().equals("GENERATED")) continue;
            String oracle = CpuGeneratedCoverageDispositionRegistry.resolve(
                    CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, record).disposition();
            String performance = CpuGeneratedCoverageDispositionRegistry.resolve(
                    CpuGeneratedCoverageDispositionRegistry.Kind.PERFORMANCE, record).disposition();
            if (isCpu0009cOwner(record)) {
                assertEquals("ORACLE_PROVED", oracle, record.occurrenceId());
                proved++;
            } else {
                assertEquals("PARTIAL_CLASSFILE_NO_CLEAN_JAVA_ORACLE", oracle, record.occurrenceId());
                partial++;
            }
            assertEquals("PARTIAL_NO_REPRESENTATIVE_BENCHMARK", performance, record.occurrenceId());
            performancePartial++;
        }
        assertEquals(2_252L, proved);
        assertEquals(15_211L, partial);
        assertEquals(17_463L, performancePartial);
        var scoped = observed.values().stream().filter(CpuGeneratedCoverageCheckpointTest::isCpu0009cOwner)
                .findFirst().orElseThrow();
        var reversed = new java.util.ArrayList<>(CpuGeneratedCoverageDispositionRegistry.entries());
        java.util.Collections.reverse(reversed);
        assertEquals(CpuGeneratedCoverageDispositionRegistry.resolve(CpuGeneratedCoverageDispositionRegistry.entries(),
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, scoped).id(),
                CpuGeneratedCoverageDispositionRegistry.resolve(reversed,
                        CpuGeneratedCoverageDispositionRegistry.Kind.ORACLE, scoped).id(),
                "scoped selector precedence is independent of TSV row order");
    }

    private static boolean isCpu0009cOwner(CpuGeneratedCoverageEvidenceRegistry.Record record) {
        if (record.occurrenceId().startsWith("affine-matrix:")) return true;
        if (!record.occurrenceId().startsWith("ordinary:")) return false;
        return Set.of("PAD", "TILE", "CONCAT", "STACK", "SLICE_UPDATE", "UNFOLD_AXIS", "UNFOLD2D",
                "GATHER", "GATHER_ELEMENTS", "GATHER_ND", "ONE_HOT", "SCATTER_ELEMENTS", "SCATTER_ND",
                "DROPOUT", "INITIAL_STATE").contains(record.operationForm());
    }

    private static Map<String, String[]> parse(String text) {
        assertTrue(text.endsWith("\n") && !text.contains("\r"), "canonical LF resource");
        String[] lines = text.split("\n", -1);
        assertEquals(HEADER.stripTrailing(), lines[0]);
        Map<String, String[]> rows = new LinkedHashMap<>();
        for (int line = 1; line < lines.length - 1; line++) {
            String[] row = lines[line].split("\t", -1);
            assertEquals(27, row.length, "line " + (line + 1));
            for (String field : row) assertFalse(field.isBlank(), "blank inventory field at line " + (line + 1));
            assertNull(rows.put(row[0], row), "duplicate owner: " + row[0]);
        }
        return rows;
    }

    private static String resource(String name) throws Exception {
        try (InputStream stream = CpuGeneratedCoverageCheckpointTest.class.getResourceAsStream(BASE + name)) {
            assertNotNull(stream, name);
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static void dumpIfRequested(String actual) throws Exception {
        String path = System.getProperty("synaptik.cpu.coverage.inventory.dump");
        if (path == null || path.isBlank()) path = System.getenv("SYNAPTIK_CPU_COVERAGE_INVENTORY_DUMP");
        if (path != null && !path.isBlank()) Files.writeString(Path.of(path), actual, StandardCharsets.UTF_8);
    }

    private static String hex(byte[] bytes) {
        StringBuilder result = new StringBuilder(bytes.length * 2);
        for (byte value : bytes) result.append(String.format("%02x", value));
        return result.toString();
    }

}
