package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.pho001.synaptik.backend.cpu.internal.cache.CpuKernelSpecialization.CarrierAccess;
import io.github.pho001.synaptik.backend.cpu.internal.ir.CpuMatmulIr;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuMatmulLowering;
import io.github.pho001.synaptik.backend.cpu.internal.lowering.CpuScatterLoweringTest;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionAnalysisInputs;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparationPlan;
import io.github.pho001.synaptik.backend.cpu.internal.prepare.CpuPartitionPreparer;
import io.github.pho001.synaptik.model.datatype.DataType;
import io.github.pho001.synaptik.model.datatype.DataTypePromotion;
import io.github.pho001.synaptik.model.datatype.ScalarValue;
import io.github.pho001.synaptik.model.graph.GraphValue;
import io.github.pho001.synaptik.model.layout.LayoutDescriptor;
import io.github.pho001.synaptik.model.operation.NoOperationAttrs;
import io.github.pho001.synaptik.model.operation.Operation;
import io.github.pho001.synaptik.model.operation.linalg.MatmulKind;
import io.github.pho001.synaptik.model.shape.Shape;
import io.github.pho001.synaptik.model.tensor.TensorDescriptor;
import io.github.pho001.synaptik.planning.memory.LogicalMemoryRequirement;
import io.github.pho001.synaptik.prepare.analysis.PrepareContext;
import java.lang.foreign.MemorySegment;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;

/** Executes every finite MATMUL inventory row against a test-local clean-Java oracle. */
class CpuMatmulSemanticClosureTest {
    private static final List<DataType> NUMERIC = List.of(DataType.FLOAT64, DataType.FLOAT32,
            DataType.BFLOAT16, DataType.INT64, DataType.INT32);
    private static final List<Shape[]> FORMS = List.of(new Shape[] {Shape.of(3), Shape.of(3)},
            new Shape[] {Shape.of(2, 3), Shape.of(3)}, new Shape[] {Shape.of(3), Shape.of(3, 4)},
            new Shape[] {Shape.of(2, 3), Shape.of(3, 4)},
            new Shape[] {Shape.of(2, 2, 3), Shape.of(2, 3, 4)},
            new Shape[] {Shape.of(1, 2, 3), Shape.of(2, 3, 4)});
    private static final CpuPartitionAnalysisInputs.MaterializationPolicy MATERIALIZATION =
            new CpuPartitionAnalysisInputs.MaterializationPolicy(true, 0, 1, 20, 1, 3,
                    1_000_000, 1, 1);

    @Test void everyMatmulInventoryRowDefinesAndInvokesItsActualGeneratedEntryAgainstIndependentOracle()
            throws Throwable {
        int raw = 0;
        Set<String> owners = new TreeSet<>();
        for (DataType left : NUMERIC) for (DataType right : NUMERIC) {
            if (left.category() != right.category()) continue;
            for (Shape[] form : FORMS) for (Request request : Request.values()) {
                Fixture fixture = new Fixture(left, right, form[0], form[1], request);
                assertTrue(owners.add(fixture.owner()), "duplicate semantic witness " + fixture);
                invokeAndCompare(fixture);
                raw++;
            }
        }
        assertEquals(390, raw, "one exact generated definition/invocation per MATMUL inventory row");
        assertEquals(inventoryOwners(), owners, "complete non-projecting MATMUL inventory-owner join");
    }

    private static void invokeAndCompare(Fixture fixture) throws Throwable {
        PrepareContext<CpuPartitionAnalysisInputs> context = configure(base(fixture), fixture.request);
        CpuPartitionPreparationPlan plan = new CpuPartitionPreparer().analyze(context).plan();
        var unit = plan.units().getFirst();
        var route = unit.portablePlan();
        assertEquals(0, plan.materializations().size(), fixture + " materialization remains unselected");
        assertTrue(route.specialization().matmulIr().isPresent(), fixture.toString());
        CpuMatmulIr matmul = route.specialization().matmulIr().orElseThrow();
        var generator = new CpuClassFileKernelGenerator();
        byte[] first = generator.generateClassBytes(route.specialization(), route.kernelIr());
        byte[] second = generator.generateClassBytes(route.specialization(), route.kernelIr());
        assertArrayEquals(first, second, fixture + " deterministic generated bytes");
        var artifact = generator.defineClassBytes(route.specialization(), first);

        List<Storage> storage = new ArrayList<>();
        for (int i = 0; i < matmul.encodedKernelIr().values().size(); i++) storage.add(new Storage(
                route.specialization().boundaryDataTypes().get(i), route.specialization().carrierPattern().get(i)));
        fillInputs(context, storage);
        Storage output = storage.getLast(); output.fill(-91.25d);
        double[][] beforeInputs = storage.subList(0, storage.size() - 1).stream()
                .map(Storage::snapshot).toArray(double[][]::new);
        double[] expected = output.snapshot();
        CpuMatmulLowering.Geometry geometry = unit.matmulGeometry().orElseThrow();
        oracle(geometry, storage.get(0), storage.get(1), output, expected);
        Object[] arguments = storage.stream().map(Storage::argument).toArray();
        long[] packed = geometry.pack(0, 0, 0);
        long work = unit.elementCount();
        if (fixture.request.parallel && work > 1) {
            long middle = work / 2;
            entry(artifact, arguments, packed, middle, work);
            entry(artifact, arguments, packed, 0, middle);
        } else entry(artifact, arguments, packed, 0, work);
        assertStorage(expected, output, fixture);
        double[][] afterInputs = storage.subList(0, storage.size() - 1).stream()
                .map(Storage::snapshot).toArray(double[][]::new);
        assertTrue(Arrays.deepEquals(beforeInputs, afterInputs), fixture + " input mutation");
    }

    private static void entry(CpuGeneratedKernel artifact, Object[] boundaries, long[] geometry,
            long start, long end) throws Throwable {
        Object[] arguments = new Object[boundaries.length + 3];
        System.arraycopy(boundaries, 0, arguments, 0, boundaries.length);
        arguments[boundaries.length] = geometry;
        arguments[boundaries.length + 1] = start;
        arguments[boundaries.length + 2] = end;
        artifact.entryPoint().invokeWithArguments(arguments);
    }

    private static PrepareContext<CpuPartitionAnalysisInputs> base(Fixture f) {
        Shape output = matmulOutput(f.leftShape, f.rightShape);
        return CpuScatterLoweringTest.context(new Operation(MatmulKind.MATMUL, NoOperationAttrs.INSTANCE),
                List.of(0, 1), List.of(descriptor(f.left, f.leftShape), descriptor(f.right, f.rightShape)),
                descriptor(DataTypePromotion.promoteNumeric(f.left, f.right), output));
    }

    private static PrepareContext<CpuPartitionAnalysisInputs> configure(
            PrepareContext<CpuPartitionAnalysisInputs> base, Request request) {
        List<GraphValue> values = new ArrayList<>();
        List<LogicalMemoryRequirement> memory = new ArrayList<>();
        for (int i = 0; i < base.values().size(); i++) {
            TensorDescriptor descriptor = base.values().get(i).descriptor();
            if (request.general && descriptor.shape().rank() != 0) {
                long[] strides = descriptor.layout().orElseThrow().strides();
                for (int axis = 0; axis < strides.length; axis++) strides[axis] *= 2;
                descriptor = new TensorDescriptor(descriptor.dataType(), descriptor.shape(),
                        Optional.of(LayoutDescriptor.of(descriptor.shape(), strides, 1, true)), false);
            }
            GraphValue value = new GraphValue(base.values().get(i).id(), descriptor);
            values.add(value);
            var requirement = base.memoryRequirements().get(i);
            memory.add(new LogicalMemoryRequirement(requirement.valueId(), descriptor,
                    requirement.producerPartition(), requirement.consumerPartitions(), requirement.graphOutput()));
        }
        List<CarrierAccess> carriers = new ArrayList<>();
        for (int i = 0; i < values.size(); i++) carriers.add(request.segment || request.mixed && i % 2 == 1
                ? CarrierAccess.MEMORY_SEGMENT
                : CpuGeneratedDirectEvidenceClosureTest.heapCarrier(values.get(i).descriptor().dataType()));
        return new PrepareContext<>(base.partition(), base.nodes(), values, memory, base.constants(),
                new CpuPartitionAnalysisInputs(false, carriers, request.execution,
                        request.materialization ? MATERIALIZATION
                                : CpuPartitionAnalysisInputs.MaterializationPolicy.DISABLED));
    }

    private static void fillInputs(PrepareContext<CpuPartitionAnalysisInputs> context,
            List<Storage> storage) {
        for (int boundary = 0; boundary < 2; boundary++) {
            TensorDescriptor descriptor = context.values().get(boundary).descriptor();
            long count = elements(descriptor.shape());
            LayoutDescriptor layout = descriptor.layout().orElseThrow();
            for (int logical = 0; logical < count; logical++) storage.get(boundary)
                    .set(offset(layout, descriptor.shape(), logical), (boundary == 0 ? .25 : -.5) + logical * .125);
        }
    }

    /* Independent scalar oracle: no lowering and no production/reference-kernel call. */
    private static void oracle(CpuMatmulLowering.Geometry g, Storage left, Storage right,
            Storage output, double[] expected) {
        long[] batches = g.batchExtents();
        for (long batch = 0; batch < g.batchCount(); batch++) for (long row = 0; row < g.m(); row++)
            for (long column = 0; column < g.n(); column++) {
                long leftBase = g.leftOffset(), rightBase = g.rightOffset(), outputBase = g.resultOffset();
                long remaining = batch;
                long[] ls = g.leftBatchStrides(), rs = g.rightBatchStrides(), os = g.resultBatchStrides();
                for (int axis = batches.length - 1; axis >= 0; axis--) {
                    long coordinate = remaining % batches[axis]; remaining /= batches[axis];
                    leftBase += coordinate * ls[axis]; rightBase += coordinate * rs[axis]; outputBase += coordinate * os[axis];
                }
                double sum = 0;
                for (long inner = 0; inner < g.k(); inner++) {
                    double product = narrow(g.resultType(), left.get(leftBase + row * g.leftMStride() + inner * g.leftKStride()))
                            * narrow(g.resultType(), right.get(rightBase + inner * g.rightKStride() + column * g.rightNStride()));
                    sum = narrow(g.resultType(), sum + narrow(g.resultType(), product));
                }
                expected[(int) (outputBase + row * g.resultMStride() + column * g.resultNStride())] = sum;
            }
    }

    private static Set<String> inventoryOwners() throws Exception {
        try (var stream = CpuMatmulSemanticClosureTest.class.getResourceAsStream(
                "/io/github/pho001/synaptik/backend/cpu/internal/codegen/emit/generated-coverage-inventory.tsv")) {
            assertTrue(stream != null, "inventory resource");
            Set<String> owners = new TreeSet<>();
            String[] lines = new String(stream.readAllBytes(), StandardCharsets.UTF_8).split("\\n", -1);
            for (int line = 1; line < lines.length - 1; line++) {
                String[] fields = lines[line].split("\\t", -1);
                if (fields[2].equals("MATMUL")) assertTrue(owners.add(fields[0]), "duplicate inventory owner " + fields[0]);
            }
            assertEquals(390, owners.size());
            return owners;
        }
    }

    private static void assertStorage(double[] expected, Storage actual, Fixture f) {
        for (int i = 0; i < expected.length; i++) assertEquals(quantize(actual.type, expected[i]), actual.get(i),
                actual.type == DataType.BFLOAT16 ? .02 : actual.type == DataType.FLOAT32 ? 2e-5 : 0,
                f + " physical " + i);
    }

    private static double quantize(DataType type, double value) { return switch (type) {
        case BFLOAT16 -> Float.intBitsToFloat((ScalarValue.bfloat16((float) value).bfloat16Bits() & 0xffff) << 16);
        case FLOAT32 -> (float) value;
        case INT32 -> (int) value;
        case INT64 -> (long) value;
        default -> value;
    }; }
    private static double narrow(DataType type, double value) { return switch (type) {
        case FLOAT64 -> value;
        case INT64 -> (long) value;
        case INT32 -> (int) value;
        default -> (float) value;
    }; }
    private static long offset(LayoutDescriptor layout, Shape shape, long linear) {
        long[] dimensions = shape.toLongArray(), strides = layout.strides(); long value = layout.storageOffset();
        for (int axis = dimensions.length - 1; axis >= 0; axis--) { value += (linear % dimensions[axis]) * strides[axis]; linear /= dimensions[axis]; }
        return value;
    }
    private static long elements(Shape shape) { long result = 1; for (long value : shape.toLongArray()) result *= value; return result; }
    private static TensorDescriptor descriptor(DataType type, Shape shape) { return new TensorDescriptor(type, shape, Optional.of(LayoutDescriptor.contiguous(shape)), false); }
    private static Shape matmulOutput(Shape left, Shape right) { var dims = new ArrayList<Long>(); long[] a = left.toLongArray(), b = right.toLongArray();
        int ar = a.length, br = b.length, batch = Math.max(0, Math.max(ar - 2, br - 2));
        for (int i = 0; i < batch; i++) { long x = i < batch - Math.max(0, ar - 2) ? 1 : a[i - (batch - Math.max(0, ar - 2))]; long y = i < batch - Math.max(0, br - 2) ? 1 : b[i - (batch - Math.max(0, br - 2))]; dims.add(Math.max(x, y)); }
        if (ar > 1) dims.add(a[ar - 2]); if (br > 1) dims.add(b[br - 1]); return Shape.of(dims.stream().mapToLong(Long::longValue).toArray()); }

    private enum Request {
        HEAP_CONTIGUOUS_SCALAR(false, false, false, false, CpuGeneratedDirectEvidenceClosureTest.scalar(1)),
        SEGMENT_CONTIGUOUS_VECTOR(true, false, false, false, CpuGeneratedDirectEvidenceClosureTest.vector(1)),
        MIXED_GENERAL_PARALLEL_VECTOR(false, true, true, false, CpuGeneratedDirectEvidenceClosureTest.vector(4)),
        HEAP_GENERAL_PARALLEL_SCALAR(false, false, true, false, CpuGeneratedDirectEvidenceClosureTest.scalar(4)),
        HEAP_GENERAL_MATERIALIZATION(false, false, true, true, CpuGeneratedDirectEvidenceClosureTest.scalar(1));
        final boolean segment, mixed, general, materialization, parallel;
        final CpuPartitionAnalysisInputs.PortableExecutionConfig execution;
        Request(boolean segment, boolean mixed, boolean general, boolean materialization,
                CpuPartitionAnalysisInputs.PortableExecutionConfig execution) {
            this.segment = segment; this.mixed = mixed; this.general = general; this.materialization = materialization;
            this.parallel = execution.availableParallelism() > 1; this.execution = execution;
        }
    }
    private record Fixture(DataType left, DataType right, Shape leftShape, Shape rightShape, Request request) {
        String owner() { return "specialized:matmul/" + left + '/' + right + '/' + leftShape + '/' + rightShape + '/' + request; }
    }
    private static final class Storage {
        final DataType type; final CarrierAccess carrier; final Object heap; final MemorySegment segment;
        Storage(DataType type, CarrierAccess carrier) { this.type = type; this.carrier = carrier; this.heap = switch (type) {
            case FLOAT64 -> new double[256]; case FLOAT32 -> new float[256]; case BFLOAT16 -> new short[256];
            case INT32 -> new int[256]; case INT64 -> new long[256]; default -> throw new AssertionError(type); };
            this.segment = switch (type) { case FLOAT64 -> MemorySegment.ofArray((double[]) heap); case FLOAT32 -> MemorySegment.ofArray((float[]) heap);
                case BFLOAT16 -> MemorySegment.ofArray((short[]) heap); case INT32 -> MemorySegment.ofArray((int[]) heap);
                case INT64 -> MemorySegment.ofArray((long[]) heap); default -> throw new AssertionError(type); }; }
        Object argument() { return carrier == CarrierAccess.MEMORY_SEGMENT ? segment : heap; }
        void fill(double value) { for (int i = 0; i < 256; i++) set(i, value); }
        void set(long index, double value) { switch (type) { case FLOAT64 -> ((double[]) heap)[(int) index] = value; case FLOAT32 -> ((float[]) heap)[(int) index] = (float) value;
            case BFLOAT16 -> ((short[]) heap)[(int) index] = ScalarValue.bfloat16((float) value).bfloat16Bits(); case INT32 -> ((int[]) heap)[(int) index] = (int) value;
            case INT64 -> ((long[]) heap)[(int) index] = (long) value; default -> throw new AssertionError(type); } }
        double get(long index) { return switch (type) { case FLOAT64 -> ((double[]) heap)[(int) index]; case FLOAT32 -> ((float[]) heap)[(int) index];
            case BFLOAT16 -> Float.intBitsToFloat((((short[]) heap)[(int) index] & 0xffff) << 16); case INT32 -> ((int[]) heap)[(int) index];
            case INT64 -> ((long[]) heap)[(int) index]; default -> throw new AssertionError(type); }; }
        double[] snapshot() { double[] result = new double[256]; for (int i = 0; i < result.length; i++) result[i] = get(i); return result; }
    }
}
