package io.github.pho001.synaptik.backend.cpu.execution;

import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.AccessFlag;
import java.util.List;
import java.util.Objects;

/**
 * Stateless owner of Java 26 class emission, byte verification, hidden-class definition, and
 * exact static-handle resolution. Emission and definition are separate cold operations so a
 * CPU-private durable store can persist only deterministic verified bytes and revalidate them
 * before definition. This owner performs no route selection, scheduling, or Model-operation
 * lowering.
 */
final class CpuClassFileKernelGenerator {
    /**
     * Generates and defines one distinct hidden kernel artifact.
     *
     * @param specialization complete validated specialization; must not be {@code null}
     * @param familyEmitter family callback with an exactly matching lowering fingerprint; must
     *     not be {@code null}
     * @return a new immutable hidden-class artifact retaining its lookup, class, exact handle,
     *     specialization, and defensive class-byte snapshot; never cached or {@code null}
     * @throws NullPointerException if either argument is {@code null}
     * @throws IllegalArgumentException if fingerprints differ, generated bytes fail verification,
     *     or hidden definition and exact entry resolution fail
     */
    CpuGeneratedKernel generate(CpuKernelSpecialization specialization,
            CpuFamilyKernelEmitter familyEmitter) {
        return defineClassBytes(specialization,
                generateClassBytes(specialization, familyEmitter));
    }

    /**
     * Emits deterministic verified class bytes without defining a class.
     *
     * @param specialization complete validated specialization; must not be {@code null}
     * @param familyEmitter family callback with an exactly matching lowering fingerprint; must
     *     not be {@code null}
     * @return a new byte array containing the complete verified class file; never {@code null}
     * @throws NullPointerException if either argument is {@code null}
     * @throws IllegalArgumentException if fingerprints differ or generated bytes fail verification
     * @throws RuntimeException if family emission throws an unchecked exception
     * @throws Error if family emission throws an error
     */
    byte[] generateClassBytes(CpuKernelSpecialization specialization,
            CpuFamilyKernelEmitter familyEmitter) {
        Objects.requireNonNull(specialization, "specialization");
        Objects.requireNonNull(familyEmitter, "familyEmitter");
        if (!specialization.loweringFingerprint().equals(familyEmitter.loweringFingerprint())) {
            throw new IllegalArgumentException(
                    "familyEmitter lowering fingerprint does not match specialization");
        }
        try {
            ClassDesc generatedClass = ClassDesc.of(
                    CpuGeneratorSchema.generatedBinaryName(specialization));
            MethodTypeDesc entryDescriptor = MethodTypeDesc.ofDescriptor(
                    specialization.entryType().descriptorString());
            byte[] bytes = ClassFile.of().build(generatedClass, classBuilder -> classBuilder
                    .withVersion(specialization.classFileMajorVersion(),
                            CpuGeneratorSchema.CLASSFILE_MINOR_VERSION)
                    .withFlags(AccessFlag.FINAL)
                    .withMethod(CpuGeneratorSchema.GENERATED_ENTRY_NAME, entryDescriptor,
                            AccessFlag.STATIC.mask(), method ->
                            method.withCode(code -> {
                                try {
                                    specialization.executionMode().emit(
                                            code, specialization, familyEmitter);
                                }
                                catch (RuntimeException | Error failure) {
                                    throw new EmissionFailure(failure);
                                }
                            })));
            verifyClassBytes(specialization, bytes);
            return bytes;
        } catch (EmissionFailure failure) {
            if (failure.getCause() instanceof RuntimeException runtime) throw runtime;
            throw (Error) failure.getCause();
        }
    }

    /**
     * Revalidates stored bytes, defines one hidden nestmate, and resolves its exact static entry.
     *
     * @param specialization complete validated compatibility description; must not be null
     * @param classBytes non-null complete class bytes; validated before definition and copied by
     *     the returned artifact
     * @return a fresh immutable loaded artifact retaining the hidden class and exact handle;
     *     never {@code null}
     * @throws NullPointerException if either argument is {@code null}
     * @throws IllegalArgumentException if verification, exact shape, hidden definition, or exact
     *     entry resolution fails
     */
    CpuGeneratedKernel defineClassBytes(CpuKernelSpecialization specialization, byte[] classBytes) {
        Objects.requireNonNull(specialization, "specialization");
        Objects.requireNonNull(classBytes, "classBytes");
        verifyClassBytes(specialization, classBytes);
        try {
            MethodHandles.Lookup lookup = MethodHandles.lookup().defineHiddenClass(
                    classBytes, false, MethodHandles.Lookup.ClassOption.NESTMATE);
            Class<?> hiddenClass = lookup.lookupClass();
            MethodHandle entry = lookup.findStatic(hiddenClass,
                    CpuGeneratorSchema.GENERATED_ENTRY_NAME, specialization.entryType());
            return new CpuGeneratedKernel(specialization, lookup, hiddenClass, entry,
                    specialization.entryType(), classBytes);
        } catch (IllegalArgumentException | ReflectiveOperationException failure) {
            throw new IllegalArgumentException("generated kernel definition failed", failure);
        }
    }

    private void verifyClassBytes(CpuKernelSpecialization specialization, byte[] classBytes) {
        List<VerifyError> errors;
        ClassModel model;
        try {
            errors = ClassFile.of().verify(classBytes);
            if (!errors.isEmpty()) {
                var message = new StringBuilder("generated class verification failed");
                for (int index = 0; index < errors.size(); index++) {
                    message.append(" [").append(index).append("] ").append(errors.get(index));
                }
                throw new IllegalArgumentException(message.toString());
            }
            model = ClassFile.of().parse(classBytes);
        } catch (IllegalArgumentException failure) {
            if (failure.getMessage() != null
                    && failure.getMessage().startsWith("generated class verification failed")) {
                throw failure;
            }
            throw new IllegalArgumentException("generated class verification failed", failure);
        }
        String expectedInternalName = CpuGeneratorSchema.generatedBinaryName(specialization)
                .replace('.', '/');
        boolean exactClassFlags = model.flags().flags().equals(java.util.Set.of(AccessFlag.FINAL));
        boolean exactMethod = model.methods().size() == 1
                && model.methods().getFirst().methodName().stringValue()
                        .equals(CpuGeneratorSchema.GENERATED_ENTRY_NAME)
                && model.methods().getFirst().methodType().stringValue()
                        .equals(specialization.entryType().descriptorString())
                && model.methods().getFirst().flags().flags().equals(java.util.Set.of(AccessFlag.STATIC))
                && model.methods().getFirst().code().isPresent();
        if (model.majorVersion() != specialization.classFileMajorVersion()
                || model.minorVersion() != CpuGeneratorSchema.CLASSFILE_MINOR_VERSION
                || !model.thisClass().asInternalName().equals(expectedInternalName)
                || model.superclass().isEmpty()
                || !model.superclass().orElseThrow().asInternalName().equals("java/lang/Object")
                || !exactClassFlags || !model.interfaces().isEmpty() || !model.fields().isEmpty()
                || !exactMethod) {
            throw new IllegalArgumentException("generated class shape does not match specialization");
        }
    }

    /** Internal marker used only to preserve exact unchecked family-emitter failures. */
    private static final class EmissionFailure extends RuntimeException {
        private EmissionFailure(Throwable cause) { super(cause); }
    }
}
