package io.github.pho001.synaptik.backend.cpu.execution;

import java.lang.classfile.ClassFile;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.AccessFlag;
import java.util.List;
import java.util.Objects;

/**
 * Stateless owner of Java 26 class emission, byte verification, hidden-class definition, and
 * exact static-handle resolution. Each call returns a fresh identity artifact; this foundation
 * performs no caching, route selection, preparation, scheduling, or Model-operation lowering.
 */
final class CpuClassFileKernelGenerator {
    /**
     * Generates and defines one distinct hidden kernel artifact.
     *
     * @param specialization complete validated specialization; must not be {@code null}
     * @param familyEmitter family callback with an exactly matching lowering fingerprint; must
     *     not be {@code null}
     * @return a new immutable hidden-class artifact retaining its lookup, class, exact handle,
     *     specialization, and defensive class-byte snapshot; never cached or {@code null}
     * @throws NullPointerException if either argument is {@code null}
     * @throws IllegalArgumentException if fingerprints differ, generated bytes fail verification,
     *     or hidden definition and exact entry resolution fail
     */
    CpuGeneratedKernel generate(CpuKernelSpecialization specialization,
            CpuFamilyKernelEmitter familyEmitter) {
        Objects.requireNonNull(specialization, "specialization");
        Objects.requireNonNull(familyEmitter, "familyEmitter");
        if (!specialization.loweringFingerprint().equals(familyEmitter.loweringFingerprint())) {
            throw new IllegalArgumentException(
                    "familyEmitter lowering fingerprint does not match specialization");
        }
        try {
            String suffix = specialization.specializationFingerprint().toString();
            ClassDesc generatedClass = ClassDesc.of(
                    "io.github.pho001.synaptik.backend.cpu.execution.CpuGenerated$" + suffix);
            MethodTypeDesc entryDescriptor = MethodTypeDesc.ofDescriptor(
                    specialization.entryType().descriptorString());
            byte[] bytes = ClassFile.of().build(generatedClass, classBuilder -> classBuilder
                    .withVersion(specialization.classFileMajorVersion(), 0)
                    .withFlags(AccessFlag.FINAL)
                    .withMethod("invoke", entryDescriptor, AccessFlag.STATIC.mask(), method ->
                            method.withCode(code -> {
                                try {
                                    specialization.executionMode().emit(
                                            code, specialization, familyEmitter);
                                }
                                catch (RuntimeException | Error failure) {
                                    throw new EmissionFailure(failure);
                                }
                            })));
            List<VerifyError> errors = ClassFile.of().verify(bytes);
            if (!errors.isEmpty()) {
                var message = new StringBuilder("generated class verification failed");
                for (int index = 0; index < errors.size(); index++) {
                    message.append(" [").append(index).append("] ").append(errors.get(index));
                }
                throw new IllegalArgumentException(message.toString());
            }
            MethodHandles.Lookup lookup = MethodHandles.lookup().defineHiddenClass(
                    bytes, false, MethodHandles.Lookup.ClassOption.NESTMATE);
            Class<?> hiddenClass = lookup.lookupClass();
            MethodHandle entry = lookup.findStatic(hiddenClass, "invoke", specialization.entryType());
            return new CpuGeneratedKernel(specialization, lookup, hiddenClass, entry,
                    specialization.entryType(), bytes);
        } catch (EmissionFailure failure) {
            if (failure.getCause() instanceof RuntimeException runtime) throw runtime;
            throw (Error) failure.getCause();
        } catch (IllegalArgumentException failure) {
            if (failure.getMessage() != null
                    && failure.getMessage().startsWith("generated class verification failed")) throw failure;
            throw new IllegalArgumentException("generated kernel definition failed", failure);
        } catch (ReflectiveOperationException failure) {
            throw new IllegalArgumentException("generated kernel definition failed", failure);
        }
    }

    /** Internal marker used only to preserve exact unchecked family-emitter failures. */
    private static final class EmissionFailure extends RuntimeException {
        private EmissionFailure(Throwable cause) { super(cause); }
    }
}
