package io.github.pho001.synaptik.backend.cpu.execution;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.Objects;

/**
 * Immutable identity artifact retaining one hidden class, its full-privilege lookup, exact static
 * entry handle, specialization, and deterministic bytes. Reachability of this object retains the
 * hidden artifact; it owns no close lifecycle, promises no unloading time, and uses ordinary
 * identity equality.
 */
final class CpuGeneratedKernel {
    private final CpuKernelSpecialization specialization;
    private final MethodHandles.Lookup hiddenLookup;
    private final Class<?> hiddenClass;
    private final MethodHandle entryPoint;
    private final MethodType entryType;
    private final byte[] classBytes;

    /**
     * Retains one internally consistent generated artifact.
     * @param specialization non-null exact specialization
     * @param hiddenLookup non-null lookup whose lookup class is {@code hiddenClass}
     * @param hiddenClass non-null hidden class declaring the entry point
     * @param entryPoint non-null direct static handle declared by {@code hiddenClass}
     * @param entryType non-null exact handle and specialization method type
     * @param classBytes non-null generated bytes; copied defensively
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalArgumentException if lookup, owner, or method types are inconsistent
     */
    CpuGeneratedKernel(CpuKernelSpecialization specialization, MethodHandles.Lookup hiddenLookup,
            Class<?> hiddenClass, MethodHandle entryPoint, MethodType entryType, byte[] classBytes) {
        this.specialization = Objects.requireNonNull(specialization, "specialization");
        this.hiddenLookup = Objects.requireNonNull(hiddenLookup, "hiddenLookup");
        this.hiddenClass = Objects.requireNonNull(hiddenClass, "hiddenClass");
        this.entryPoint = Objects.requireNonNull(entryPoint, "entryPoint");
        this.entryType = Objects.requireNonNull(entryType, "entryType");
        Objects.requireNonNull(classBytes, "classBytes");
        if (hiddenLookup.lookupClass() != hiddenClass) throw new IllegalArgumentException(
                "hiddenLookup lookup class must equal hiddenClass");
        if (!entryPoint.type().equals(entryType) || !entryType.equals(specialization.entryType()))
            throw new IllegalArgumentException("entry type must match handle and specialization");
        if (hiddenLookup.revealDirect(entryPoint).getDeclaringClass() != hiddenClass)
            throw new IllegalArgumentException("entry point must be declared by hiddenClass");
        this.classBytes = classBytes.clone();
    }
    /** Returns the generation specialization.
     * @return exact non-null immutable specialization retained by this artifact */ CpuKernelSpecialization specialization() { return specialization; }
    /** Returns the lookup retaining full privilege for the hidden class.
     * @return exact non-null full-privilege hidden lookup retained by this artifact */ MethodHandles.Lookup hiddenLookup() { return hiddenLookup; }
    /** Returns the generated hidden class.
     * @return exact non-null hidden class declared by {@link #hiddenLookup()} */ Class<?> hiddenClass() { return hiddenClass; }
    /** Returns the directly invocable entry point.
     * @return exact non-null direct static entry handle declared by {@link #hiddenClass()} */ MethodHandle entryPoint() { return entryPoint; }
    /** Returns the exact entry signature.
     * @return exact non-null entry type shared by the handle and specialization */ MethodType entryType() { return entryType; }
    /** Returns generated bytes without exposing retained mutable state.
     * @return a new defensive copy of the deterministic generated class bytes */ byte[] classBytes() { return classBytes.clone(); }
}
