package backend.cpu1.kernels.reduction;

/**
 * Prepared reduction execution variants for cpu1.
 */
public enum Cpu1ReductionKernelId {
    SUM_F32_DENSE_SCALAR,
    SUM_F64_DENSE_SCALAR,
    SUM_BF16_DENSE_SCALAR,
    MEAN_F32_DENSE_SCALAR,
    MEAN_F64_DENSE_SCALAR,
    MEAN_BF16_DENSE_SCALAR,
    MIN_F32_DENSE_SCALAR,
    MIN_F64_DENSE_SCALAR,
    MIN_BF16_DENSE_SCALAR,
    MAX_F32_DENSE_SCALAR,
    MAX_F64_DENSE_SCALAR,
    MAX_BF16_DENSE_SCALAR,
    PROD_F32_DENSE_SCALAR,
    PROD_F64_DENSE_SCALAR,
    PROD_BF16_DENSE_SCALAR,
    ALL_BOOL_DENSE_SCALAR,
    ANY_BOOL_DENSE_SCALAR,
    ARGMAX_F32_TO_I64_DENSE_SCALAR,
    ARGMAX_F64_TO_I64_DENSE_SCALAR,
    ARGMAX_BF16_TO_I64_DENSE_SCALAR,
    ARGMAX_I32_TO_I64_DENSE_SCALAR,
    ARGMAX_I64_TO_I64_DENSE_SCALAR,
    CUMSUM_F32_DENSE_SCALAR,
    CUMSUM_F64_DENSE_SCALAR,
    CUMSUM_BF16_DENSE_SCALAR,
    CUMSUM_I32_DENSE_SCALAR,
    CUMSUM_I64_DENSE_SCALAR,
    SOFTMAX_F32_DENSE_SCALAR,
    SOFTMAX_F64_DENSE_SCALAR,
    SOFTMAX_BF16_DENSE_SCALAR,
    LOG_SOFTMAX_F32_DENSE_SCALAR,
    LOG_SOFTMAX_F64_DENSE_SCALAR,
    LOG_SOFTMAX_BF16_DENSE_SCALAR
}
