package backend.registry;

import backend.kernels.cpu.CpuKernel;
import backend.kernels.cpu.elementwise.binary.*;
import backend.kernels.cpu.elementwise.compare.*;
import backend.kernels.cpu.fused.CpuFusedKernel;
import backend.kernels.cpu.grad.*;
import backend.kernels.cpu.index.*;
import backend.kernels.cpu.layout.*;
import backend.kernels.cpu.linalg.*;
import backend.kernels.cpu.elementwise.logical.*;
import backend.kernels.cpu.nn.*;
import backend.kernels.cpu.reduction.*;
import backend.kernels.cpu.elementwise.unary.*;
import backend.kernels.cpu.elementwise.where.*;
import operations.Operation;

public final class CpuKernelResolver {
    private static final CpuAddKernel ADD = new CpuAddKernel();
    private static final CpuSubKernel SUB = new CpuSubKernel();
    private static final CpuMulKernel MUL = new CpuMulKernel();
    private static final CpuDivKernel DIV = new CpuDivKernel();
    private static final CpuMinKernel MIN = new CpuMinKernel();
    private static final CpuMaxKernel MAX = new CpuMaxKernel();
    private static final CpuGreaterThanKernel GT = new CpuGreaterThanKernel();
    private static final CpuGreaterOrEqualKernel GE = new CpuGreaterOrEqualKernel();
    private static final CpuLessThanKernel LT = new CpuLessThanKernel();
    private static final CpuLessOrEqualKernel LE = new CpuLessOrEqualKernel();
    private static final CpuEqualToKernel EQ = new CpuEqualToKernel();
    private static final CpuNotEqualToKernel NE = new CpuNotEqualToKernel();
    private static final CpuLogicalAndKernel LOGICAL_AND = new CpuLogicalAndKernel();
    private static final CpuLogicalOrKernel LOGICAL_OR = new CpuLogicalOrKernel();
    private static final CpuLogicalNotKernel LOGICAL_NOT = new CpuLogicalNotKernel();
    private static final CpuGatherKernel GATHER = new CpuGatherKernel();
    private static final CpuGatherGradKernel GATHER_GRAD = new CpuGatherGradKernel();
    private static final CpuTakeAlongAxisKernel TAKE_ALONG_AXIS = new CpuTakeAlongAxisKernel();
    private static final CpuTakeAlongAxisGradKernel TAKE_ALONG_AXIS_GRAD = new CpuTakeAlongAxisGradKernel();
    private static final CpuScatterAddKernel SCATTER_ADD = new CpuScatterAddKernel();
    private static final CpuLinearKernel LINEAR = new CpuLinearKernel();
    private static final CpuConv2dKernel CONV2D = new CpuConv2dKernel();
    private static final CpuConv2dGemmKernel CONV2D_GEMM = new CpuConv2dGemmKernel();
    private static final CpuConv2dBackwardInputKernel CONV2D_BACKWARD_INPUT = new CpuConv2dBackwardInputKernel();
    private static final CpuConv2dBackwardWeightKernel CONV2D_BACKWARD_WEIGHT = new CpuConv2dBackwardWeightKernel();
    private static final CpuMaxPool2dKernel MAX_POOL2D = new CpuMaxPool2dKernel();
    private static final CpuMaxPool2dBackwardInputKernel MAX_POOL2D_BACKWARD_INPUT = new CpuMaxPool2dBackwardInputKernel();
    private static final CpuAvgPool2dKernel AVG_POOL2D = new CpuAvgPool2dKernel();
    private static final CpuAvgPool2dBackwardInputKernel AVG_POOL2D_BACKWARD_INPUT = new CpuAvgPool2dBackwardInputKernel();
    private static final CpuMinGradKernel MIN_GRAD = new CpuMinGradKernel();
    private static final CpuMaxGradKernel MAX_GRAD = new CpuMaxGradKernel();
    private static final CpuReduceMinKernel REDUCE_MIN = new CpuReduceMinKernel();
    private static final CpuReduceMaxKernel REDUCE_MAX = new CpuReduceMaxKernel();
    private static final CpuReduceAllKernel REDUCE_ALL = new CpuReduceAllKernel();
    private static final CpuReduceAnyKernel REDUCE_ANY = new CpuReduceAnyKernel();
    private static final CpuSoftmaxKernel SOFTMAX = new CpuSoftmaxKernel();
    private static final CpuLogSoftmaxKernel LOG_SOFTMAX = new CpuLogSoftmaxKernel();
    private static final CpuNllLossKernel NLL_LOSS = new CpuNllLossKernel();
    private static final CpuCrossEntropyLossKernel CROSS_ENTROPY_LOSS = new CpuCrossEntropyLossKernel();
    private static final CpuReduceMinGradKernel REDUCE_MIN_GRAD = new CpuReduceMinGradKernel();
    private static final CpuReduceMaxGradKernel REDUCE_MAX_GRAD = new CpuReduceMaxGradKernel();
    private static final CpuMatMulKernel MATMUL = new CpuMatMulKernel();
    private static final CpuNegKernel NEG = new CpuNegKernel();
    private static final CpuInvKernel INV = new CpuInvKernel();
    private static final CpuLogKernel LOG = new CpuLogKernel();
    private static final CpuExpKernel EXP = new CpuExpKernel();
    private static final CpuFastExpKernel FAST_EXP = new CpuFastExpKernel();
    private static final CpuTanhKernel TANH = new CpuTanhKernel();
    private static final CpuFastTanhKernel FAST_TANH = new CpuFastTanhKernel();
    private static final CpuPowKernel POW = new CpuPowKernel();
    private static final CpuSqrtKernel SQRT = new CpuSqrtKernel();
    private static final CpuAbsKernel ABS = new CpuAbsKernel();
    private static final CpuMulScalarKernel MUL_SCALAR = new CpuMulScalarKernel();
    private static final CpuSumKernel SUM = new CpuSumKernel();
    private static final CpuMeanKernel MEAN = new CpuMeanKernel();
    private static final CpuReluKernel RELU = new CpuReluKernel();
    private static final CpuClampMinKernel CLAMP_MIN = new CpuClampMinKernel();
    private static final CpuClampMaxKernel CLAMP_MAX = new CpuClampMaxKernel();
    private static final CpuSigmoidKernel SIGMOID = new CpuSigmoidKernel();
    private static final CpuWhereKernel WHERE = new CpuWhereKernel();
    private static final CpuContiguousKernel CONTIGUOUS = new CpuContiguousKernel();
    private static final CpuReshapeLikeKernel RESHAPE = new CpuReshapeLikeKernel();
    private static final CpuExpandKernel EXPAND = new CpuExpandKernel();
    private static final CpuAliasViewKernel ALIAS_VIEW = new CpuAliasViewKernel();
    private static final CpuPermuteKernel PERMUTE = new CpuPermuteKernel();
    private static final CpuNoopKernel NOOP = new CpuNoopKernel();
    private static final CpuFusedKernel FUSED = new CpuFusedKernel();

    private CpuKernelResolver() {
    }

    public static CpuKernel resolve(Operation.OpType type) {
        return switch (type) {
            case ADD -> ADD;
            case SUB -> SUB;
            case MUL -> MUL;
            case DIV -> DIV;
            case MIN -> MIN;
            case MAX -> MAX;
            case GT -> GT;
            case GE -> GE;
            case LT -> LT;
            case LE -> LE;
            case EQ -> EQ;
            case NE -> NE;
            case LOGICAL_AND -> LOGICAL_AND;
            case LOGICAL_OR -> LOGICAL_OR;
            case LOGICAL_NOT -> LOGICAL_NOT;
            case GATHER -> GATHER;
            case GATHER_GRAD -> GATHER_GRAD;
            case TAKE_ALONG_AXIS -> TAKE_ALONG_AXIS;
            case TAKE_ALONG_AXIS_GRAD -> TAKE_ALONG_AXIS_GRAD;
            case SCATTER_ADD -> SCATTER_ADD;
            case LINEAR -> LINEAR;
            case CONV2D -> CONV2D;
            case CONV2D_GEMM -> CONV2D_GEMM;
            case CONV2D_BACKWARD_INPUT -> CONV2D_BACKWARD_INPUT;
            case CONV2D_BACKWARD_WEIGHT -> CONV2D_BACKWARD_WEIGHT;
            case MAX_POOL2D -> MAX_POOL2D;
            case MAX_POOL2D_BACKWARD_INPUT -> MAX_POOL2D_BACKWARD_INPUT;
            case AVG_POOL2D -> AVG_POOL2D;
            case AVG_POOL2D_BACKWARD_INPUT -> AVG_POOL2D_BACKWARD_INPUT;
            case MIN_GRAD -> MIN_GRAD;
            case MAX_GRAD -> MAX_GRAD;
            case REDUCE_MIN -> REDUCE_MIN;
            case REDUCE_MAX -> REDUCE_MAX;
            case REDUCE_ALL -> REDUCE_ALL;
            case REDUCE_ANY -> REDUCE_ANY;
            case SOFTMAX -> SOFTMAX;
            case LOG_SOFTMAX -> LOG_SOFTMAX;
            case NLL_LOSS -> NLL_LOSS;
            case CROSS_ENTROPY_LOSS -> CROSS_ENTROPY_LOSS;
            case REDUCE_MIN_GRAD -> REDUCE_MIN_GRAD;
            case REDUCE_MAX_GRAD -> REDUCE_MAX_GRAD;
            case MATMUL -> MATMUL;
            case NEG -> NEG;
            case INV -> INV;
            case LOG -> LOG;
            case EXP -> EXP;
            case FAST_EXP -> FAST_EXP;
            case TANH -> TANH;
            case FAST_TANH -> FAST_TANH;
            case POW -> POW;
            case SQRT -> SQRT;
            case ABS -> ABS;
            case MUL_SCALAR -> MUL_SCALAR;
            case SUM -> SUM;
            case MEAN -> MEAN;
            case RELU -> RELU;
            case CLAMP_MIN -> CLAMP_MIN;
            case CLAMP_MAX -> CLAMP_MAX;
            case SIGMOID -> SIGMOID;
            case WHERE -> WHERE;
            case CONTIGUOUS -> CONTIGUOUS;
            case RESHAPE -> RESHAPE;
            case EXPAND -> EXPAND;
            case SELECT, EXPAND_DIMS, SQUEEZE -> ALIAS_VIEW;
            case PERMUTE -> PERMUTE;
            case NOOP -> NOOP;
            case FUSED -> FUSED;
            case UNKNOWN -> throw new IllegalStateException("Cannot resolve CPU kernel for UNKNOWN operation type");
        };
    }
}
