package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;

import io.github.pho001.synaptik.model.datatype.DataType;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.Opcode;
import java.lang.classfile.TypeKind;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

/**
 * Emits exact floating sum and mean limb operations directly into generated CPU methods.
 *
 * <p>The emitter exists only while a Class-File body is built. Generated execution owns a
 * prevalidated {@link MemorySegment} slice, accumulates signed coefficients in fixed-width
 * two's-complement limbs, and rounds the exact sum or rational mean once to the represented type.
 * Generated artifacts do not reference this generation-time type.</p>
 */
final class CpuExactSumEmitter {
    private static final ClassDesc SEGMENT = ClassDesc.of(MemorySegment.class.getName());
    private static final ClassDesc VALUE_LAYOUT = ClassDesc.of(ValueLayout.class.getName());
    private static final ClassDesc LONG_LAYOUT = ClassDesc.of("java.lang.foreign.ValueLayout$OfLong");
    private static final ClassDesc LONG_CLASS = ClassDesc.of(Long.class.getName());
    private static final ClassDesc DOUBLE_CLASS = ClassDesc.of(Double.class.getName());
    private static final ClassDesc FLOAT_CLASS = ClassDesc.of(Float.class.getName());
    private static final long NAN = 1, POS_INF = 2, NEG_INF = 4;
    private static final long POS_ZERO = 8, NEG_ZERO = 16, NONZERO = 32;

    private final CodeBuilder code;
    private final DataType type;
    private final boolean mean;
    private final int scratch;
    private final int geometry;
    private final int offset, bytes, limbs, flags, bits, fraction, exponentField, significand;
    private final int shift, wordIndex, bitOffset, limb, addend, carry, old, sum, position;
    private final int negative, top, bitLength, unbiased, quotient, guard, sticky, result;
    private final int domain, remainder, next, quotientWord, bit;

    /**
     * Creates exact-state emission bound to one generated method and its fixed structural width.
     *
     * @param code Class-File method builder mutated by subsequent emission; not {@code null}
     * @param type exact floating represented type
     * @param mean whether finalization divides the exact magnitude by the domain cardinality
     * @param scratch local-variable slot containing the invocation-private state segment
     * @param geometry local-variable slot containing packed aggregate geometry
     * @param exactLimbCount positive schema-29 structural limb count embedded in generated bytes
     * @throws IllegalArgumentException if {@code type} is not a supported floating type or the
     *     structural limb count is not positive
     */
    CpuExactSumEmitter(CodeBuilder code, DataType type, boolean mean, int scratch, int geometry,
            int exactLimbCount) {
        if (type != DataType.FLOAT64 && type != DataType.FLOAT32 && type != DataType.BFLOAT16)
            throw new IllegalArgumentException("exact sum requires a floating type");
        if (exactLimbCount <= 0) throw new IllegalArgumentException("exact limb count must be positive");
        this.code = code; this.type = type; this.mean = mean;
        this.scratch = scratch; this.geometry = geometry;
        offset = code.allocateLocal(TypeKind.LONG); bytes = code.allocateLocal(TypeKind.LONG);
        limbs = code.allocateLocal(TypeKind.INT); flags = code.allocateLocal(TypeKind.LONG);
        bits = code.allocateLocal(TypeKind.LONG); fraction = code.allocateLocal(TypeKind.LONG);
        exponentField = code.allocateLocal(TypeKind.LONG); significand = code.allocateLocal(TypeKind.LONG);
        shift = code.allocateLocal(TypeKind.INT); wordIndex = code.allocateLocal(TypeKind.INT);
        bitOffset = code.allocateLocal(TypeKind.INT); limb = code.allocateLocal(TypeKind.INT);
        addend = code.allocateLocal(TypeKind.LONG); carry = code.allocateLocal(TypeKind.LONG);
        old = code.allocateLocal(TypeKind.LONG); sum = code.allocateLocal(TypeKind.LONG);
        position = code.allocateLocal(TypeKind.LONG); negative = code.allocateLocal(TypeKind.INT);
        top = code.allocateLocal(TypeKind.LONG); bitLength = code.allocateLocal(TypeKind.INT);
        unbiased = code.allocateLocal(TypeKind.LONG); quotient = code.allocateLocal(TypeKind.LONG);
        guard = code.allocateLocal(TypeKind.INT); sticky = code.allocateLocal(TypeKind.INT);
        result = code.allocateLocal(TypeKind.LONG); domain = code.allocateLocal(TypeKind.LONG);
        remainder = code.allocateLocal(TypeKind.LONG); next = code.allocateLocal(TypeKind.LONG);
        quotientWord = code.allocateLocal(TypeKind.LONG); bit = code.allocateLocal(TypeKind.INT);
        geometry(10).lstore(offset); geometry(9).lstore(bytes);
        code.loadConstant(exactLimbCount).istore(limbs);
        geometry(7).lstore(domain);
    }

    /** Emits deterministic zero initialization for the current output cell's exact state. */
    void emitReset() {
        code.loadConstant(0L).lstore(flags);
        set(0, () -> code.loadConstant(0L));
        code.loadConstant(0).istore(limb);
        var loop = code.newLabel(); var done = code.newLabel();
        code.labelBinding(loop).iload(limb).iload(limbs).branch(Opcode.IF_ICMPGE, done);
        limbOffset(limb); code.lstore(position); setAt(position, () -> code.loadConstant(0L));
        code.iinc(limb, 1).branch(Opcode.GOTO, loop).labelBinding(done);
    }

    /**
     * Emits classification and exact signed-limb addition for one represented factor.
     *
     * @param value local-variable slot containing a value of the emitter's represented type
     */
    void emitFactor(int value) {
        loadBits(value); code.lstore(bits);
        code.lload(bits).loadConstant(signMask()).land().loadConstant(0L).lcmp();
        var nonnegativeFactor = code.newLabel(); var factorSignReady = code.newLabel();
        code.branch(Opcode.IFEQ, nonnegativeFactor); code.loadConstant(1)
                .branch(Opcode.GOTO, factorSignReady).labelBinding(nonnegativeFactor)
                .loadConstant(0).labelBinding(factorSignReady).istore(negative);
        code.lload(bits).loadConstant(fractionMask()).land().lstore(fraction);
        code.lload(bits).loadConstant(fractionBits()).lushr().loadConstant(exponentMask()).land()
                .lstore(exponentField);
        var finite = code.newLabel();
        code.lload(exponentField).loadConstant(exponentMask()).lcmp().branch(Opcode.IFNE, finite);
        var infinity = code.newLabel(); var classified = code.newLabel();
        code.lload(fraction).loadConstant(0L).lcmp().branch(Opcode.IFEQ, infinity);
        code.lload(flags).loadConstant(NAN).lor().lstore(flags).branch(Opcode.GOTO, classified)
                .labelBinding(infinity);
        code.lload(flags).loadConstant(signMask()).lload(bits).land().loadConstant(0L).lcmp();
        var positiveInfinity = code.newLabel(); var classifiedFlag = code.newLabel();
        code.branch(Opcode.IFEQ, positiveInfinity);
        code.loadConstant(NEG_INF).branch(Opcode.GOTO, classifiedFlag).labelBinding(positiveInfinity)
                .loadConstant(POS_INF).labelBinding(classifiedFlag);
        code.lor().lstore(flags).branch(Opcode.GOTO, classified).labelBinding(finite);
        var nonzero = code.newLabel();
        code.lload(exponentField).loadConstant(0L).lcmp().branch(Opcode.IFNE, nonzero);
        code.lload(fraction).loadConstant(0L).lcmp().branch(Opcode.IFNE, nonzero);
        code.lload(flags).loadConstant(signMask()).lload(bits).land().loadConstant(0L).lcmp();
        var positiveZero = code.newLabel(); var zeroFlag = code.newLabel();
        code.branch(Opcode.IFEQ, positiveZero);
        code.loadConstant(NEG_ZERO).branch(Opcode.GOTO, zeroFlag).labelBinding(positiveZero)
                .loadConstant(POS_ZERO).labelBinding(zeroFlag);
        code.lor().lstore(flags).branch(Opcode.GOTO, classified).labelBinding(nonzero);
        code.lload(flags).loadConstant(NONZERO).lor().lstore(flags);
        var normal = code.newLabel(); var ready = code.newLabel();
        code.lload(exponentField).loadConstant(0L).lcmp().branch(Opcode.IFNE, normal);
        code.lload(fraction).lstore(significand); code.loadConstant(0).istore(shift)
                .branch(Opcode.GOTO, ready).labelBinding(normal);
        code.loadConstant(1L << fractionBits()).lload(fraction).lor().lstore(significand);
        code.lload(exponentField).loadConstant((long) bias() + fractionBits() + minimumUnitExponent())
                .lsub().l2i().istore(shift).labelBinding(ready);
        code.iload(shift).loadConstant(6).iushr().istore(wordIndex);
        code.iload(shift).loadConstant(63).iand().istore(bitOffset);
        code.iload(negative); var positiveAdd = code.newLabel(); var addDone = code.newLabel();
        code.branch(Opcode.IFEQ, positiveAdd);
        emitAddLoop(true);
        code.branch(Opcode.GOTO, addDone).labelBinding(positiveAdd);
        emitAddLoop(false);
        code.labelBinding(addDone).labelBinding(classified);
    }

    private void emitAddLoop(boolean complement) {
        code.loadConstant(complement ? 1L : 0L).lstore(carry);
        code.loadConstant(0).istore(limb);
        var addLoop = code.newLabel(); var loopDone = code.newLabel();
        code.labelBinding(addLoop).iload(limb).iload(limbs).branch(Opcode.IF_ICMPGE, loopDone);
        code.loadConstant(0L).lstore(addend);
        var nextPart = code.newLabel();
        code.iload(limb).iload(wordIndex).branch(Opcode.IF_ICMPNE, nextPart);
        code.lload(significand).iload(bitOffset).lshl().lstore(addend);
        var partReady = code.newLabel(); code.branch(Opcode.GOTO, partReady).labelBinding(nextPart);
        code.iload(bitOffset).branch(Opcode.IFEQ, partReady);
        code.iload(limb).iload(wordIndex).loadConstant(1).iadd().branch(Opcode.IF_ICMPNE, partReady);
        code.lload(significand).loadConstant(64).iload(bitOffset).isub().lushr().lstore(addend)
                .labelBinding(partReady);
        if (complement) code.lload(addend).loadConstant(-1L).lxor().lstore(addend);
        code.lload(addend).lload(carry).ladd().lstore(sum);
        code.lload(sum).lload(addend).invokestatic(LONG_CLASS, "compareUnsigned",
                MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long, ConstantDescs.CD_long));
        var noFirstCarry = code.newLabel(); var firstCarryDone = code.newLabel();
        code.branch(Opcode.IFGE, noFirstCarry);
        code.loadConstant(1L).branch(Opcode.GOTO, firstCarryDone).labelBinding(noFirstCarry)
                .loadConstant(0L).labelBinding(firstCarryDone).lstore(carry);
        limbOffset(limb); code.lstore(position); getAt(position).lstore(old);
        code.lload(old).lload(sum).ladd().lstore(addend);
        code.lload(addend).lload(old).invokestatic(LONG_CLASS, "compareUnsigned",
                MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long, ConstantDescs.CD_long));
        var noSecondCarry = code.newLabel(); code.branch(Opcode.IFGE, noSecondCarry);
        code.loadConstant(1L).lload(carry).lor().lstore(carry).labelBinding(noSecondCarry);
        setAt(position, () -> code.lload(addend));
        code.iinc(limb, 1).branch(Opcode.GOTO, addLoop).labelBinding(loopDone);
    }

    /**
     * Emits special-value resolution and one ties-to-even conversion into a result local.
     *
     * @param value local-variable slot receiving the represented result
     */
    void emitFinish(int value) {
        set(0, () -> code.lload(flags)); code.loadConstant(0L).lstore(result);
        var finite = code.newLabel(); var store = code.newLabel();
        code.lload(flags).loadConstant(NAN).land().loadConstant(0L).lcmp().branch(Opcode.IFEQ, finite);
        code.loadConstant(canonicalNan()).lstore(result).branch(Opcode.GOTO, store)
                .labelBinding(finite);
        code.lload(flags).loadConstant(POS_INF | NEG_INF).land()
                .loadConstant(POS_INF | NEG_INF).lcmp();
        var oneInfinity = code.newLabel(); code.branch(Opcode.IFNE, oneInfinity);
        code.loadConstant(canonicalNan()).lstore(result).branch(Opcode.GOTO, store)
                .labelBinding(oneInfinity);
        code.lload(flags).loadConstant(POS_INF).land().loadConstant(0L).lcmp();
        var negativeInfinity = code.newLabel(); code.branch(Opcode.IFEQ, negativeInfinity);
        code.loadConstant(positiveInfinity()).lstore(result).branch(Opcode.GOTO, store)
                .labelBinding(negativeInfinity);
        code.lload(flags).loadConstant(NEG_INF).land().loadConstant(0L).lcmp();
        var checkEmptyMean = code.newLabel(); code.branch(Opcode.IFEQ, checkEmptyMean);
        code.loadConstant(signMask() | positiveInfinity()).lstore(result).branch(Opcode.GOTO, store)
                .labelBinding(checkEmptyMean);
        if (mean) {
            code.lload(domain).loadConstant(0L).lcmp(); var nonempty = code.newLabel();
            code.branch(Opcode.IFNE, nonempty); code.loadConstant(canonicalNan()).lstore(result)
                    .branch(Opcode.GOTO, store).labelBinding(nonempty);
        }
        code.iload(limbs).loadConstant(1).isub().istore(limb); limbOffset(limb);
        code.lstore(position); getAt(position).loadConstant(0L).lcmp();
        var positive = code.newLabel(); code.branch(Opcode.IFGE, positive);
        code.loadConstant(1).istore(negative); code.loadConstant(1L).lstore(carry);
        code.loadConstant(0).istore(limb); var negate = code.newLabel(); var negated = code.newLabel();
        code.labelBinding(negate).iload(limb).iload(limbs).branch(Opcode.IF_ICMPGE, negated);
        limbOffset(limb); code.lstore(position); getAt(position).loadConstant(-1L).lxor().lstore(old);
        code.lload(old).lload(carry).ladd().lstore(sum);
        code.lload(sum).lload(old).invokestatic(LONG_CLASS, "compareUnsigned",
                MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long, ConstantDescs.CD_long));
        var noCarry = code.newLabel(); code.branch(Opcode.IFLT, noCarry);
        code.loadConstant(0L).lstore(carry).labelBinding(noCarry); setAt(position, () -> code.lload(sum));
        code.iinc(limb, 1).branch(Opcode.GOTO, negate).labelBinding(negated);
        var magnitude = code.newLabel(); code.branch(Opcode.GOTO, magnitude).labelBinding(positive);
        code.loadConstant(0).istore(negative).labelBinding(magnitude);
        code.loadConstant(0L).lstore(remainder);
        if (mean) emitDivide();
        code.iload(limbs).loadConstant(1).isub().istore(limb);
        var findTop = code.newLabel(); var foundTop = code.newLabel();
        code.labelBinding(findTop); limbOffset(limb); code.lstore(position); getAt(position).lstore(top);
        code.lload(top).loadConstant(0L).lcmp().branch(Opcode.IFNE, foundTop);
        code.iload(limb).branch(Opcode.IFEQ, foundTop); code.iinc(limb, -1)
                .branch(Opcode.GOTO, findTop).labelBinding(foundTop);
        code.lload(top).loadConstant(0L).lcmp(); var nonzero = code.newLabel();
        code.branch(Opcode.IFNE, nonzero);
        if (mean) {
            code.lload(remainder).loadConstant(0L).lcmp(); var rationalNonzero = code.newLabel();
            code.branch(Opcode.IFNE, rationalNonzero);
            emitZeroResult(store); code.labelBinding(rationalNonzero);
            code.loadConstant(0).istore(bitLength);
        } else emitZeroResult(store);
        code.labelBinding(nonzero);
        code.iload(limb).loadConstant(64).imul().loadConstant(64)
                .lload(top).invokestatic(LONG_CLASS, "numberOfLeadingZeros",
                        MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long))
                .isub().iadd().istore(bitLength);
        code.loadConstant((long) minimumUnitExponent()).iload(bitLength).i2l().ladd()
                .loadConstant(1L).lsub().lstore(unbiased);
        code.lload(unbiased).loadConstant((long) minimumNormal()).lcmp();
        var subnormal = code.newLabel(); var shiftReady = code.newLabel();
        code.branch(Opcode.IFLT, subnormal); code.iload(bitLength).loadConstant(precision()).isub()
                .istore(shift).branch(Opcode.GOTO, shiftReady).labelBinding(subnormal);
        code.loadConstant(0).istore(shift).labelBinding(shiftReady);
        emitExtractAndRound();
        code.lload(unbiased).loadConstant((long) minimumNormal()).lcmp();
        var finishSubnormal = code.newLabel(); code.branch(Opcode.IFLT, finishSubnormal);
        code.lload(quotient).loadConstant(1L << precision()).lcmp(); var widthReady = code.newLabel();
        code.branch(Opcode.IFNE, widthReady); code.lload(quotient).loadConstant(1).lushr()
                .lstore(quotient); code.lload(unbiased).loadConstant(1L).ladd().lstore(unbiased)
                .labelBinding(widthReady);
        code.lload(unbiased).loadConstant((long) maximumExponent()).lcmp(); var notOverflow = code.newLabel();
        code.branch(Opcode.IFLE, notOverflow); emitSign(); code.loadConstant(positiveInfinity()).lor()
                .lstore(result).branch(Opcode.GOTO, store).labelBinding(notOverflow);
        emitSign(); code.lload(unbiased).loadConstant((long) bias()).ladd().loadConstant(fractionBits())
                .lshl().lload(quotient).loadConstant(fractionMask()).land().lor().lor().lstore(result)
                .branch(Opcode.GOTO, store).labelBinding(finishSubnormal);
        emitSign(); code.lstore(result); code.lload(quotient).loadConstant(1L << fractionBits()).lcmp();
        var trueSubnormal = code.newLabel(); code.branch(Opcode.IFLT, trueSubnormal);
        code.lload(result).loadConstant(1L << fractionBits()).lor().lstore(result)
                .branch(Opcode.GOTO, store).labelBinding(trueSubnormal);
        code.lload(result).lload(quotient).lor().lstore(result).labelBinding(store);
        storeResult(value);
    }

    /**
     * Emits finalization using a runtime-selected non-negative domain count.
     *
     * <p>This generation-time seam is used by masked mean. Ordinary aggregate emission retains
     * the static domain loaded by the constructor and therefore keeps identical generated bytes.</p>
     *
     * @param value local-variable slot receiving the represented result
     * @param selectedCount local-variable slot containing the invocation-local selected count
     */
    void emitFinish(int value, int selectedCount) {
        code.lload(selectedCount).lstore(domain);
        emitFinish(value);
    }

    private void emitDivide() {
        code.iload(limbs).loadConstant(1).isub().istore(limb);
        var words = code.newLabel(); var done = code.newLabel();
        code.labelBinding(words).iload(limb).branch(Opcode.IFLT, done);
        limbOffset(limb); code.lstore(position); getAt(position).lstore(old);
        code.loadConstant(0L).lstore(quotientWord); code.loadConstant(63).istore(bit);
        var bitsLoop = code.newLabel(); var wordDone = code.newLabel();
        code.labelBinding(bitsLoop).iload(bit).branch(Opcode.IFLT, wordDone);
        code.lload(remainder).loadConstant(1).lshl().lload(old).iload(bit).lushr()
                .loadConstant(1L).land().lor().lstore(next);
        code.lload(next).lload(domain).invokestatic(LONG_CLASS, "compareUnsigned",
                MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long, ConstantDescs.CD_long));
        var below = code.newLabel(); code.branch(Opcode.IFLT, below);
        code.lload(next).lload(domain).lsub().lstore(next);
        code.lload(quotientWord).loadConstant(1L).iload(bit).lshl().lor().lstore(quotientWord)
                .labelBinding(below); code.lload(next).lstore(remainder); code.iinc(bit, -1)
                .branch(Opcode.GOTO, bitsLoop).labelBinding(wordDone);
        setAt(position, () -> code.lload(quotientWord)); code.iinc(limb, -1)
                .branch(Opcode.GOTO, words).labelBinding(done);
    }

    private void emitExtractAndRound() {
        code.iload(shift).loadConstant(6).iushr().istore(wordIndex);
        code.iload(shift).loadConstant(63).iand().istore(bitOffset);
        limbOffset(wordIndex); code.lstore(position); getAt(position).iload(bitOffset).lushr()
                .lstore(quotient);
        var noNext = code.newLabel(); code.iload(bitOffset).branch(Opcode.IFEQ, noNext);
        code.iload(wordIndex).loadConstant(1).iadd().iload(limbs).branch(Opcode.IF_ICMPGE, noNext);
        code.iinc(wordIndex, 1); limbOffset(wordIndex); code.lstore(position); getAt(position)
                .loadConstant(64).iload(bitOffset).isub().lshl().lload(quotient).lor()
                .lstore(quotient).labelBinding(noNext);
        code.loadConstant(0).istore(guard); code.loadConstant(0).istore(sticky);
        var fractionalUnit = code.newLabel(); var round = code.newLabel();
        code.iload(shift).branch(Opcode.IFEQ, fractionalUnit);
        code.iload(shift).loadConstant(1).isub().istore(bit);
        code.iload(bit).loadConstant(6).iushr().istore(wordIndex);
        code.iload(bit).loadConstant(63).iand().istore(bitOffset); limbOffset(wordIndex);
        code.lstore(position); getAt(position).iload(bitOffset).lushr().loadConstant(1L).land()
                .l2i().istore(guard); code.loadConstant(0).istore(limb);
        var stickyLoop = code.newLabel(); var stickyDone = code.newLabel();
        code.labelBinding(stickyLoop).iload(limb).iload(wordIndex).branch(Opcode.IF_ICMPGE, stickyDone);
        limbOffset(limb); code.lstore(position); getAt(position).loadConstant(0L).lcmp();
        var nextLimb = code.newLabel(); code.branch(Opcode.IFEQ, nextLimb);
        code.loadConstant(1).istore(sticky).branch(Opcode.GOTO, stickyDone)
                .labelBinding(nextLimb).iinc(limb, 1).branch(Opcode.GOTO, stickyLoop)
                .labelBinding(stickyDone);
        code.iload(sticky).branch(Opcode.IFNE, round); code.iload(bitOffset).branch(Opcode.IFEQ, round);
        limbOffset(wordIndex); code.lstore(position); getAt(position).loadConstant(1L)
                .iload(bitOffset).lshl().loadConstant(1L).lsub().land().loadConstant(0L).lcmp();
        var noLow = code.newLabel(); code.branch(Opcode.IFEQ, noLow); code.loadConstant(1)
                .istore(sticky).labelBinding(noLow);
        if (mean) {
            code.lload(remainder).loadConstant(0L).lcmp(); var noRemainder = code.newLabel();
            code.branch(Opcode.IFEQ, noRemainder); code.loadConstant(1).istore(sticky)
                    .labelBinding(noRemainder);
        }
        code.branch(Opcode.GOTO, round).labelBinding(fractionalUnit);
        if (mean) {
            code.lload(remainder).loadConstant(1).lshl().lstore(next);
            code.lload(next).lload(domain).invokestatic(LONG_CLASS, "compareUnsigned",
                    MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long,
                            ConstantDescs.CD_long)).istore(bit);
            var less = code.newLabel(); var greater = code.newLabel();
            code.iload(bit).branch(Opcode.IFLT, less); code.iload(bit).branch(Opcode.IFGT, greater);
            code.loadConstant(1).istore(guard).branch(Opcode.GOTO, round)
                    .labelBinding(greater); code.loadConstant(1).istore(guard);
            code.loadConstant(1).istore(sticky).branch(Opcode.GOTO, round).labelBinding(less);
        }
        code.labelBinding(round); code.iload(guard); var rounded = code.newLabel();
        code.branch(Opcode.IFEQ, rounded); code.iload(sticky); var up = code.newLabel();
        code.branch(Opcode.IFNE, up); code.lload(quotient).loadConstant(1L).land()
                .loadConstant(0L).lcmp().branch(Opcode.IFEQ, rounded).labelBinding(up);
        code.lload(quotient).loadConstant(1L).ladd().lstore(quotient).labelBinding(rounded);
    }

    private void emitZeroResult(java.lang.classfile.Label store) {
        code.lload(flags).loadConstant(NEG_ZERO).lcmp(); var positive = code.newLabel();
        code.branch(Opcode.IFNE, positive); code.loadConstant(signMask()).lstore(result)
                .branch(Opcode.GOTO, store).labelBinding(positive); code.loadConstant(0L)
                .lstore(result).branch(Opcode.GOTO, store);
    }
    private void emitSign() {
        code.iload(negative); var positive = code.newLabel(); var done = code.newLabel();
        code.branch(Opcode.IFEQ, positive); code.loadConstant(signMask()).branch(Opcode.GOTO, done)
                .labelBinding(positive).loadConstant(0L).labelBinding(done);
    }
    private void loadBits(int value) { switch (type) {
        case FLOAT64 -> code.dload(value).invokestatic(DOUBLE_CLASS, "doubleToRawLongBits",
                MethodTypeDesc.of(ConstantDescs.CD_long, ConstantDescs.CD_double));
        case FLOAT32 -> code.fload(value).invokestatic(FLOAT_CLASS, "floatToRawIntBits",
                MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_float)).i2l()
                .loadConstant(0xffffffffL).land();
        case BFLOAT16 -> code.iload(value).i2l().loadConstant(0xffffL).land();
        default -> throw new IllegalArgumentException("not floating");
    } }
    private void storeResult(int value) { switch (type) {
        case FLOAT64 -> code.lload(result).invokestatic(DOUBLE_CLASS, "longBitsToDouble",
                MethodTypeDesc.of(ConstantDescs.CD_double, ConstantDescs.CD_long)).dstore(value);
        case FLOAT32 -> code.lload(result).l2i().invokestatic(FLOAT_CLASS, "intBitsToFloat",
                MethodTypeDesc.of(ConstantDescs.CD_float, ConstantDescs.CD_int)).fstore(value);
        case BFLOAT16 -> code.lload(result).l2i().istore(value);
        default -> throw new IllegalArgumentException("not floating");
    } }
    private CodeBuilder geometry(int index) { return code.aload(geometry).loadConstant(index).laload(); }
    private CodeBuilder get(int delta) { segmentOffset(delta); return code.invokeinterface(SEGMENT,
            "get", MethodTypeDesc.of(ConstantDescs.CD_long, LONG_LAYOUT, ConstantDescs.CD_long)); }
    private CodeBuilder getAt(int address) { return code.aload(scratch).getstatic(VALUE_LAYOUT,
            "JAVA_LONG", LONG_LAYOUT).lload(address).invokeinterface(SEGMENT, "get",
            MethodTypeDesc.of(ConstantDescs.CD_long, LONG_LAYOUT, ConstantDescs.CD_long)); }
    private void set(int delta, Runnable value) { segmentOffset(delta); value.run();
        code.invokeinterface(SEGMENT, "set", MethodTypeDesc.of(ConstantDescs.CD_void,
                LONG_LAYOUT, ConstantDescs.CD_long, ConstantDescs.CD_long)); }
    private void setAt(int address, Runnable value) { code.aload(scratch).getstatic(VALUE_LAYOUT,
            "JAVA_LONG", LONG_LAYOUT).lload(address); value.run(); code.invokeinterface(SEGMENT,
            "set", MethodTypeDesc.of(ConstantDescs.CD_void, LONG_LAYOUT,
                    ConstantDescs.CD_long, ConstantDescs.CD_long)); }
    private void segmentOffset(int delta) { code.aload(scratch).getstatic(VALUE_LAYOUT,
            "JAVA_LONG", LONG_LAYOUT).lload(offset); if (delta != 0) code.loadConstant((long) delta).ladd(); }
    private void limbOffset(int index) { code.lload(offset).loadConstant(8L).ladd().iload(index)
            .i2l().loadConstant(8L).lmul().ladd(); }
    private int fractionBits() { return type == DataType.FLOAT64 ? 52 : type == DataType.FLOAT32 ? 23 : 7; }
    private int precision() { return fractionBits() + 1; }
    private int bias() { return type == DataType.FLOAT64 ? 1023 : 127; }
    private int minimumUnitExponent() { return type == DataType.FLOAT64 ? -1074
            : type == DataType.FLOAT32 ? -149 : -133; }
    private int minimumNormal() { return 1 - bias(); }
    private int maximumExponent() { return type == DataType.FLOAT64 ? 1023 : 127; }
    private long fractionMask() { return (1L << fractionBits()) - 1; }
    private long exponentMask() { return type == DataType.FLOAT64 ? 0x7ffL : 0xffL; }
    private long signMask() { return type == DataType.FLOAT64 ? Long.MIN_VALUE
            : type == DataType.FLOAT32 ? 1L << 31 : 1L << 15; }
    private long canonicalNan() { return type == DataType.FLOAT64 ? 0x7ff8000000000000L
            : type == DataType.FLOAT32 ? 0x7fc00000L : 0x7fc0L; }
    private long positiveInfinity() { return type == DataType.FLOAT64 ? 0x7ff0000000000000L
            : type == DataType.FLOAT32 ? 0x7f800000L : 0x7f80L; }
}
