/**
 * Owns unsupported Java 26 Class-File generation from canonical CPU kernel IR.
 *
 * <p>Emitters consume an already-selected exact scalar or preferred-species typed vector
 * specialization and generate one universal primitive {@code start}/{@code end} loop over its
 * exact ordered typed primitive-array or {@code MemorySegment} carrier pattern. Proved dense
 * heap-array pointwise entries narrow their universal long bounds and bases once, then use
 * integer loop/address locals; other forms retain checked long state. Scalar generation
 * covers the admitted FLOAT64, FLOAT32, INT32, INT64, and BOOL pointwise rows. A separate scalar
 * affine emitter copies represented bits for all six Model data types, including opaque BFLOAT16
 * through {@code short[]} or native-order two-byte {@code MemorySegment} access. Vector generation covers the
 * bounded typed value matrix plus unit-private floating masks and scalar-broadcast BOOL conditions;
 * materialized or general external masks remain scalar. Every unary opcode has a scalar body;
 * FLOOR, CEIL, SIGMOID, GELU tanh approximation, and SiLU remain scalar-compute only. Vector
 * instruction bytecode emission is separate from pure typed vector mathematics. General Tensor
 * power and direct scalar power are also scalar-compute only. FLOAT32 reciprocal square root
 * widens before both {@code StrictMath.sqrt} and the reciprocal and narrows their combined result
 * once. Direct FLOAT32 power widens the represented base and exponent exactly, invokes
 * {@code StrictMath.pow}, and narrows once. Segment access uses native byte order. Dense,
 * scalar-broadcast, last-axis, and block/outer regimes admit
 * unmasked complete vectors followed by the existing scalar body for every remainder. Proved
 * dense arrays compute one integer vector bound, execute one vector loop, and then one scalar
 * tail while retaining the preferred species in one local; the general
 * odometer remains scalar. Emitters consume the already-typed CPU opcode sequence and do not
 * inspect graph nodes, choose numerical policy, select a
 * route, orchestrate workers, bind Runtime resources, or persist artifacts. Generated bytes are
 * verified before definition and are handed to the cache and executable packages as strongly
 * owned immutable artifact state.
 * The general affine body reads one cold-composed source/result address pair per iteration.
 * Proved dense heap-array affine copies narrow their first pair and bounds once and advance direct
 * integer indexes. Both forms perform no numerical conversion, Shape/layout interpretation,
 * allocation, or vector access.
 * A separate movement emitter consumes compact cold geometry for one static PAD, TILE, CONCAT,
 * STACK, window-extraction, or functional SLICE_UPDATE occurrence and emits a direct
 * represented-bit scalar loop. Proved dense heap-array movement bodies hoist their primitive
 * geometry into integer locals and retain the universal long entry bounds; general layouts and
 * segment or mixed carriers keep the long-address body. Slice update walks the output once,
 * selecting update values at
 * signed-sequence positions and base values elsewhere. It uses coordinate and sequence-cursor
 * carry/reset state for arbitrary ranges, performs no per-element division or modulo, and
 * preserves repeated input occurrences without duplicating boundary carriers.
 * The indexing emitter receives compact range-start geometry only after a separate bound scalar
 * pass has validated every logical INT32/INT64 index. It writes GATHER, GATHER_ELEMENTS,
 * GATHER_ND, or canonical-BOOL ONE_HOT output, performs no bounds branch, and owns neither
 * validation nor worker submission.
 * The functional-scatter emitter receives the same direct carriers only after complete bounds
 * validation and, for replacement forms, complete target-uniqueness validation. It owns one
 * output-domain scalar pass for SCATTER_ELEMENTS, Gather-compatible SCATTER_ADD, or SCATTER_ND.
 * Each range reads the functional base, scans logical updates in row-major order, and writes its
 * disjoint output coordinates once. Floating multiplication alone receives one assigned scratch
 * slice and rounds the abstract unchanged-format product once; other reductions receive no
 * scratch parameter. The emitter neither mutates inputs nor submits workers.
 * The fold emitter owns a separate output-domain scalar body. It initializes each owned output
 * from represented positive zero, scans logical input occurrences in canonical row-major order,
 * excludes out-of-domain FOLD2D positions geometrically, performs represented sequential
 * addition, and writes each output coordinate once without scratch or atomics.
 * The ordering emitter owns a separate logical-slice scalar body. It performs a stable bottom-up
 * merge over two assigned INT64 index regions, compares floating values with NaNs last and
 * directional signed zero, preserves selected represented bits, writes logical-axis INT64
 * indices, and emits both TOP_K outputs from one entry. Parallel orchestration supplies disjoint
 * complete slices and scratch regions; vector sorting and worker submission remain outside it.
 *
 * <p>The random emitter owns one allocation-free initializer/dropout bridge. A dedicated
 * {@code [0,0)} prologue writes state exactly once before scalar or parallel element ranges;
 * each dropout element derives its word from the global logical ordinal and writes one canonical
 * BOOL byte plus its exact FLOAT64/FLOAT32 result.</p>
 *
 * <p>The scan emitter embeds a typed two-boundary body over complete independent slice ordinals.
 * It reconstructs non-axis coordinates once per slice, walks the selected axis sequentially in
 * the requested direction, applies inclusive or exclusive placement, and retains same-type
 * FLOAT64/FLOAT32 or modular INT32/INT64 accumulators. BFLOAT16 widens to FLOAT32 and rounds back
 * after every visited value. Dense rank-one heap arrays use a direct integer-address loop;
 * arbitrary layouts and segment carriers retain typed long-address traversal. Parallel
 * orchestration never splits a slice.</p>
 *
 * <p>The aggregate emitter embeds a typed scalar fold. It owns complete output cells, walks
 * selected coordinates in canonical logical row-major order, preserves the first NaN bits and
 * signed-zero extrema, emits canonical Boolean identities and results, and allocates no object
 * per output cell or selected element. Full dense heap-array reductions use a direct integer fold;
 * all other current forms retain a typed general-layout fallback.</p>
 *
 * <p>Generation and verification are cold-path operations. Only the resolved static entry handle
 * executes on the Runtime hot path. Parallel plans reuse that direct scalar or vector entry for
 * already-bound disjoint chunks; generated code contains no parallel scheduler or strategy switch.
 */
package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;
