/**
 * Owns unsupported Java 26 Class-File generation from canonical CPU kernel IR.
 *
 * <p>Emitters consume an already-selected exact scalar or preferred-species typed vector
 * specialization and generate one universal primitive {@code start}/{@code end} loop over its
 * exact ordered typed primitive-array or {@code MemorySegment} carrier pattern. Scalar generation
 * covers the admitted FLOAT64, FLOAT32, INT32, INT64, and BOOL rows. Vector generation covers the
 * bounded typed value matrix plus unit-private floating masks and scalar-broadcast BOOL conditions;
 * materialized or general external masks remain scalar. Every unary opcode has a scalar body;
 * FLOOR, CEIL, SIGMOID, GELU tanh approximation, and SiLU remain scalar-compute only. Vector
 * instruction bytecode emission is separate from pure typed vector mathematics. General Tensor
 * power and direct scalar power are also scalar-compute only. FLOAT32 reciprocal square root
 * widens before both {@code StrictMath.sqrt} and the reciprocal and narrows their combined result
 * once. Direct FLOAT32 power widens the represented base and exponent exactly, invokes
 * {@code StrictMath.pow}, and narrows once. Segment access uses native byte order. Dense,
 * scalar-broadcast, last-axis, and block/outer regimes admit
 * unmasked complete vectors followed by the existing scalar body for every remainder; the general
 * odometer remains scalar. Emitters consume the already-typed CPU opcode sequence and do not
 * inspect graph nodes, choose numerical policy, select a
 * route, orchestrate workers, bind Runtime resources, or persist artifacts. Generated bytes are
 * verified before definition and are handed to the cache and executable packages as strongly
 * owned immutable artifact state.
 *
 * <p>Generation and verification are cold-path operations. Only the resolved static entry handle
 * executes on the Runtime hot path. Parallel plans reuse that direct scalar or vector entry for
 * already-bound disjoint chunks; generated code contains no parallel scheduler or strategy switch.
 */
package io.github.pho001.synaptik.backend.cpu.internal.codegen.emit;
