// GENERATED by scripts/generate-cpu1-elementwise.js. Do not edit by hand.
package backend.cpu1.kernels.elementwise.binary.mul;

import backend.cpu1.exec.Cpu1KernelArgs;
import backend.cpu1.exec.Cpu1TensorView;
import backend.cpu1.offset.Cpu1GenericOffsetPlan;
import jdk.incubator.vector.DoubleVector;
import jdk.incubator.vector.FloatVector;
import jdk.incubator.vector.VectorOperators;
import jdk.incubator.vector.VectorSpecies;
import tensor.dtype.TensorDTypeOps;
import utils.FastTranscendentals;
import utils.SpecialFunctions;

import java.lang.foreign.MemorySegment;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * Static mul loops selected by Cpu1KernelId at prepare time.
 */
public final class Cpu1MulLoops {
    private static final VectorSpecies<Float> F32 = FloatVector.SPECIES_PREFERRED;
    private static final VectorSpecies<Double> F64 = DoubleVector.SPECIES_PREFERRED;
    private static final ByteOrder ORDER = ByteOrder.nativeOrder();
    private static final int BROADCAST_CONTIGUOUS = 0;
    private static final int BROADCAST_SCALAR = 1;
    private static final int BROADCAST_INNER = 2;

    private Cpu1MulLoops() {
    }

    private static int broadcastVectorMode(Cpu1TensorView view) {
        if (isBroadcastScalar(view)) {
            return BROADCAST_SCALAR;
        }
        if (isBroadcastInner(view)) {
            return BROADCAST_INNER;
        }
        return BROADCAST_CONTIGUOUS;
    }

    private static int broadcastVectorInnerSize(Cpu1TensorView outputView) {
        int rank = outputView.rank();
        return rank == 0 ? 1 : outputView.shape(rank - 1);
    }

    private static boolean isBroadcastScalar(Cpu1TensorView view) {
        for (int dim = 0; dim < view.rank(); dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return true;
    }

    private static boolean isBroadcastInner(Cpu1TensorView view) {
        int rank = view.rank();
        if (rank == 0 || view.contiguous()) {
            return false;
        }
        for (int dim = 0; dim < rank - 1; dim++) {
            if (view.stride(dim) != 0) {
                return false;
            }
        }
        return view.stride(rank - 1) == 1;
    }

    public static void bf16ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        float[] leftChunk = new float[F32.length()];
        float[] rightChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                for (int lane = 0; lane < F32.length(); lane++) {
                    leftChunk[lane] = TensorDTypeOps.fromBFloat16Bits(left[leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + vectorInner + lane : leftBase + i + lane)]);
                    rightChunk[lane] = TensorDTypeOps.fromBFloat16Bits(right[rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + vectorInner + lane : rightBase + i + lane)]);
                }
                FloatVector.fromArray(F32, leftChunk, 0)
                        .mul(FloatVector.fromArray(F32, rightChunk, 0))
                        .intoArray(outputChunk, 0);
                for (int lane = 0; lane < F32.length(); lane++) {
                    output[outputBase + i + lane] = TensorDTypeOps.toBFloat16Bits(outputChunk[lane]);
                }
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                float result = TensorDTypeOps.fromBFloat16Bits(left[leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + scalarInner : leftBase + i)]) * TensorDTypeOps.fromBFloat16Bits(right[rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + scalarInner : rightBase + i)]);
                output[outputBase + i] = TensorDTypeOps.toBFloat16Bits(result);
            }
        }
    }

    public static void bf16ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left[leftOffset]) * TensorDTypeOps.fromBFloat16Bits(right[rightOffset]));
        }
    }

    public static void bf16ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        float[] leftChunk = new float[F32.length()];
        float[] rightChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            for (int lane = 0; lane < F32.length(); lane++) {
                leftChunk[lane] = TensorDTypeOps.fromBFloat16Bits(left[leftBase + i + lane]);
                rightChunk[lane] = TensorDTypeOps.fromBFloat16Bits(right[rightBase + i + lane]);
            }
            FloatVector.fromArray(F32, leftChunk, 0)
                    .mul(FloatVector.fromArray(F32, rightChunk, 0))
                    .intoArray(outputChunk, 0);
            for (int lane = 0; lane < F32.length(); lane++) {
                output[outputBase + i + lane] = TensorDTypeOps.toBFloat16Bits(outputChunk[lane]);
            }
        }
        for (; i < endExclusive; i++) {
            float result = TensorDTypeOps.fromBFloat16Bits(left[leftBase + i]) * TensorDTypeOps.fromBFloat16Bits(right[rightBase + i]);
            output[outputBase + i] = TensorDTypeOps.toBFloat16Bits(result);
        }
    }

    public static void bf16ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        short[] left = args.input(0).bfloat16Array();
        short[] right = args.input(1).bfloat16Array();
        short[] output = args.output().bfloat16Array();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output[outputOffset.offset(i)] = TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left[leftOffset.offset(i)]) * TensorDTypeOps.fromBFloat16Bits(right[rightOffset.offset(i)]));
        }
    }

    public static void bf16ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left[leftOffset]) * TensorDTypeOps.fromBFloat16Bits(right[rightOffset]));
        }
    }

    public static void bf16ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left[leftOffset]) * TensorDTypeOps.fromBFloat16Bits(right[rightOffset]));
        }
    }

    public static void bf16ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        short[] left = leftView.bfloat16Array();
        short[] right = rightView.bfloat16Array();
        short[] output = outputView.bfloat16Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output[outputOffset] = TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left[leftOffset]) * TensorDTypeOps.fromBFloat16Bits(right[rightOffset]));
        }
    }

    public static void bf16SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        float[] leftChunk = new float[F32.length()];
        float[] rightChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                for (int lane = 0; lane < F32.length(); lane++) {
                    leftChunk[lane] = TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + vectorInner + lane : leftBase + i + lane)) * Short.BYTES));
                    rightChunk[lane] = TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + vectorInner + lane : rightBase + i + lane)) * Short.BYTES));
                }
                FloatVector.fromArray(F32, leftChunk, 0)
                        .mul(FloatVector.fromArray(F32, rightChunk, 0))
                        .intoArray(outputChunk, 0);
                for (int lane = 0; lane < F32.length(); lane++) {
                    output.set(JAVA_SHORT, (long) (outputBase + i + lane) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(outputChunk[lane]));
                }
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                float result = TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + scalarInner : leftBase + i)) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + scalarInner : rightBase + i)) * Short.BYTES));
                output.set(JAVA_SHORT, (long) (outputBase + i) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(result));
            }
        }
    }

    public static void bf16SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftOffset) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightOffset) * Short.BYTES))));
        }
    }

    public static void bf16SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        float[] leftChunk = new float[F32.length()];
        float[] rightChunk = new float[F32.length()];
        float[] outputChunk = new float[F32.length()];
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            for (int lane = 0; lane < F32.length(); lane++) {
                leftChunk[lane] = TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftBase + i + lane) * Short.BYTES));
                rightChunk[lane] = TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightBase + i + lane) * Short.BYTES));
            }
            FloatVector.fromArray(F32, leftChunk, 0)
                    .mul(FloatVector.fromArray(F32, rightChunk, 0))
                    .intoArray(outputChunk, 0);
            for (int lane = 0; lane < F32.length(); lane++) {
                output.set(JAVA_SHORT, (long) (outputBase + i + lane) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(outputChunk[lane]));
            }
        }
        for (; i < endExclusive; i++) {
            float result = TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftBase + i) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightBase + i) * Short.BYTES));
            output.set(JAVA_SHORT, (long) (outputBase + i) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(result));
        }
    }

    public static void bf16SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment left = args.input(0).segment();
        MemorySegment right = args.input(1).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output.set(JAVA_SHORT, (long) (outputOffset.offset(i)) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftOffset.offset(i)) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightOffset.offset(i)) * Short.BYTES))));
        }
    }

    public static void bf16SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftOffset) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightOffset) * Short.BYTES))));
        }
    }

    public static void bf16SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftOffset) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightOffset) * Short.BYTES))));
        }
    }

    public static void bf16SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output.set(JAVA_SHORT, (long) (outputOffset) * Short.BYTES, TensorDTypeOps.toBFloat16Bits(TensorDTypeOps.fromBFloat16Bits(left.get(JAVA_SHORT, (long) (leftOffset) * Short.BYTES)) * TensorDTypeOps.fromBFloat16Bits(right.get(JAVA_SHORT, (long) (rightOffset) * Short.BYTES))));
        }
    }

    public static void f32ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                (leftMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, left[leftBase]) : (leftMode == BROADCAST_INNER ? FloatVector.fromArray(F32, left, leftBase + vectorInner) : FloatVector.fromArray(F32, left, leftBase + i)))
                        .mul((rightMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, right[rightBase]) : (rightMode == BROADCAST_INNER ? FloatVector.fromArray(F32, right, rightBase + vectorInner) : FloatVector.fromArray(F32, right, rightBase + i))))
                        .intoArray(output, outputBase + i);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                output[outputBase + i] = left[leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + scalarInner : leftBase + i)] * right[rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + scalarInner : rightBase + i)];
            }
        }
    }

    public static void f32ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f32ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            FloatVector.fromArray(F32, left, leftBase + i)
                    .mul(FloatVector.fromArray(F32, right, rightBase + i))
                    .intoArray(output, outputBase + i);
        }
        for (; i < endExclusive; i++) {
            output[outputBase + i] = left[leftBase + i] * right[rightBase + i];
        }
    }

    public static void f32ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        float[] left = args.input(0).float32Array();
        float[] right = args.input(1).float32Array();
        float[] output = args.output().float32Array();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output[outputOffset.offset(i)] = left[leftOffset.offset(i)] * right[rightOffset.offset(i)];
        }
    }

    public static void f32ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f32ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f32ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        float[] left = leftView.float32Array();
        float[] right = rightView.float32Array();
        float[] output = outputView.float32Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f32SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        long leftBase = (long) leftView.storageOffset() * Float.BYTES;
        long rightBase = (long) rightView.storageOffset() * Float.BYTES;
        long outputBase = (long) outputView.storageOffset() * Float.BYTES;
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F32.loopBound(rowEnd - i);
            for (; i < upper; i += F32.length()) {
                int vectorInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Float.BYTES;
                (leftMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, left.get(JAVA_FLOAT, leftBase)) : (leftMode == BROADCAST_INNER ? FloatVector.fromMemorySegment(F32, left, leftBase + (long) vectorInner * Float.BYTES, ORDER) : FloatVector.fromMemorySegment(F32, left, leftBase + (long) i * Float.BYTES, ORDER)))
                        .mul((rightMode == BROADCAST_SCALAR ? FloatVector.broadcast(F32, right.get(JAVA_FLOAT, rightBase)) : (rightMode == BROADCAST_INNER ? FloatVector.fromMemorySegment(F32, right, rightBase + (long) vectorInner * Float.BYTES, ORDER) : FloatVector.fromMemorySegment(F32, right, rightBase + (long) i * Float.BYTES, ORDER))))
                        .intoMemorySegment(output, outputOffset, ORDER);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Float.BYTES;
                output.set(JAVA_FLOAT, outputOffset, (leftMode == BROADCAST_SCALAR ? left.get(JAVA_FLOAT, leftBase) : (leftMode == BROADCAST_INNER ? left.get(JAVA_FLOAT, leftBase + (long) scalarInner * Float.BYTES) : left.get(JAVA_FLOAT, leftBase + (long) i * Float.BYTES))) * (rightMode == BROADCAST_SCALAR ? right.get(JAVA_FLOAT, rightBase) : (rightMode == BROADCAST_INNER ? right.get(JAVA_FLOAT, rightBase + (long) scalarInner * Float.BYTES) : right.get(JAVA_FLOAT, rightBase + (long) i * Float.BYTES))));
            }
        }
    }

    public static void f32SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, left.get(JAVA_FLOAT, (long) (leftOffset) * Float.BYTES) * right.get(JAVA_FLOAT, (long) (rightOffset) * Float.BYTES));
        }
    }

    public static void f32SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        long leftBase = (long) leftView.storageOffset() * Float.BYTES;
        long rightBase = (long) rightView.storageOffset() * Float.BYTES;
        long outputBase = (long) outputView.storageOffset() * Float.BYTES;
        int upper = startInclusive + F32.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F32.length()) {
            long byteIndex = (long) i * Float.BYTES;
            FloatVector.fromMemorySegment(F32, left, leftBase + byteIndex, ORDER)
                    .mul(FloatVector.fromMemorySegment(F32, right, rightBase + byteIndex, ORDER))
                    .intoMemorySegment(output, outputBase + byteIndex, ORDER);
        }
        for (; i < endExclusive; i++) {
            long leftOffset = leftBase + (long) i * Float.BYTES;
            long rightOffset = rightBase + (long) i * Float.BYTES;
            long outputOffset = outputBase + (long) i * Float.BYTES;
            output.set(JAVA_FLOAT, outputOffset, left.get(JAVA_FLOAT, leftOffset) * right.get(JAVA_FLOAT, rightOffset));
        }
    }

    public static void f32SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment left = args.input(0).segment();
        MemorySegment right = args.input(1).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output.set(JAVA_FLOAT, (long) (outputOffset.offset(i)) * Float.BYTES, left.get(JAVA_FLOAT, (long) (leftOffset.offset(i)) * Float.BYTES) * right.get(JAVA_FLOAT, (long) (rightOffset.offset(i)) * Float.BYTES));
        }
    }

    public static void f32SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, left.get(JAVA_FLOAT, (long) (leftOffset) * Float.BYTES) * right.get(JAVA_FLOAT, (long) (rightOffset) * Float.BYTES));
        }
    }

    public static void f32SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, left.get(JAVA_FLOAT, (long) (leftOffset) * Float.BYTES) * right.get(JAVA_FLOAT, (long) (rightOffset) * Float.BYTES));
        }
    }

    public static void f32SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output.set(JAVA_FLOAT, (long) (outputOffset) * Float.BYTES, left.get(JAVA_FLOAT, (long) (leftOffset) * Float.BYTES) * right.get(JAVA_FLOAT, (long) (rightOffset) * Float.BYTES));
        }
    }

    public static void f64ArrayBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F64.loopBound(rowEnd - i);
            for (; i < upper; i += F64.length()) {
                int vectorInner = i % innerSize;
                (leftMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, left[leftBase]) : (leftMode == BROADCAST_INNER ? DoubleVector.fromArray(F64, left, leftBase + vectorInner) : DoubleVector.fromArray(F64, left, leftBase + i)))
                        .mul((rightMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, right[rightBase]) : (rightMode == BROADCAST_INNER ? DoubleVector.fromArray(F64, right, rightBase + vectorInner) : DoubleVector.fromArray(F64, right, rightBase + i))))
                        .intoArray(output, outputBase + i);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                output[outputBase + i] = left[leftMode == BROADCAST_SCALAR ? leftBase : (leftMode == BROADCAST_INNER ? leftBase + scalarInner : leftBase + i)] * right[rightMode == BROADCAST_SCALAR ? rightBase : (rightMode == BROADCAST_INNER ? rightBase + scalarInner : rightBase + i)];
            }
        }
    }

    public static void f64ArrayContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f64ArrayContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        int upper = startInclusive + F64.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F64.length()) {
            DoubleVector.fromArray(F64, left, leftBase + i)
                    .mul(DoubleVector.fromArray(F64, right, rightBase + i))
                    .intoArray(output, outputBase + i);
        }
        for (; i < endExclusive; i++) {
            output[outputBase + i] = left[leftBase + i] * right[rightBase + i];
        }
    }

    public static void f64ArrayStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        double[] left = args.input(0).float64Array();
        double[] right = args.input(1).float64Array();
        double[] output = args.output().float64Array();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output[outputOffset.offset(i)] = left[leftOffset.offset(i)] * right[rightOffset.offset(i)];
        }
    }

    public static void f64ArrayStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f64ArrayStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f64ArrayStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        double[] left = leftView.float64Array();
        double[] right = rightView.float64Array();
        double[] output = outputView.float64Array();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output[outputOffset] = left[leftOffset] * right[rightOffset];
        }
    }

    public static void f64SegmentBroadcastInnerVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        long leftBase = (long) leftView.storageOffset() * Double.BYTES;
        long rightBase = (long) rightView.storageOffset() * Double.BYTES;
        long outputBase = (long) outputView.storageOffset() * Double.BYTES;
        int leftMode = broadcastVectorMode(leftView);
        int rightMode = broadcastVectorMode(rightView);
        int innerSize = broadcastVectorInnerSize(outputView);
        int i = startInclusive;
        while (i < endExclusive) {
            int rowInner = i % innerSize;
            int rowEnd = Math.min(endExclusive, i + innerSize - rowInner);
            int upper = i + F64.loopBound(rowEnd - i);
            for (; i < upper; i += F64.length()) {
                int vectorInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Double.BYTES;
                (leftMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, left.get(JAVA_DOUBLE, leftBase)) : (leftMode == BROADCAST_INNER ? DoubleVector.fromMemorySegment(F64, left, leftBase + (long) vectorInner * Double.BYTES, ORDER) : DoubleVector.fromMemorySegment(F64, left, leftBase + (long) i * Double.BYTES, ORDER)))
                        .mul((rightMode == BROADCAST_SCALAR ? DoubleVector.broadcast(F64, right.get(JAVA_DOUBLE, rightBase)) : (rightMode == BROADCAST_INNER ? DoubleVector.fromMemorySegment(F64, right, rightBase + (long) vectorInner * Double.BYTES, ORDER) : DoubleVector.fromMemorySegment(F64, right, rightBase + (long) i * Double.BYTES, ORDER))))
                        .intoMemorySegment(output, outputOffset, ORDER);
            }
            for (; i < rowEnd; i++) {
                int scalarInner = i % innerSize;
                long outputOffset = outputBase + (long) i * Double.BYTES;
                output.set(JAVA_DOUBLE, outputOffset, (leftMode == BROADCAST_SCALAR ? left.get(JAVA_DOUBLE, leftBase) : (leftMode == BROADCAST_INNER ? left.get(JAVA_DOUBLE, leftBase + (long) scalarInner * Double.BYTES) : left.get(JAVA_DOUBLE, leftBase + (long) i * Double.BYTES))) * (rightMode == BROADCAST_SCALAR ? right.get(JAVA_DOUBLE, rightBase) : (rightMode == BROADCAST_INNER ? right.get(JAVA_DOUBLE, rightBase + (long) scalarInner * Double.BYTES) : right.get(JAVA_DOUBLE, rightBase + (long) i * Double.BYTES))));
            }
        }
    }

    public static void f64SegmentContiguousScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int leftOffset = leftBase + i;
            int rightOffset = rightBase + i;
            int outputOffset = outputBase + i;
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, left.get(JAVA_DOUBLE, (long) (leftOffset) * Double.BYTES) * right.get(JAVA_DOUBLE, (long) (rightOffset) * Double.BYTES));
        }
    }

    public static void f64SegmentContiguousVector(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        long leftBase = (long) leftView.storageOffset() * Double.BYTES;
        long rightBase = (long) rightView.storageOffset() * Double.BYTES;
        long outputBase = (long) outputView.storageOffset() * Double.BYTES;
        int upper = startInclusive + F64.loopBound(endExclusive - startInclusive);
        int i = startInclusive;
        for (; i < upper; i += F64.length()) {
            long byteIndex = (long) i * Double.BYTES;
            DoubleVector.fromMemorySegment(F64, left, leftBase + byteIndex, ORDER)
                    .mul(DoubleVector.fromMemorySegment(F64, right, rightBase + byteIndex, ORDER))
                    .intoMemorySegment(output, outputBase + byteIndex, ORDER);
        }
        for (; i < endExclusive; i++) {
            long leftOffset = leftBase + (long) i * Double.BYTES;
            long rightOffset = rightBase + (long) i * Double.BYTES;
            long outputOffset = outputBase + (long) i * Double.BYTES;
            output.set(JAVA_DOUBLE, outputOffset, left.get(JAVA_DOUBLE, leftOffset) * right.get(JAVA_DOUBLE, rightOffset));
        }
    }

    public static void f64SegmentStridedGenericScalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        MemorySegment left = args.input(0).segment();
        MemorySegment right = args.input(1).segment();
        MemorySegment output = args.output().segment();
        Cpu1GenericOffsetPlan leftOffset = args.inputGenericOffsetPlan(0);
        Cpu1GenericOffsetPlan rightOffset = args.inputGenericOffsetPlan(1);
        Cpu1GenericOffsetPlan outputOffset = args.outputGenericOffsetPlan();
        for (int i = startInclusive; i < endExclusive; i++) {
            output.set(JAVA_DOUBLE, (long) (outputOffset.offset(i)) * Double.BYTES, left.get(JAVA_DOUBLE, (long) (leftOffset.offset(i)) * Double.BYTES) * right.get(JAVA_DOUBLE, (long) (rightOffset.offset(i)) * Double.BYTES));
        }
    }

    public static void f64SegmentStridedRank2Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c0 = i / d1;
            int c1 = i - c0 * d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, left.get(JAVA_DOUBLE, (long) (leftOffset) * Double.BYTES) * right.get(JAVA_DOUBLE, (long) (rightOffset) * Double.BYTES));
        }
    }

    public static void f64SegmentStridedRank3Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c2 = i % d2;
            int rem = i / d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, left.get(JAVA_DOUBLE, (long) (leftOffset) * Double.BYTES) * right.get(JAVA_DOUBLE, (long) (rightOffset) * Double.BYTES));
        }
    }

    public static void f64SegmentStridedRank4Scalar(Cpu1KernelArgs args, int startInclusive, int endExclusive) {
        Cpu1TensorView leftView = args.input(0);
        Cpu1TensorView rightView = args.input(1);
        Cpu1TensorView outputView = args.output();
        MemorySegment left = leftView.segment();
        MemorySegment right = rightView.segment();
        MemorySegment output = outputView.segment();
        int d1 = outputView.shape(1);
        int d2 = outputView.shape(2);
        int d3 = outputView.shape(3);
        int leftBase = leftView.storageOffset();
        int rightBase = rightView.storageOffset();
        int outputBase = outputView.storageOffset();
        for (int i = startInclusive; i < endExclusive; i++) {
            int c3 = i % d3;
            int rem = i / d3;
            int c2 = rem % d2;
            rem /= d2;
            int c1 = rem % d1;
            int c0 = rem / d1;
            int leftOffset = leftBase + c0 * leftView.stride(0) + c1 * leftView.stride(1) + c2 * leftView.stride(2) + c3 * leftView.stride(3);
            int rightOffset = rightBase + c0 * rightView.stride(0) + c1 * rightView.stride(1) + c2 * rightView.stride(2) + c3 * rightView.stride(3);
            int outputOffset = outputBase + c0 * outputView.stride(0) + c1 * outputView.stride(1) + c2 * outputView.stride(2) + c3 * outputView.stride(3);
            output.set(JAVA_DOUBLE, (long) (outputOffset) * Double.BYTES, left.get(JAVA_DOUBLE, (long) (leftOffset) * Double.BYTES) * right.get(JAVA_DOUBLE, (long) (rightOffset) * Double.BYTES));
        }
    }
}
