package backend.accelerator.buffer;

/**
 * Stable reason codes for accelerator buffer decisions.
 */
public enum AcceleratorBufferReasonCode {
    NOT_EVALUATED,
    BUFFER_BINDINGS_DISABLED,
    BRIDGE_UNAVAILABLE,
    BELOW_MINIMUM_WORK,
    BUFFER_ALLOCATOR_UNAVAILABLE,
    BACKEND_BUFFER_NOT_IMPLEMENTED,
    INPUT_NOT_CPU_CURRENT,
    INPUT_NOT_CONTIGUOUS,
    PREPARED_INPUT_REQUIRED,
    PREPARED_INPUT_MATERIALIZATION_DISABLED,
    PREPARED_INPUT_CONFLICT,
    INPUT_DTYPE_UNSUPPORTED,
    INPUT_BINDING_UNAVAILABLE,
    OUTPUT_LAYOUT_UNSUPPORTED,
    OUTPUT_DTYPE_UNSUPPORTED,
    OUTPUT_BINDING_UNAVAILABLE,
    NATIVE_BUFFER_EXECUTION_FAILED,
    BUFFER_BINDING_AVAILABLE,
    TENSOR_ARRAY_SELECTED,
    CPU_FALLBACK_SELECTED,
    INPUT_LAYOUT_UNSUPPORTED,
    NATIVE_BUFFER_ABI_UNAVAILABLE,
    REQUIRED_BUFFER_EXECUTION_UNAVAILABLE,
    NATIVE_LAYOUT_ABI_UNAVAILABLE,
    NATIVE_LAYOUT_ABI_VERSION_MISMATCH,
    NATIVE_LAYOUT_METADATA_UNSUPPORTED,
    NATIVE_LAYOUT_RANK_UNSUPPORTED,
    NATIVE_LAYOUT_DTYPE_UNSUPPORTED,
    NATIVE_LAYOUT_PHYSICAL_SPAN_OVERFLOW
}
