package backend.cpu1.kernels.linalg.attention;

/**
 * Dense scaled dot-product attention kernels supported by cpu1.
 */
public enum Cpu1AttentionKernelId {
    ATTENTION_F32_ARRAY_DENSE_SCALAR,
    ATTENTION_F32_ARRAY_DENSE_VECTOR,
    ATTENTION_F64_ARRAY_DENSE_SCALAR,
    ATTENTION_F64_ARRAY_DENSE_VECTOR,
    ATTENTION_BF16_ARRAY_DENSE_SCALAR,
    ATTENTION_F32_SEGMENT_DENSE_SCALAR,
    ATTENTION_F32_SEGMENT_DENSE_VECTOR,
    ATTENTION_F64_SEGMENT_DENSE_SCALAR,
    ATTENTION_F64_SEGMENT_DENSE_VECTOR,
    ATTENTION_BF16_SEGMENT_DENSE_SCALAR,
    ATTENTION_WEIGHTS_F32_ARRAY_DENSE_SCALAR,
    ATTENTION_WEIGHTS_F64_ARRAY_DENSE_SCALAR,
    ATTENTION_WEIGHTS_BF16_ARRAY_DENSE_SCALAR,
    ATTENTION_WEIGHTS_F32_SEGMENT_DENSE_SCALAR,
    ATTENTION_WEIGHTS_F64_SEGMENT_DENSE_SCALAR,
    ATTENTION_WEIGHTS_BF16_SEGMENT_DENSE_SCALAR
}
