package backend.cpu.fused.numeric;

/**
 * JVM scalar compute primitive used by fused generated bytecode.
 */
public enum FusedComputeKind {
    F32(1),
    F64(2);

    private final int localSlots;

    FusedComputeKind(int localSlots) {
        this.localSlots = localSlots;
    }

    public int localSlots() {
        return localSlots;
    }
}
